.TH "ActionGroupList" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionGroupList \- The list of groups defining a \fIroot\fP \fBAction\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <action\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBcontains\fP (const string &nm) const"
.br
.RI "Check if \fBthis\fP \fBActionGroupList\fP contains a given group\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBActionDatabase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The list of groups defining a \fIroot\fP \fBAction\fP\&. 

Any \fBRule\fP or \fIleaf\fP \fBAction\fP belongs to a \fBgroup\fP\&. This class is a \fBgrouplist\fP defined by a collection of these \fBgroup\fP names\&. The set of \fBRule\fP and \fBAction\fP objects belong to any of the groups in this list together form a \fBroot\fP \fBAction\fP\&. 
.PP
Definition at line 29 of file action\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ActionGroupList::contains (const string & nm) const\fC [inline]\fP"

.PP
Check if \fBthis\fP \fBActionGroupList\fP contains a given group\&. 
.PP
\fBParameters:\fP
.RS 4
\fInm\fP is the given group to check for 
.RE
.PP
\fBReturns:\fP
.RS 4
true if \fBthis\fP contains the group 
.RE
.PP

.PP
Definition at line 37 of file action\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBActionDatabase\fP\fC [friend]\fP"

.PP
Definition at line 30 of file action\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
