.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/action.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/action.hh \- \fBAction\fP, \fBRule\fP, and other associates classes supporting transformations on function data-flow\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'block\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionGroupList\fP"
.br
.RI "The list of groups defining a \fIroot\fP \fBAction\fP\&. "
.ti -1c
.RI "class \fBAction\fP"
.br
.RI "Large scale transformations applied to the varnode/op graph\&. "
.ti -1c
.RI "class \fBActionGroup\fP"
.br
.RI "A group of actions (generally) applied in sequence\&. "
.ti -1c
.RI "class \fBActionRestartGroup\fP"
.br
.RI "\fBAction\fP which checks if restart (sub)actions have been generated and restarts itself\&. "
.ti -1c
.RI "class \fBRule\fP"
.br
.RI "Class for performing a single transformation on a \fBPcodeOp\fP or \fBVarnode\fP\&. "
.ti -1c
.RI "class \fBActionPool\fP"
.br
.RI "A pool of Rules that apply simultaneously\&. "
.ti -1c
.RI "class \fBActionDatabase\fP"
.br
.RI "\fBDatabase\fP of root \fBAction\fP objects that can be used to transform a function\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBAction\fP, \fBRule\fP, and other associates classes supporting transformations on function data-flow\&. 


.PP
Definition in file \fBaction\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
