.TH "AliasChecker::AddBase" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AliasChecker::AddBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <varmap\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddBase\fP (\fBVarnode\fP *b, \fBVarnode\fP *i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVarnode\fP * \fBbase\fP"
.br
.ti -1c
.RI "\fBVarnode\fP * \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file varmap\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AliasChecker::AddBase::AddBase (\fBVarnode\fP * b, \fBVarnode\fP * i)\fC [inline]\fP"

.PP
Definition at line 62 of file varmap\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVarnode\fP* AliasChecker::AddBase::base"

.PP
Definition at line 60 of file varmap\&.hh\&.
.SS "\fBVarnode\fP* AliasChecker::AddBase::index"

.PP
Definition at line 61 of file varmap\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
