.TH "Attributes" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xml\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributes\fP (string *el)"
.br
.ti -1c
.RI "\fB~Attributes\fP (void)"
.br
.ti -1c
.RI "const string & \fBgetelemURI\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetelemName\fP (void) const"
.br
.ti -1c
.RI "void \fBadd_attribute\fP (string *nm, string *vl)"
.br
.ti -1c
.RI "int4 \fBgetLength\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetURI\fP (int4 index) const"
.br
.ti -1c
.RI "const string & \fBgetLocalName\fP (int4 index) const"
.br
.ti -1c
.RI "const string & \fBgetQName\fP (int4 index) const"
.br
.ti -1c
.RI "const string & \fBgetValue\fP (int4 index) const"
.br
.ti -1c
.RI "const string & \fBgetValue\fP (const string &qualifiedName) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file xml\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Attributes::Attributes (string * el)\fC [inline]\fP"

.PP
Definition at line 35 of file xml\&.hh\&.
.SS "Attributes::~Attributes (void)\fC [inline]\fP"

.PP
Definition at line 36 of file xml\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void Attributes::add_attribute (string * nm, string * vl)\fC [inline]\fP"

.PP
Definition at line 42 of file xml\&.hh\&.
.SS "const string& Attributes::getelemName (void) const\fC [inline]\fP"

.PP
Definition at line 41 of file xml\&.hh\&.
.SS "const string& Attributes::getelemURI (void) const\fC [inline]\fP"

.PP
Definition at line 40 of file xml\&.hh\&.
.SS "int4 Attributes::getLength (void) const\fC [inline]\fP"

.PP
Definition at line 44 of file xml\&.hh\&.
.SS "const string& Attributes::getLocalName (int4 index) const\fC [inline]\fP"

.PP
Definition at line 46 of file xml\&.hh\&.
.SS "const string& Attributes::getQName (int4 index) const\fC [inline]\fP"

.PP
Definition at line 47 of file xml\&.hh\&.
.SS "const string& Attributes::getURI (int4 index) const\fC [inline]\fP"

.PP
Definition at line 45 of file xml\&.hh\&.
.SS "const string& Attributes::getValue (int4 index) const\fC [inline]\fP"

.PP
Definition at line 53 of file xml\&.hh\&.
.SS "const string& Attributes::getValue (const string & qualifiedName) const\fC [inline]\fP"

.PP
Definition at line 55 of file xml\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
