.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/bfd_arch.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/bfd_arch.hh \- Specific implementation of \fBArchitecture\fP using GNU BFD libraries\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sleigh_arch\&.hh'\fP
.br
\fC#include 'loadimage_bfd\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBfdArchitectureCapability\fP"
.br
.RI "Extension point for building a GNU BFD capable \fBArchitecture\fP\&. "
.ti -1c
.RI "class \fBBfdArchitecture\fP"
.br
.RI "\fBArchitecture\fP that reads executable files using GNU BFD libraries\&. "
.in -1c
.SH "Detailed Description"
.PP 
Specific implementation of \fBArchitecture\fP using GNU BFD libraries\&. 


.PP
Definition in file \fBbfd_arch\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
