.TH "BinaryExpression" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternExpression\fP\&.
.PP
Inherited by \fBAndExpression\fP, \fBDivExpression\fP, \fBLeftShiftExpression\fP, \fBMultExpression\fP, \fBOrExpression\fP, \fBPlusExpression\fP, \fBRightShiftExpression\fP, \fBSubExpression\fP, and \fBXorExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryExpression\fP (void)"
.br
.ti -1c
.RI "\fBBinaryExpression\fP (\fBPatternExpression\fP *l, \fBPatternExpression\fP *r)"
.br
.ti -1c
.RI "\fBPatternExpression\fP * \fBgetLeft\fP (void) const"
.br
.ti -1c
.RI "\fBPatternExpression\fP * \fBgetRight\fP (void) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenMinPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.ti -1c
.RI "virtual void \fBlistValues\fP (vector< const \fBPatternValue\fP * > &list) const"
.br
.ti -1c
.RI "virtual void \fBgetMinMax\fP (vector< \fBintb\fP > &minlist, vector< \fBintb\fP > &maxlist) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBTranslate\fP *trans)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~BinaryExpression\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 189 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BinaryExpression::~BinaryExpression (void)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 812 of file slghpatexpress\&.cc\&.
.SS "BinaryExpression::BinaryExpression (void)\fC [inline]\fP"

.PP
Definition at line 194 of file slghpatexpress\&.hh\&.
.SS "BinaryExpression::BinaryExpression (\fBPatternExpression\fP * l, \fBPatternExpression\fP * r)"

.PP
Definition at line 805 of file slghpatexpress\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTokenPattern\fP BinaryExpression::genMinPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 198 of file slghpatexpress\&.hh\&.
.SS "\fBPatternExpression\fP* BinaryExpression::getLeft (void) const\fC [inline]\fP"

.PP
Definition at line 196 of file slghpatexpress\&.hh\&.
.SS "virtual void BinaryExpression::getMinMax (vector< \fBintb\fP > & minlist, vector< \fBintb\fP > & maxlist) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 201 of file slghpatexpress\&.hh\&.
.SS "\fBPatternExpression\fP* BinaryExpression::getRight (void) const\fC [inline]\fP"

.PP
Definition at line 197 of file slghpatexpress\&.hh\&.
.SS "virtual void BinaryExpression::listValues (vector< const \fBPatternValue\fP * > & list) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 199 of file slghpatexpress\&.hh\&.
.SS "void BinaryExpression::restoreXml (const \fBElement\fP * el, \fBTranslate\fP * trans)\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 828 of file slghpatexpress\&.cc\&.
.SS "void BinaryExpression::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Reimplemented in \fBDivExpression\fP, \fBXorExpression\fP, \fBOrExpression\fP, \fBAndExpression\fP, \fBRightShiftExpression\fP, \fBLeftShiftExpression\fP, \fBMultExpression\fP, \fBSubExpression\fP, and \fBPlusExpression\fP\&.
.PP
Definition at line 821 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
