.TH "BitrangeSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitrangeSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSleighSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBitrangeSymbol\fP (void)"
.br
.ti -1c
.RI "\fBBitrangeSymbol\fP (const string &nm, \fBVarnodeSymbol\fP *sym, uint4 bitoff, uint4 num)"
.br
.ti -1c
.RI "\fBVarnodeSymbol\fP * \fBgetParentSymbol\fP (void) const"
.br
.ti -1c
.RI "uint4 \fBgetBitOffset\fP (void) const"
.br
.ti -1c
.RI "uint4 \fBnumBits\fP (void) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 263 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BitrangeSymbol::BitrangeSymbol (void)\fC [inline]\fP"

.PP
Definition at line 268 of file slghsymbol\&.hh\&.
.SS "BitrangeSymbol::BitrangeSymbol (const string & nm, \fBVarnodeSymbol\fP * sym, uint4 bitoff, uint4 num)\fC [inline]\fP"

.PP
Definition at line 269 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "uint4 BitrangeSymbol::getBitOffset (void) const\fC [inline]\fP"

.PP
Definition at line 272 of file slghsymbol\&.hh\&.
.SS "\fBVarnodeSymbol\fP* BitrangeSymbol::getParentSymbol (void) const\fC [inline]\fP"

.PP
Definition at line 271 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP BitrangeSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 274 of file slghsymbol\&.hh\&.
.SS "uint4 BitrangeSymbol::numBits (void) const\fC [inline]\fP"

.PP
Definition at line 273 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
