.TH "BlockMultiGoto" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMultiGoto \- A block with multiple edges out, at least one of which is an unstructured (goto) branch\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.hh>\fP
.PP
Inherits \fBBlockGraph\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockMultiGoto\fP (\fBFlowBlock\fP *bl)"
.br
.RI "Construct given the underlying multi-exit block\&. "
.ti -1c
.RI "void \fBsetDefaultGoto\fP (void)"
.br
.RI "Mark that this block holds an unstructured switch default\&. "
.ti -1c
.RI "bool \fBhasDefaultGoto\fP (void) const"
.br
.RI "Does this block hold an unstructured switch default edge\&. "
.ti -1c
.RI "void \fBaddEdge\fP (\fBFlowBlock\fP *bl)"
.br
.RI "Mark the edge from \fBthis\fP to the given \fBFlowBlock\fP as unstructured\&. "
.ti -1c
.RI "int4 \fBnumGotos\fP (void) const"
.br
.RI "Get the number of unstructured edges\&. "
.ti -1c
.RI "\fBFlowBlock\fP * \fBgetGoto\fP (int4 i) const"
.br
.RI "Get the target \fBFlowBlock\fP along the i-th unstructured edge\&. "
.ti -1c
.RI "virtual \fBblock_type\fP \fBgetType\fP (void) const"
.br
.RI "Get the \fBFlowBlock\fP type of \fBthis\fP\&. "
.ti -1c
.RI "virtual void \fBscopeBreak\fP (int4 curexit, int4 curloopexit)"
.br
.RI "Mark unstructured edges that should be \fIbreaks\fP\&. "
.ti -1c
.RI "virtual void \fBprintHeader\fP (ostream &s) const"
.br
.RI "Print a simple description of \fBthis\fP to stream\&. "
.ti -1c
.RI "virtual void \fBprintRaw\fP (ostream &s) const"
.br
.RI "Print raw instructions contained in \fBthis\fP \fBFlowBlock\fP\&. "
.ti -1c
.RI "virtual void \fBemit\fP (\fBPrintLanguage\fP *lng) const"
.br
.RI "Emit the instructions in \fBthis\fP \fBFlowBlock\fP as structured code\&. "
.ti -1c
.RI "virtual const \fBFlowBlock\fP * \fBgetExitLeaf\fP (void) const"
.br
.RI "Get the \fBFlowBlock\fP to which \fBthis\fP block exits\&. "
.ti -1c
.RI "virtual \fBPcodeOp\fP * \fBlastOp\fP (void) const"
.br
.RI "Get the last \fBPcodeOp\fP executed by \fBthis\fP \fBFlowBlock\fP\&. "
.ti -1c
.RI "virtual \fBFlowBlock\fP * \fBnextFlowAfter\fP (const \fBFlowBlock\fP *bl) const"
.br
.RI "Get the leaf \fBFlowBlock\fP that will execute after the given \fBFlowBlock\fP\&. "
.ti -1c
.RI "virtual void \fBsaveXmlBody\fP (ostream &s) const"
.br
.RI "Save detail about components to an XML stream\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A block with multiple edges out, at least one of which is an unstructured (goto) branch\&. 

An instance of this class is used to mirror a basic block with multiple out edges at the point where one of the edges can't be structured\&. The instance keeps track of this edge but otherwise presents a view to the structuring algorithm as if the edge didn't exist\&. If at a later point, more edges can't be structured, the one instance can hold this information as well\&. 
.PP
Definition at line 465 of file block\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockMultiGoto::BlockMultiGoto (\fBFlowBlock\fP * bl)\fC [inline]\fP"

.PP
Construct given the underlying multi-exit block\&. 
.PP
Definition at line 469 of file block\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void BlockMultiGoto::addEdge (\fBFlowBlock\fP * bl)\fC [inline]\fP"

.PP
Mark the edge from \fBthis\fP to the given \fBFlowBlock\fP as unstructured\&. 
.PP
Definition at line 472 of file block\&.hh\&.
.SS "virtual void BlockMultiGoto::emit (\fBPrintLanguage\fP * lng) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Emit the instructions in \fBthis\fP \fBFlowBlock\fP as structured code\&. This is the main entry point, at the control-flow level, for printing structured code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlng\fP is the \fBPrintLanguage\fP that provides details of the high-level language being printed 
.RE
.PP

.PP
Reimplemented from \fBBlockGraph\fP\&.
.PP
Definition at line 480 of file block\&.hh\&.
.SS "virtual const \fBFlowBlock\fP* BlockMultiGoto::getExitLeaf (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the \fBFlowBlock\fP to which \fBthis\fP block exits\&. 
.PP
Reimplemented from \fBFlowBlock\fP\&.
.PP
Definition at line 481 of file block\&.hh\&.
.SS "\fBFlowBlock\fP* BlockMultiGoto::getGoto (int4 i) const\fC [inline]\fP"

.PP
Get the target \fBFlowBlock\fP along the i-th unstructured edge\&. 
.PP
Definition at line 474 of file block\&.hh\&.
.SS "virtual \fBblock_type\fP BlockMultiGoto::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the \fBFlowBlock\fP type of \fBthis\fP\&. 
.PP
Reimplemented from \fBBlockGraph\fP\&.
.PP
Definition at line 476 of file block\&.hh\&.
.SS "bool BlockMultiGoto::hasDefaultGoto (void) const\fC [inline]\fP"

.PP
Does this block hold an unstructured switch default edge\&. 
.PP
Definition at line 471 of file block\&.hh\&.
.SS "virtual \fBPcodeOp\fP* BlockMultiGoto::lastOp (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the last \fBPcodeOp\fP executed by \fBthis\fP \fBFlowBlock\fP\&. 
.PP
Reimplemented from \fBFlowBlock\fP\&.
.PP
Definition at line 482 of file block\&.hh\&.
.SS "\fBFlowBlock\fP * BlockMultiGoto::nextFlowAfter (const \fBFlowBlock\fP * bl) const\fC [virtual]\fP"

.PP
Get the leaf \fBFlowBlock\fP that will execute after the given \fBFlowBlock\fP\&. Within the hierarchy of \fBthis\fP \fBFlowBlock\fP, assume the given \fBFlowBlock\fP will fall-thru in its execution at some point\&. Return the first leaf block (\fBBlockBasic\fP or \fBBlockCopy\fP) that will execute after the given \fBFlowBlock\fP completes, assuming this is a unique block\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbl\fP is the given \fBFlowBlock\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the next \fBFlowBlock\fP to execute or NULL 
.RE
.PP

.PP
Reimplemented from \fBBlockGraph\fP\&.
.PP
Definition at line 2618 of file block\&.cc\&.
.SS "int4 BlockMultiGoto::numGotos (void) const\fC [inline]\fP"

.PP
Get the number of unstructured edges\&. 
.PP
Definition at line 473 of file block\&.hh\&.
.SS "void BlockMultiGoto::printHeader (ostream & s) const\fC [virtual]\fP"

.PP
Print a simple description of \fBthis\fP to stream\&. Only print a header for \fBthis\fP single block 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the output stream 
.RE
.PP

.PP
Reimplemented from \fBFlowBlock\fP\&.
.PP
Definition at line 2611 of file block\&.cc\&.
.SS "virtual void BlockMultiGoto::printRaw (ostream & s) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Print raw instructions contained in \fBthis\fP \fBFlowBlock\fP\&. 
.PP
Reimplemented from \fBBlockGraph\fP\&.
.PP
Definition at line 479 of file block\&.hh\&.
.SS "void BlockMultiGoto::saveXmlBody (ostream & s) const\fC [virtual]\fP"

.PP
Save detail about components to an XML stream\&. 
.PP
Reimplemented from \fBBlockGraph\fP\&.
.PP
Definition at line 2625 of file block\&.cc\&.
.SS "void BlockMultiGoto::scopeBreak (int4 curexit, int4 curloopexit)\fC [virtual]\fP"

.PP
Mark unstructured edges that should be \fIbreaks\fP\&. 
.PP
Reimplemented from \fBBlockGraph\fP\&.
.PP
Definition at line 2605 of file block\&.cc\&.
.SS "void BlockMultiGoto::setDefaultGoto (void)\fC [inline]\fP"

.PP
Mark that this block holds an unstructured switch default\&. 
.PP
Definition at line 470 of file block\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
