.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/codedata.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/codedata.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'ifacedecomp\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIfaceCodeDataCapability\fP"
.br
.ti -1c
.RI "class \fBCodeUnit\fP"
.br
.ti -1c
.RI "struct \fBDisassemblyResult\fP"
.br
.ti -1c
.RI "class \fBDisassemblyEngine\fP"
.br
.ti -1c
.RI "class \fBTargetHit\fP"
.br
.ti -1c
.RI "struct \fBTargetFeature\fP"
.br
.ti -1c
.RI "struct \fBAddrLink\fP"
.br
.ti -1c
.RI "class \fBCodeDataAnalysis\fP"
.br
.ti -1c
.RI "class \fBIfaceCodeDataCommand\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataInit\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataTarget\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataRun\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataDumpModelHits\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataDumpCrossRefs\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataDumpStarts\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataDumpUnlinked\fP"
.br
.ti -1c
.RI "class \fBIfcCodeDataDumpTargetHits\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
