.TH "CodeUnit" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodeUnit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codedata\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBfallthru\fP = 1, \fBjump\fP = 2, \fBcall\fP = 4, \fBnotcode\fP = 8, \fBhit_by_fallthru\fP = 16, \fBhit_by_jump\fP = 32, \fBhit_by_call\fP = 64, \fBerrantstart\fP = 128, \fBtargethit\fP = 256, \fBthunkhit\fP = 512 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint4 \fBflags\fP"
.br
.ti -1c
.RI "int4 \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file codedata\&.hh\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIfallthru \fP\fP
.TP
\fB\fIjump \fP\fP
.TP
\fB\fIcall \fP\fP
.TP
\fB\fInotcode \fP\fP
.TP
\fB\fIhit_by_fallthru \fP\fP
.TP
\fB\fIhit_by_jump \fP\fP
.TP
\fB\fIhit_by_call \fP\fP
.TP
\fB\fIerrantstart \fP\fP
.TP
\fB\fItargethit \fP\fP
.TP
\fB\fIthunkhit \fP\fP
.PP
Definition at line 34 of file codedata\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "uint4 CodeUnit::flags"

.PP
Definition at line 46 of file codedata\&.hh\&.
.SS "int4 CodeUnit::size"

.PP
Definition at line 47 of file codedata\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
