.TH "CombinePattern" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CombinePattern
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpattern\&.hh>\fP
.PP
Inherits \fBDisjointPattern\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCombinePattern\fP (void)"
.br
.ti -1c
.RI "\fBCombinePattern\fP (\fBContextPattern\fP *con, \fBInstructionPattern\fP *in)"
.br
.ti -1c
.RI "virtual \fB~CombinePattern\fP (void)"
.br
.ti -1c
.RI "virtual \fBPattern\fP * \fBsimplifyClone\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBshiftInstruction\fP (int4 sa)"
.br
.ti -1c
.RI "virtual bool \fBisMatch\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual bool \fBalwaysTrue\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBalwaysFalse\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBalwaysInstructionTrue\fP (void) const"
.br
.ti -1c
.RI "virtual \fBPattern\fP * \fBdoOr\fP (const \fBPattern\fP *b, int4 sa) const"
.br
.ti -1c
.RI "virtual \fBPattern\fP * \fBdoAnd\fP (const \fBPattern\fP *b, int4 sa) const"
.br
.ti -1c
.RI "virtual \fBPattern\fP * \fBcommonSubPattern\fP (const \fBPattern\fP *b, int4 sa) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 127 of file slghpattern\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CombinePattern::CombinePattern (void)\fC [inline]\fP"

.PP
Definition at line 132 of file slghpattern\&.hh\&.
.SS "CombinePattern::CombinePattern (\fBContextPattern\fP * con, \fBInstructionPattern\fP * in)\fC [inline]\fP"

.PP
Definition at line 133 of file slghpattern\&.hh\&.
.SS "CombinePattern::~CombinePattern (void)\fC [virtual]\fP"

.PP
Definition at line 692 of file slghpattern\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CombinePattern::alwaysFalse (void) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 715 of file slghpattern\&.cc\&.
.SS "virtual bool CombinePattern::alwaysInstructionTrue (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 141 of file slghpattern\&.hh\&.
.SS "bool CombinePattern::alwaysTrue (void) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 709 of file slghpattern\&.cc\&.
.SS "\fBPattern\fP * CombinePattern::commonSubPattern (const \fBPattern\fP * b, int4 sa) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 752 of file slghpattern\&.cc\&.
.SS "\fBPattern\fP * CombinePattern::doAnd (const \fBPattern\fP * b, int4 sa) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 721 of file slghpattern\&.cc\&.
.SS "\fBPattern\fP * CombinePattern::doOr (const \fBPattern\fP * b, int4 sa) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 776 of file slghpattern\&.cc\&.
.SS "bool CombinePattern::isMatch (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 701 of file slghpattern\&.cc\&.
.SS "void CombinePattern::restoreXml (const \fBElement\fP * el)\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 814 of file slghpattern\&.cc\&.
.SS "void CombinePattern::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 805 of file slghpattern\&.cc\&.
.SS "virtual void CombinePattern::shiftInstruction (int4 sa)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 137 of file slghpattern\&.hh\&.
.SS "\fBPattern\fP * CombinePattern::simplifyClone (void) const\fC [virtual]\fP"

.PP
Implements \fBPattern\fP\&.
.PP
Definition at line 792 of file slghpattern\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
