.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/comment.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/comment.hh \- A database interface for high-level language comments\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'address\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComment\fP"
.br
.RI "A comment attached to a specific function and code address\&. "
.ti -1c
.RI "struct \fBCommentOrder\fP"
.br
.RI "Compare two \fBComment\fP pointers\&. "
.ti -1c
.RI "class \fBCommentDatabase\fP"
.br
.RI "An interface to a container of comments\&. "
.ti -1c
.RI "class \fBCommentDatabaseInternal\fP"
.br
.RI "An in-memory implementation of the \fBCommentDatabase\fP API\&. "
.ti -1c
.RI "class \fBCommentSorter\fP"
.br
.RI "A class for sorting comments into and within basic blocks\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef set< \fBComment\fP *, \fBCommentOrder\fP > \fBCommentSet\fP"
.br
.RI "A set of comments sorted by function and address\&. "
.in -1c
.SH "Detailed Description"
.PP 
A database interface for high-level language comments\&. 


.PP
Definition in file \fBcomment\&.hh\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef set<\fBComment\fP *,\fBCommentOrder\fP> \fBCommentSet\fP"

.PP
A set of comments sorted by function and address\&. 
.PP
Definition at line 76 of file comment\&.hh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
