.TH "CompilerTag" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompilerTag \- Contents of a <compiler> tag in a \&.ldefs file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sleigh_arch\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompilerTag\fP (void)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "void \fBrestoreXml\fP (const \fBElement\fP *el)"
.br
.RI "Restore the record from an XML stream\&. "
.ti -1c
.RI "const string & \fBgetName\fP (void) const"
.br
.RI "Get the human readable name of the spec\&. "
.ti -1c
.RI "const string & \fBgetSpec\fP (void) const"
.br
.RI "Get the file-name\&. "
.ti -1c
.RI "const string & \fBgetId\fP (void) const"
.br
.RI "Get the string used as part of \fIlanguage\fP \fIid\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contents of a <compiler> tag in a \&.ldefs file\&. 

This class describes a compiler specification file as referenced by the \fBSleigh\fP language subsystem\&. 
.PP
Definition at line 29 of file sleigh_arch\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CompilerTag::CompilerTag (void)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 34 of file sleigh_arch\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "const string& CompilerTag::getId (void) const\fC [inline]\fP"

.PP
Get the string used as part of \fIlanguage\fP \fIid\fP\&. 
.PP
Definition at line 38 of file sleigh_arch\&.hh\&.
.SS "const string& CompilerTag::getName (void) const\fC [inline]\fP"

.PP
Get the human readable name of the spec\&. 
.PP
Definition at line 36 of file sleigh_arch\&.hh\&.
.SS "const string& CompilerTag::getSpec (void) const\fC [inline]\fP"

.PP
Get the file-name\&. 
.PP
Definition at line 37 of file sleigh_arch\&.hh\&.
.SS "void CompilerTag::restoreXml (const \fBElement\fP * el)"

.PP
Restore the record from an XML stream\&. Read file attributes from an XML <compiler> tag 
.PP
\fBParameters:\fP
.RS 4
\fIel\fP is the XML element 
.RE
.PP

.PP
Definition at line 27 of file sleigh_arch\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
