.TH "ConstraintOpCopy" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstraintOpCopy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBUnifyConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstraintOpCopy\fP (int4 oldind, int4 newind)"
.br
.ti -1c
.RI "virtual \fBUnifyConstraint\fP * \fBclone\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBstep\fP (\fBUnifyState\fP &state)"
.br
.ti -1c
.RI "virtual void \fBcollectTypes\fP (vector< \fBUnifyDatatype\fP > &typelist) const"
.br
.ti -1c
.RI "virtual int4 \fBgetBaseIndex\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 296 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConstraintOpCopy::ConstraintOpCopy (int4 oldind, int4 newind)\fC [inline]\fP"

.PP
Definition at line 300 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBUnifyConstraint\fP* ConstraintOpCopy::clone (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.
.PP
Definition at line 301 of file unify\&.hh\&.
.SS "virtual void ConstraintOpCopy::collectTypes (vector< \fBUnifyDatatype\fP > & typelist) const\fC [virtual]\fP"

.PP
Reimplemented from \fBUnifyConstraint\fP\&.
.SS "virtual int4 ConstraintOpCopy::getBaseIndex (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUnifyConstraint\fP\&.
.PP
Definition at line 304 of file unify\&.hh\&.
.SS "virtual void ConstraintOpCopy::print (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.
.SS "virtual bool ConstraintOpCopy::step (\fBUnifyState\fP & state)\fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
