.TH "ConstructState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstructState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <context\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConstructor\fP * \fBct\fP"
.br
.ti -1c
.RI "\fBFixedHandle\fP \fBhand\fP"
.br
.ti -1c
.RI "vector< \fBConstructState\fP * > \fBresolve\fP"
.br
.ti -1c
.RI "\fBConstructState\fP * \fBparent\fP"
.br
.ti -1c
.RI "int4 \fBlength\fP"
.br
.ti -1c
.RI "uint4 \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file context\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConstructor\fP* ConstructState::ct"

.PP
Definition at line 47 of file context\&.hh\&.
.SS "\fBFixedHandle\fP ConstructState::hand"

.PP
Definition at line 48 of file context\&.hh\&.
.SS "int4 ConstructState::length"

.PP
Definition at line 51 of file context\&.hh\&.
.SS "uint4 ConstructState::offset"

.PP
Definition at line 52 of file context\&.hh\&.
.SS "\fBConstructState\fP* ConstructState::parent"

.PP
Definition at line 50 of file context\&.hh\&.
.SS "vector<\fBConstructState\fP *> ConstructState::resolve"

.PP
Definition at line 49 of file context\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
