.TH "ConstantValue" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantValue\fP (void)"
.br
.ti -1c
.RI "\fBConstantValue\fP (\fBintb\fP v)"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenMinPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenPattern\fP (\fBintb\fP v) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBminValue\fP (void) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBmaxValue\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBTranslate\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 128 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConstantValue::ConstantValue (void)\fC [inline]\fP"

.PP
Definition at line 131 of file slghpatexpress\&.hh\&.
.SS "ConstantValue::ConstantValue (\fBintb\fP v)\fC [inline]\fP"

.PP
Definition at line 132 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTokenPattern\fP ConstantValue::genMinPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 134 of file slghpatexpress\&.hh\&.
.SS "virtual \fBTokenPattern\fP ConstantValue::genPattern (\fBintb\fP v) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 135 of file slghpatexpress\&.hh\&.
.SS "virtual \fBintb\fP ConstantValue::getValue (\fBParserWalker\fP & walker) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 133 of file slghpatexpress\&.hh\&.
.SS "virtual \fBintb\fP ConstantValue::maxValue (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 137 of file slghpatexpress\&.hh\&.
.SS "virtual \fBintb\fP ConstantValue::minValue (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 136 of file slghpatexpress\&.hh\&.
.SS "void ConstantValue::restoreXml (const \fBElement\fP * el, \fBTranslate\fP * trans)\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 696 of file slghpatexpress\&.cc\&.
.SS "void ConstantValue::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 690 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
