.TH "ConstraintConstCompare" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstraintConstCompare
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBUnifyConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstraintConstCompare\fP (int4 c1ind, int4 c2ind, \fBOpCode\fP oc)"
.br
.ti -1c
.RI "virtual \fBUnifyConstraint\fP * \fBclone\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBstep\fP (\fBUnifyState\fP &state)"
.br
.ti -1c
.RI "virtual void \fBcollectTypes\fP (vector< \fBUnifyDatatype\fP > &typelist) const"
.br
.ti -1c
.RI "virtual int4 \fBgetBaseIndex\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 474 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConstraintConstCompare::ConstraintConstCompare (int4 c1ind, int4 c2ind, \fBOpCode\fP oc)\fC [inline]\fP"

.PP
Definition at line 479 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBUnifyConstraint\fP* ConstraintConstCompare::clone (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.
.PP
Definition at line 481 of file unify\&.hh\&.
.SS "virtual void ConstraintConstCompare::collectTypes (vector< \fBUnifyDatatype\fP > & typelist) const\fC [virtual]\fP"

.PP
Reimplemented from \fBUnifyConstraint\fP\&.
.SS "virtual int4 ConstraintConstCompare::getBaseIndex (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUnifyConstraint\fP\&.
.PP
Definition at line 484 of file unify\&.hh\&.
.SS "virtual void ConstraintConstCompare::print (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.
.SS "virtual bool ConstraintConstCompare::step (\fBUnifyState\fP & state)\fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
