.TH "ConstantExpression" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBRHSConstant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantExpression\fP (\fBRHSConstant\fP *e1, \fBRHSConstant\fP *e2, \fBOpCode\fP oc)"
.br
.ti -1c
.RI "virtual \fB~ConstantExpression\fP (void)"
.br
.ti -1c
.RI "virtual \fBRHSConstant\fP * \fBclone\fP (void)"
.br
.ti -1c
.RI "virtual \fBuintb\fP \fBgetConstant\fP (\fBUnifyState\fP &state) const"
.br
.ti -1c
.RI "virtual void \fBwriteExpression\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConstantExpression::ConstantExpression (\fBRHSConstant\fP * e1, \fBRHSConstant\fP * e2, \fBOpCode\fP oc)\fC [inline]\fP"

.PP
Definition at line 144 of file unify\&.hh\&.
.SS "virtual ConstantExpression::~ConstantExpression (void)\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBRHSConstant\fP* ConstantExpression::clone (void)\fC [virtual]\fP"

.PP
Implements \fBRHSConstant\fP\&.
.SS "virtual \fBuintb\fP ConstantExpression::getConstant (\fBUnifyState\fP & state) const\fC [virtual]\fP"

.PP
Implements \fBRHSConstant\fP\&.
.SS "virtual void ConstantExpression::writeExpression (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [virtual]\fP"

.PP
Implements \fBRHSConstant\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
