.TH "ConstraintOtherInput" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstraintOtherInput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBUnifyConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstraintOtherInput\fP (int4 oind, int4 v_in, int4 v_out)"
.br
.ti -1c
.RI "virtual \fBUnifyConstraint\fP * \fBclone\fP (void) const"
.br
.ti -1c
.RI "virtual int4 \fBgetBaseIndex\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBstep\fP (\fBUnifyState\fP &state)"
.br
.ti -1c
.RI "virtual void \fBcollectTypes\fP (vector< \fBUnifyDatatype\fP > &typelist) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 460 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConstraintOtherInput::ConstraintOtherInput (int4 oind, int4 v_in, int4 v_out)\fC [inline]\fP"

.PP
Definition at line 465 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBUnifyConstraint\fP* ConstraintOtherInput::clone (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.
.PP
Definition at line 467 of file unify\&.hh\&.
.SS "virtual void ConstraintOtherInput::collectTypes (vector< \fBUnifyDatatype\fP > & typelist) const\fC [virtual]\fP"

.PP
Reimplemented from \fBUnifyConstraint\fP\&.
.SS "virtual int4 ConstraintOtherInput::getBaseIndex (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUnifyConstraint\fP\&.
.PP
Definition at line 468 of file unify\&.hh\&.
.SS "virtual void ConstraintOtherInput::print (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.
.SS "virtual bool ConstraintOtherInput::step (\fBUnifyState\fP & state)\fC [virtual]\fP"

.PP
Implements \fBUnifyConstraint\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
