.TH "ConstantConsumed" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantConsumed
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBRHSConstant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantConsumed\fP (int4 ind)"
.br
.ti -1c
.RI "virtual \fBRHSConstant\fP * \fBclone\fP (void)"
.br
.ti -1c
.RI "virtual \fBuintb\fP \fBgetConstant\fP (\fBUnifyState\fP &state) const"
.br
.ti -1c
.RI "virtual void \fBwriteExpression\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConstantConsumed::ConstantConsumed (int4 ind)\fC [inline]\fP"

.PP
Definition at line 98 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBRHSConstant\fP* ConstantConsumed::clone (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBRHSConstant\fP\&.
.PP
Definition at line 99 of file unify\&.hh\&.
.SS "virtual \fBuintb\fP ConstantConsumed::getConstant (\fBUnifyState\fP & state) const\fC [virtual]\fP"

.PP
Implements \fBRHSConstant\fP\&.
.SS "virtual void ConstantConsumed::writeExpression (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [virtual]\fP"

.PP
Implements \fBRHSConstant\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
