.TH "ConstraintOr" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstraintOr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBConstraintGroup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBUnifyConstraint\fP * \fBclone\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBinitialize\fP (\fBUnifyState\fP &state)"
.br
.ti -1c
.RI "virtual bool \fBstep\fP (\fBUnifyState\fP &state)"
.br
.ti -1c
.RI "virtual void \fBbuildTraverseState\fP (\fBUnifyState\fP &state)"
.br
.ti -1c
.RI "virtual int4 \fBgetBaseIndex\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 514 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ConstraintOr::buildTraverseState (\fBUnifyState\fP & state)\fC [virtual]\fP"

.PP
Reimplemented from \fBConstraintGroup\fP\&.
.SS "virtual \fBUnifyConstraint\fP* ConstraintOr::clone (void) const\fC [virtual]\fP"

.PP
Reimplemented from \fBConstraintGroup\fP\&.
.SS "virtual int4 ConstraintOr::getBaseIndex (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBConstraintGroup\fP\&.
.PP
Definition at line 520 of file unify\&.hh\&.
.SS "virtual void ConstraintOr::initialize (\fBUnifyState\fP & state)\fC [virtual]\fP"

.PP
Reimplemented from \fBConstraintGroup\fP\&.
.SS "virtual void ConstraintOr::print (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [virtual]\fP"

.PP
Reimplemented from \fBConstraintGroup\fP\&.
.SS "virtual bool ConstraintOr::step (\fBUnifyState\fP & state)\fC [virtual]\fP"

.PP
Reimplemented from \fBConstraintGroup\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
