.TH "ContextCommit" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextCommit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBContextChange\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContextCommit\fP (void)"
.br
.ti -1c
.RI "\fBContextCommit\fP (\fBTripleSymbol\fP *s, int4 sbit, int4 ebit, bool fl)"
.br
.ti -1c
.RI "virtual void \fBvalidate\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBSleighBase\fP *trans)"
.br
.ti -1c
.RI "virtual void \fBapply\fP (\fBParserWalkerChange\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBContextChange\fP * \fBclone\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 447 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContextCommit::ContextCommit (void)\fC [inline]\fP"

.PP
Definition at line 453 of file slghsymbol\&.hh\&.
.SS "ContextCommit::ContextCommit (\fBTripleSymbol\fP * s, int4 sbit, int4 ebit, bool fl)"

.PP
Definition at line 2482 of file slghsymbol\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void ContextCommit::apply (\fBParserWalkerChange\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBContextChange\fP\&.
.PP
Definition at line 2492 of file slghsymbol\&.cc\&.
.SS "\fBContextChange\fP * ContextCommit::clone (void) const\fC [virtual]\fP"

.PP
Implements \fBContextChange\fP\&.
.PP
Definition at line 2535 of file slghsymbol\&.cc\&.
.SS "void ContextCommit::restoreXml (const \fBElement\fP * el, \fBSleighBase\fP * trans)\fC [virtual]\fP"

.PP
Implements \fBContextChange\fP\&.
.PP
Definition at line 2509 of file slghsymbol\&.cc\&.
.SS "void ContextCommit::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Implements \fBContextChange\fP\&.
.PP
Definition at line 2498 of file slghsymbol\&.cc\&.
.SS "virtual void ContextCommit::validate (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContextChange\fP\&.
.PP
Definition at line 455 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
