.TH "ContextField" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextField
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContextField\fP (void)"
.br
.ti -1c
.RI "\fBContextField\fP (bool s, int4 sbit, int4 ebit)"
.br
.ti -1c
.RI "int4 \fBgetStartBit\fP (void) const"
.br
.ti -1c
.RI "int4 \fBgetEndBit\fP (void) const"
.br
.ti -1c
.RI "bool \fBgetSignBit\fP (void) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenMinPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenPattern\fP (\fBintb\fP val) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBminValue\fP (void) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBmaxValue\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBTranslate\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 108 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContextField::ContextField (void)\fC [inline]\fP"

.PP
Definition at line 114 of file slghpatexpress\&.hh\&.
.SS "ContextField::ContextField (bool s, int4 sbit, int4 ebit)"

.PP
Definition at line 614 of file slghpatexpress\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBTokenPattern\fP ContextField::genMinPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 120 of file slghpatexpress\&.hh\&.
.SS "\fBTokenPattern\fP ContextField::genPattern (\fBintb\fP val) const\fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 637 of file slghpatexpress\&.cc\&.
.SS "int4 ContextField::getEndBit (void) const\fC [inline]\fP"

.PP
Definition at line 117 of file slghpatexpress\&.hh\&.
.SS "bool ContextField::getSignBit (void) const\fC [inline]\fP"

.PP
Definition at line 118 of file slghpatexpress\&.hh\&.
.SS "int4 ContextField::getStartBit (void) const\fC [inline]\fP"

.PP
Definition at line 116 of file slghpatexpress\&.hh\&.
.SS "\fBintb\fP ContextField::getValue (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 625 of file slghpatexpress\&.cc\&.
.SS "virtual \fBintb\fP ContextField::maxValue (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 123 of file slghpatexpress\&.hh\&.
.SS "virtual \fBintb\fP ContextField::minValue (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 122 of file slghpatexpress\&.hh\&.
.SS "void ContextField::restoreXml (const \fBElement\fP * el, \fBTranslate\fP * trans)\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 659 of file slghpatexpress\&.cc\&.
.SS "void ContextField::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 643 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
