.TH "ContextSet" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextSet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <context\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTripleSymbol\fP * \fBsym\fP"
.br
.ti -1c
.RI "\fBConstructState\fP * \fBpoint\fP"
.br
.ti -1c
.RI "int4 \fBnum\fP"
.br
.ti -1c
.RI "uintm \fBmask\fP"
.br
.ti -1c
.RI "uintm \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBflow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file context\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ContextSet::flow"

.PP
Definition at line 62 of file context\&.hh\&.
.SS "uintm ContextSet::mask"

.PP
Definition at line 60 of file context\&.hh\&.
.SS "int4 ContextSet::num"

.PP
Definition at line 59 of file context\&.hh\&.
.SS "\fBConstructState\fP* ContextSet::point"

.PP
Definition at line 58 of file context\&.hh\&.
.SS "\fBTripleSymbol\fP* ContextSet::sym"

.PP
Definition at line 57 of file context\&.hh\&.
.SS "uintm ContextSet::value"

.PP
Definition at line 61 of file context\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
