.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'coreaction\&.hh'\fP
.br
\fC#include 'condexe\&.hh'\fP
.br
\fC#include 'double\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStackEqn\fP"
.br
.RI "A stack equation\&. "
.ti -1c
.RI "class \fBStackSolver\fP"
.br
.RI "A class that solves for stack-pointer changes across unknown sub-functions\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbuild_defaultactions\fP (\fBActionDatabase\fP &allacts)"
.br
.RI "Build the default actions\&. "
.ti -1c
.RI "void \fBuniversal_action\fP (\fBArchitecture\fP *conf)"
.br
.RI "The generic decompilation action\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void build_defaultactions (\fBActionDatabase\fP & allacts)"

.PP
Build the default actions\&. Build the default \fIroot\fP Actions: decompile, jumptable, normalize, paramid, register, firstpass 
.PP
\fBParameters:\fP
.RS 4
\fIallacts\fP is the database that will hold the \fIroot\fP Actions 
.RE
.PP

.PP
Definition at line 4429 of file coreaction\&.cc\&.
.SS "void universal_action (\fBArchitecture\fP * conf)"

.PP
The generic decompilation action\&. Construct the \fBuniversal\fP \fBAction\fP that contains all possible components 
.PP
\fBParameters:\fP
.RS 4
\fIconf\fP is the \fBArchitecture\fP that will use the \fBAction\fP 
.RE
.PP

.PP
Definition at line 4469 of file coreaction\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
