.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/cpool_ghidra.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/cpool_ghidra.hh \- Utility for implementing a \fIconstant\fP \fIpool\fP backed by a Ghidra client\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ghidra_arch\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstantPoolGhidra\fP"
.br
.RI "An implementation of \fBConstantPool\fP using a Ghidra client as the backing storage\&. "
.in -1c
.SH "Detailed Description"
.PP 
Utility for implementing a \fIconstant\fP \fIpool\fP backed by a Ghidra client\&. 


.PP
Definition in file \fBcpool_ghidra\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
