.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/database_ghidra.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/database_ghidra.hh \- Facilities for retrieving symbol information from a Ghidra client\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'database\&.hh'\fP
.br
\fC#include 'ghidra_arch\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScopeGhidra\fP"
.br
.RI "An implementation of the \fBScope\fP interface by querying a Ghidra client for \fBSymbol\fP information\&. "
.ti -1c
.RI "class \fBScopeGhidraNamespace\fP"
.br
.RI "A global \fInamespace\fP \fBScope\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Facilities for retrieving symbol information from a Ghidra client\&. 


.PP
Definition in file \fBdatabase_ghidra\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
