.TH "DatatypeCompare" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatatypeCompare \- Compare two \fBDatatype\fP pointers for equivalence of their description\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBDatatype\fP *a, const \fBDatatype\fP *b) const"
.br
.RI "Comparison operator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Compare two \fBDatatype\fP pointers for equivalence of their description\&. 
.PP
Definition at line 131 of file type\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool DatatypeCompare::operator() (const \fBDatatype\fP * a, const \fBDatatype\fP * b) const\fC [inline]\fP"

.PP
Comparison operator\&. 
.PP
Definition at line 133 of file type\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
