.TH "DataUnavailError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataUnavailError \- Exception indicating data was not available\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loadimage\&.hh>\fP
.PP
Inherits \fBLowlevelError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataUnavailError\fP (const string &s)"
.br
.RI "Instantiate with an explanatory string\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Exception indicating data was not available\&. 

This exception is thrown when a request for load image data cannot be met, usually because the requested address range is not in the image\&. 
.PP
Definition at line 29 of file loadimage\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataUnavailError::DataUnavailError (const string & s)\fC [inline]\fP"

.PP
Instantiate with an explanatory string\&. 
.PP
Definition at line 30 of file loadimage\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
