.TH "DecisionNode" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecisionNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecisionNode\fP (void)"
.br
.ti -1c
.RI "\fBDecisionNode\fP (\fBDecisionNode\fP *p)"
.br
.ti -1c
.RI "\fB~DecisionNode\fP (void)"
.br
.ti -1c
.RI "\fBConstructor\fP * \fBresolve\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "void \fBaddConstructorPair\fP (const \fBDisjointPattern\fP *pat, \fBConstructor\fP *ct)"
.br
.ti -1c
.RI "void \fBsplit\fP (\fBDecisionProperties\fP &props)"
.br
.ti -1c
.RI "void \fBorderPatterns\fP (\fBDecisionProperties\fP &props)"
.br
.ti -1c
.RI "void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "void \fBrestoreXml\fP (const \fBElement\fP *el, \fBDecisionNode\fP *par, \fBSubtableSymbol\fP *sub)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 533 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DecisionNode::DecisionNode (void)\fC [inline]\fP"

.PP
Definition at line 546 of file slghsymbol\&.hh\&.
.SS "DecisionNode::DecisionNode (\fBDecisionNode\fP * p)"

.PP
Definition at line 2002 of file slghsymbol\&.cc\&.
.SS "DecisionNode::~DecisionNode (void)"

.PP
Definition at line 2012 of file slghsymbol\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void DecisionNode::addConstructorPair (const \fBDisjointPattern\fP * pat, \fBConstructor\fP * ct)"

.PP
Definition at line 2023 of file slghsymbol\&.cc\&.
.SS "void DecisionNode::orderPatterns (\fBDecisionProperties\fP & props)"

.PP
Definition at line 2211 of file slghsymbol\&.cc\&.
.SS "\fBConstructor\fP * DecisionNode::resolve (\fBParserWalker\fP & walker) const"

.PP
Definition at line 2296 of file slghsymbol\&.cc\&.
.SS "void DecisionNode::restoreXml (const \fBElement\fP * el, \fBDecisionNode\fP * par, \fBSubtableSymbol\fP * sub)"

.PP
Definition at line 2341 of file slghsymbol\&.cc\&.
.SS "void DecisionNode::saveXml (ostream & s) const"

.PP
Definition at line 2318 of file slghsymbol\&.cc\&.
.SS "void DecisionNode::split (\fBDecisionProperties\fP & props)"

.PP
Definition at line 2173 of file slghsymbol\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
