.TH "DecisionProperties" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecisionProperties
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBidenticalPattern\fP (\fBConstructor\fP *a, \fBConstructor\fP *b)"
.br
.ti -1c
.RI "void \fBconflictingPattern\fP (\fBConstructor\fP *a, \fBConstructor\fP *b)"
.br
.ti -1c
.RI "const vector< string > & \fBgetIdentErrors\fP (void) const"
.br
.ti -1c
.RI "const vector< string > & \fBgetConflictErrors\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 523 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void DecisionProperties::conflictingPattern (\fBConstructor\fP * a, \fBConstructor\fP * b)"

.PP
Definition at line 1986 of file slghsymbol\&.cc\&.
.SS "const vector<string>& DecisionProperties::getConflictErrors (void) const\fC [inline]\fP"

.PP
Definition at line 530 of file slghsymbol\&.hh\&.
.SS "const vector<string>& DecisionProperties::getIdentErrors (void) const\fC [inline]\fP"

.PP
Definition at line 529 of file slghsymbol\&.hh\&.
.SS "void DecisionProperties::identicalPattern (\fBConstructor\fP * a, \fBConstructor\fP * b)"

.PP
Definition at line 1970 of file slghsymbol\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
