.TH "decompiler.DecompilerInitializer" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decompiler.DecompilerInitializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModuleInitializer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file DecompilerInitializer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String decompiler\&.DecompilerInitializer\&.getName (void)\fC [inline]\fP"

.PP
Definition at line 28 of file DecompilerInitializer\&.java\&.
.SS "void decompiler\&.DecompilerInitializer\&.run ()\fC [inline]\fP"

.PP
Definition at line 23 of file DecompilerInitializer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
