.TH "deprecated" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBAddress::toPhysical\fP (void)\fP" 1c
Convert this to the most basic physical address\&. This routine is only present for backward compatibility with SLED  
.IP "\fBMember \fBTranslate::addRegister\fP (const string &nm, \fBAddrSpace\fP *base, uintb offset, int4 size)=0\fP" 1c
All registers used to be formally added to the processor model through this method\&. 
.PP

