.TH "DisassemblyCache" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisassemblyCache
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sleigh\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisassemblyCache\fP (\fBContextCache\fP *ccache, \fBAddrSpace\fP *cspace, int4 cachesize, int4 windowsize)"
.br
.ti -1c
.RI "\fB~DisassemblyCache\fP (void)"
.br
.ti -1c
.RI "\fBParserContext\fP * \fBgetParserContext\fP (const \fBAddress\fP &addr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file sleigh\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DisassemblyCache::DisassemblyCache (\fBContextCache\fP * ccache, \fBAddrSpace\fP * cspace, int4 cachesize, int4 windowsize)"

.PP
Definition at line 385 of file sleigh\&.cc\&.
.SS "DisassemblyCache::~DisassemblyCache (void)\fC [inline]\fP"

.PP
Definition at line 81 of file sleigh\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBParserContext\fP * DisassemblyCache::getParserContext (const \fBAddress\fP & addr)"

.PP
Definition at line 393 of file sleigh\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
