.TH "DisassemblyResult" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisassemblyResult
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codedata\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsuccess\fP"
.br
.ti -1c
.RI "int4 \fBlength\fP"
.br
.ti -1c
.RI "uint4 \fBflags\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBjumpaddress\fP"
.br
.ti -1c
.RI "\fBuintb\fP \fBtargethit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file codedata\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "uint4 DisassemblyResult::flags"

.PP
Definition at line 53 of file codedata\&.hh\&.
.SS "\fBAddress\fP DisassemblyResult::jumpaddress"

.PP
Definition at line 54 of file codedata\&.hh\&.
.SS "int4 DisassemblyResult::length"

.PP
Definition at line 52 of file codedata\&.hh\&.
.SS "bool DisassemblyResult::success"

.PP
Definition at line 51 of file codedata\&.hh\&.
.SS "\fBuintb\fP DisassemblyResult::targethit"

.PP
Definition at line 55 of file codedata\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
