.TH "DivExpression" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DivExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBBinaryExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDivExpression\fP (void)"
.br
.ti -1c
.RI "\fBDivExpression\fP (\fBPatternExpression\fP *l, \fBPatternExpression\fP *r)"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetSubValue\fP (const vector< \fBintb\fP > &replace, int4 &listpos) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 297 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DivExpression::DivExpression (void)\fC [inline]\fP"

.PP
Definition at line 299 of file slghpatexpress\&.hh\&.
.SS "DivExpression::DivExpression (\fBPatternExpression\fP * l, \fBPatternExpression\fP * r)\fC [inline]\fP"

.PP
Definition at line 300 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBintb\fP DivExpression::getSubValue (const vector< \fBintb\fP > & replace, int4 & listpos) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 1070 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP DivExpression::getValue (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 1062 of file slghpatexpress\&.cc\&.
.SS "void DivExpression::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBBinaryExpression\fP\&.
.PP
Definition at line 1078 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
