.TH "DocumentStorage" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DocumentStorage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xml\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~DocumentStorage\fP (void)"
.br
.ti -1c
.RI "\fBDocument\fP * \fBparseDocument\fP (istream &s)"
.br
.ti -1c
.RI "\fBDocument\fP * \fBopenDocument\fP (const string &filename)"
.br
.ti -1c
.RI "void \fBregisterTag\fP (const \fBElement\fP *el)"
.br
.ti -1c
.RI "const \fBElement\fP * \fBgetTag\fP (const string &nm) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file xml\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DocumentStorage::~DocumentStorage (void)"

.SH "Member Function Documentation"
.PP 
.SS "const \fBElement\fP* DocumentStorage::getTag (const string & nm) const"

.SS "\fBDocument\fP* DocumentStorage::openDocument (const string & filename)"

.SS "\fBDocument\fP* DocumentStorage::parseDocument (istream & s)"

.SS "void DocumentStorage::registerTag (const \fBElement\fP * el)"


.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
