.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/dynamic.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/dynamic.hh \- Utilities for making references to \fBdynamic\fP variables: defined as locations and constants that can only be identified by their context within the data-flow graph\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'varnode\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToOpEdge\fP"
.br
.RI "An edge between a \fBVarnode\fP and a \fBPcodeOp\fP\&. "
.ti -1c
.RI "class \fBDynamicHash\fP"
.br
.RI "A hash utility to uniquely identify a temporary \fBVarnode\fP in data-flow\&. "
.in -1c
.SH "Detailed Description"
.PP 
Utilities for making references to \fBdynamic\fP variables: defined as locations and constants that can only be identified by their context within the data-flow graph\&. 


.PP
Definition in file \fBdynamic\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
