.TH "Element" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Element
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xml\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP (\fBElement\fP *par)"
.br
.ti -1c
.RI "\fB~Element\fP (void)"
.br
.ti -1c
.RI "void \fBsetName\fP (const string &nm)"
.br
.ti -1c
.RI "void \fBaddContent\fP (const char *str, int4 start, int4 length)"
.br
.ti -1c
.RI "void \fBaddChild\fP (\fBElement\fP *child)"
.br
.ti -1c
.RI "void \fBaddAttribute\fP (const string &nm, const string &vl)"
.br
.ti -1c
.RI "\fBElement\fP * \fBgetParent\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetName\fP (void) const"
.br
.ti -1c
.RI "const \fBList\fP & \fBgetChildren\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetContent\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetAttributeValue\fP (const string &nm) const"
.br
.ti -1c
.RI "int4 \fBgetNumAttributes\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetAttributeName\fP (int4 i) const"
.br
.ti -1c
.RI "const string & \fBgetAttributeValue\fP (int4 i) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBElement\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fBList\fP \fBchildren\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file xml\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Element::Element (\fBElement\fP * par)\fC [inline]\fP"

.PP
Definition at line 97 of file xml\&.hh\&.
.SS "Element::~Element (void)"

.SH "Member Function Documentation"
.PP 
.SS "void Element::addAttribute (const string & nm, const string & vl)\fC [inline]\fP"

.PP
Definition at line 104 of file xml\&.hh\&.
.SS "void Element::addChild (\fBElement\fP * child)\fC [inline]\fP"

.PP
Definition at line 103 of file xml\&.hh\&.
.SS "void Element::addContent (const char * str, int4 start, int4 length)\fC [inline]\fP"

.PP
Definition at line 100 of file xml\&.hh\&.
.SS "const string& Element::getAttributeName (int4 i) const\fC [inline]\fP"

.PP
Definition at line 112 of file xml\&.hh\&.
.SS "const string& Element::getAttributeValue (const string & nm) const"

.SS "const string& Element::getAttributeValue (int4 i) const\fC [inline]\fP"

.PP
Definition at line 113 of file xml\&.hh\&.
.SS "const \fBList\fP& Element::getChildren (void) const\fC [inline]\fP"

.PP
Definition at line 108 of file xml\&.hh\&.
.SS "const string& Element::getContent (void) const\fC [inline]\fP"

.PP
Definition at line 109 of file xml\&.hh\&.
.SS "const string& Element::getName (void) const\fC [inline]\fP"

.PP
Definition at line 107 of file xml\&.hh\&.
.SS "int4 Element::getNumAttributes (void) const\fC [inline]\fP"

.PP
Definition at line 111 of file xml\&.hh\&.
.SS "\fBElement\fP* Element::getParent (void) const\fC [inline]\fP"

.PP
Definition at line 106 of file xml\&.hh\&.
.SS "void Element::setName (const string & nm)\fC [inline]\fP"

.PP
Definition at line 99 of file xml\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBList\fP Element::children\fC [protected]\fP"

.PP
Definition at line 95 of file xml\&.hh\&.
.SS "\fBElement\fP* Element::parent\fC [protected]\fP"

.PP
Definition at line 94 of file xml\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
