.TH "Equal3Form" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Equal3Form
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <double\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBverify\fP (\fBVarnode\fP *h, \fBVarnode\fP *l, \fBPcodeOp\fP *aop)"
.br
.ti -1c
.RI "bool \fBapplyRule\fP (\fBSplitVarnode\fP &i, \fBPcodeOp\fP *op, bool workishi, \fBFuncdata\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 163 of file double\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Equal3Form::applyRule (\fBSplitVarnode\fP & i, \fBPcodeOp\fP * op, bool workishi, \fBFuncdata\fP & data)"

.PP
Definition at line 1754 of file double\&.cc\&.
.SS "bool Equal3Form::verify (\fBVarnode\fP * h, \fBVarnode\fP * l, \fBPcodeOp\fP * aop)"

.PP
Definition at line 1729 of file double\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
