.TH "EquationAnd" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EquationAnd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternEquation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEquationAnd\fP (\fBPatternEquation\fP *l, \fBPatternEquation\fP *r)"
.br
.ti -1c
.RI "virtual void \fBgenPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.ti -1c
.RI "virtual bool \fBresolveOperandLeft\fP (\fBOperandResolve\fP &state) const"
.br
.ti -1c
.RI "virtual void \fBoperandOrder\fP (\fBConstructor\fP *ct, vector< \fBOperandSymbol\fP * > &order) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~EquationAnd\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 416 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EquationAnd::~EquationAnd (void)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1444 of file slghpatexpress\&.cc\&.
.SS "EquationAnd::EquationAnd (\fBPatternEquation\fP * l, \fBPatternEquation\fP * r)"

.PP
Definition at line 1437 of file slghpatexpress\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void EquationAnd::genPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [virtual]\fP"

.PP
Implements \fBPatternEquation\fP\&.
.PP
Definition at line 1451 of file slghpatexpress\&.cc\&.
.SS "void EquationAnd::operandOrder (\fBConstructor\fP * ct, vector< \fBOperandSymbol\fP * > & order) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPatternEquation\fP\&.
.PP
Definition at line 1479 of file slghpatexpress\&.cc\&.
.SS "bool EquationAnd::resolveOperandLeft (\fBOperandResolve\fP & state) const\fC [virtual]\fP"

.PP
Implements \fBPatternEquation\fP\&.
.PP
Definition at line 1459 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
