.TH "ExecutablePcodeSleigh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExecutablePcodeSleigh
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inject_sleigh\&.hh>\fP
.PP
Inherits \fBExecutablePcode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExecutablePcodeSleigh\fP (\fBArchitecture\fP *g, const string &src, const string &nm)"
.br
.ti -1c
.RI "virtual \fB~ExecutablePcodeSleigh\fP (void)"
.br
.ti -1c
.RI "virtual void \fBinject\fP (\fBInjectContext\fP &context, \fBPcodeEmit\fP &emit) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el)"
.br
.ti -1c
.RI "virtual void \fBprintTemplate\fP (ostream &s) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBparsestring\fP"
.br
.ti -1c
.RI "\fBConstructTpl\fP * \fBtpl\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPcodeInjectLibrarySleigh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file inject_sleigh\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExecutablePcodeSleigh::ExecutablePcodeSleigh (\fBArchitecture\fP * g, const string & src, const string & nm)"

.PP
Definition at line 179 of file inject_sleigh\&.cc\&.
.SS "ExecutablePcodeSleigh::~ExecutablePcodeSleigh (void)\fC [virtual]\fP"

.PP
Definition at line 185 of file inject_sleigh\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void ExecutablePcodeSleigh::inject (\fBInjectContext\fP & context, \fBPcodeEmit\fP & emit) const\fC [virtual]\fP"

.PP
Definition at line 192 of file inject_sleigh\&.cc\&.
.SS "void ExecutablePcodeSleigh::printTemplate (ostream & s) const\fC [virtual]\fP"

.PP
Definition at line 232 of file inject_sleigh\&.cc\&.
.SS "void ExecutablePcodeSleigh::restoreXml (const \fBElement\fP * el)\fC [virtual]\fP"

.PP
Definition at line 214 of file inject_sleigh\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBPcodeInjectLibrarySleigh\fP\fC [friend]\fP"

.PP
Definition at line 65 of file inject_sleigh\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "string ExecutablePcodeSleigh::parsestring\fC [protected]\fP"

.PP
Definition at line 67 of file inject_sleigh\&.hh\&.
.SS "\fBConstructTpl\fP* ExecutablePcodeSleigh::tpl\fC [protected]\fP"

.PP
Definition at line 68 of file inject_sleigh\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
