.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/main/java Directory Reference" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/main/java Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdecompiler\fP"
.br
.ti -1c
.RI "directory \fBghidra\fP"
.br
.in -1c
