.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp Directory Reference" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaction\&.cc\fP"
.br
.ti -1c
.RI "file \fBaction\&.hh\fP"
.br
.RI "\fBAction\fP, \fBRule\fP, and other associates classes supporting transformations on function data-flow\&. "
.ti -1c
.RI "file \fBaddress\&.cc\fP"
.br
.ti -1c
.RI "file \fBaddress\&.hh\fP"
.br
.RI "Classes for specifying addresses and other low-level constants\&. "
.ti -1c
.RI "file \fBarchitecture\&.cc\fP"
.br
.ti -1c
.RI "file \fBarchitecture\&.hh\fP"
.br
.RI "\fBArchitecture\fP and associated classes that help manage a single processor architecture and load image\&. "
.ti -1c
.RI "file \fBbfd_arch\&.cc\fP"
.br
.ti -1c
.RI "file \fBbfd_arch\&.hh\fP"
.br
.RI "Specific implementation of \fBArchitecture\fP using GNU BFD libraries\&. "
.ti -1c
.RI "file \fBblock\&.cc\fP"
.br
.ti -1c
.RI "file \fBblock\&.hh\fP"
.br
.RI "Classes related to \fIbasic\fP \fIblocks\fP and control-flow structuring\&. "
.ti -1c
.RI "file \fBblockaction\&.cc\fP"
.br
.ti -1c
.RI "file \fBblockaction\&.hh\fP"
.br
.RI "Actions and classes associated with transforming and structuring the control-flow graph\&. "
.ti -1c
.RI "file \fBcallgraph\&.cc\fP"
.br
.ti -1c
.RI "file \fBcallgraph\&.hh\fP"
.br
.ti -1c
.RI "file \fBcapability\&.cc\fP"
.br
.ti -1c
.RI "file \fBcapability\&.hh\fP"
.br
.RI "Infrastructure for discovering code extensions to the decompiler\&. "
.ti -1c
.RI "file \fBcast\&.cc\fP"
.br
.ti -1c
.RI "file \fBcast\&.hh\fP"
.br
.RI "API and specific strategies for applying type casts\&. "
.ti -1c
.RI "file \fBcodedata\&.cc\fP"
.br
.ti -1c
.RI "file \fBcodedata\&.hh\fP"
.br
.ti -1c
.RI "file \fBcomment\&.cc\fP"
.br
.ti -1c
.RI "file \fBcomment\&.hh\fP"
.br
.RI "A database interface for high-level language comments\&. "
.ti -1c
.RI "file \fBcomment_ghidra\&.cc\fP"
.br
.ti -1c
.RI "file \fBcomment_ghidra\&.hh\fP"
.br
.RI "Obtain comments by talking to a Ghidra client\&. "
.ti -1c
.RI "file \fBcondexe\&.cc\fP"
.br
.ti -1c
.RI "file \fBcondexe\&.hh\fP"
.br
.RI "Classes for simplifying control-flow with shared conditional expressions\&. "
.ti -1c
.RI "file \fBconsolemain\&.cc\fP"
.br
.ti -1c
.RI "file \fBcontext\&.cc\fP"
.br
.ti -1c
.RI "file \fBcontext\&.hh\fP"
.br
.ti -1c
.RI "file \fBcoreaction\&.cc\fP"
.br
.ti -1c
.RI "file \fBcoreaction\&.hh\fP"
.br
.RI "Core decompilation actions which are indepedent of any particular architecture\&. "
.ti -1c
.RI "file \fBcover\&.cc\fP"
.br
.ti -1c
.RI "file \fBcover\&.hh\fP"
.br
.RI "Classes describing the topological scope of variables within a function\&. "
.ti -1c
.RI "file \fBcpool\&.cc\fP"
.br
.ti -1c
.RI "file \fBcpool\&.hh\fP"
.br
.RI "Definitions to support a constant pool for \fIdeferred\fP compilation languages (i\&.e\&. java byte-code) "
.ti -1c
.RI "file \fBcpool_ghidra\&.cc\fP"
.br
.ti -1c
.RI "file \fBcpool_ghidra\&.hh\fP"
.br
.RI "Utility for implementing a \fIconstant\fP \fIpool\fP backed by a Ghidra client\&. "
.ti -1c
.RI "file \fBcrc32\&.cc\fP"
.br
.ti -1c
.RI "file \fBcrc32\&.hh\fP"
.br
.RI "Table and function for computing a CRC32\&. "
.ti -1c
.RI "file \fBdatabase\&.cc\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.hh\fP"
.br
.RI "\fBSymbol\fP and \fBScope\fP objects for the decompiler\&. "
.ti -1c
.RI "file \fBdatabase_ghidra\&.cc\fP"
.br
.ti -1c
.RI "file \fBdatabase_ghidra\&.hh\fP"
.br
.RI "Facilities for retrieving symbol information from a Ghidra client\&. "
.ti -1c
.RI "file \fBdoccore\&.hh\fP"
.br
.ti -1c
.RI "file \fBdocmain\&.hh\fP"
.br
.ti -1c
.RI "file \fBdouble\&.cc\fP"
.br
.ti -1c
.RI "file \fBdouble\&.hh\fP"
.br
.ti -1c
.RI "file \fBdynamic\&.cc\fP"
.br
.ti -1c
.RI "file \fBdynamic\&.hh\fP"
.br
.RI "Utilities for making references to \fBdynamic\fP variables: defined as locations and constants that can only be identified by their context within the data-flow graph\&. "
.ti -1c
.RI "file \fBemulate\&.cc\fP"
.br
.ti -1c
.RI "file \fBemulate\&.hh\fP"
.br
.RI "Classes for emulating p-code\&. "
.ti -1c
.RI "file \fBemulateutil\&.cc\fP"
.br
.ti -1c
.RI "file \fBemulateutil\&.hh\fP"
.br
.RI "(Lightweight) emulation interface for executing \fBPcodeOp\fP objects within a syntax tree or for executing snippets defined with \fBPcodeOpRaw\fP objects "
.ti -1c
.RI "file \fBerror\&.hh\fP"
.br
.RI "Base class for error handling facilities\&. "
.ti -1c
.RI "file \fBfilemanage\&.cc\fP"
.br
.ti -1c
.RI "file \fBfilemanage\&.hh\fP"
.br
.ti -1c
.RI "file \fBfloat\&.cc\fP"
.br
.ti -1c
.RI "file \fBfloat\&.hh\fP"
.br
.RI "Support for decoding different floating-point formats\&. "
.ti -1c
.RI "file \fBflow\&.cc\fP"
.br
.ti -1c
.RI "file \fBflow\&.hh\fP"
.br
.RI "Utilities for following control-flow in p-code generated from machine instructions\&. "
.ti -1c
.RI "file \fBfspec\&.cc\fP"
.br
.ti -1c
.RI "file \fBfspec\&.hh\fP"
.br
.RI "Definitions for specifying functions prototypes\&. "
.ti -1c
.RI "file \fBfuncdata\&.cc\fP"
.br
.ti -1c
.RI "file \fBfuncdata\&.hh\fP"
.br
.RI "Utilities for processing data structures associated with a single function\&. "
.ti -1c
.RI "file \fBfuncdata_block\&.cc\fP"
.br
.ti -1c
.RI "file \fBfuncdata_op\&.cc\fP"
.br
.ti -1c
.RI "file \fBfuncdata_varnode\&.cc\fP"
.br
.ti -1c
.RI "file \fBghidra_arch\&.cc\fP"
.br
.ti -1c
.RI "file \fBghidra_arch\&.hh\fP"
.br
.RI "Ghidra specific architecture information and connection to a Ghidra client\&. "
.ti -1c
.RI "file \fBghidra_context\&.cc\fP"
.br
.ti -1c
.RI "file \fBghidra_context\&.hh\fP"
.br
.RI "Obtaining context information from a Ghidra client\&. "
.ti -1c
.RI "file \fBghidra_process\&.cc\fP"
.br
.ti -1c
.RI "file \fBghidra_process\&.hh\fP"
.br
.RI "The formal commands that can be issued to the decompiler by the Ghidra client\&. "
.ti -1c
.RI "file \fBghidra_translate\&.cc\fP"
.br
.ti -1c
.RI "file \fBghidra_translate\&.hh\fP"
.br
.RI "Class for fetching p-code from a Ghidra client\&. "
.ti -1c
.RI "file \fBglobalcontext\&.cc\fP"
.br
.ti -1c
.RI "file \fBglobalcontext\&.hh\fP"
.br
.RI "Utilities for getting address-based context to the disassembler and decompiler\&. "
.ti -1c
.RI "file \fBgrammar\&.hh\fP"
.br
.ti -1c
.RI "file \fBgraph\&.cc\fP"
.br
.ti -1c
.RI "file \fBgraph\&.hh\fP"
.br
.ti -1c
.RI "file \fBheritage\&.cc\fP"
.br
.ti -1c
.RI "file \fBheritage\&.hh\fP"
.br
.RI "Utilities for building Static Single Assignment (SSA) form\&. "
.ti -1c
.RI "file \fBifacedecomp\&.cc\fP"
.br
.ti -1c
.RI "file \fBifacedecomp\&.hh\fP"
.br
.ti -1c
.RI "file \fBifaceterm\&.cc\fP"
.br
.ti -1c
.RI "file \fBifaceterm\&.hh\fP"
.br
.ti -1c
.RI "file \fBinject_ghidra\&.cc\fP"
.br
.ti -1c
.RI "file \fBinject_ghidra\&.hh\fP"
.br
.RI "P-code injection classes using a Ghidra client as the back-end for generating p-code\&. "
.ti -1c
.RI "file \fBinject_sleigh\&.cc\fP"
.br
.ti -1c
.RI "file \fBinject_sleigh\&.hh\fP"
.br
.ti -1c
.RI "file \fBinterface\&.cc\fP"
.br
.ti -1c
.RI "file \fBinterface\&.hh\fP"
.br
.ti -1c
.RI "file \fBjumptable\&.cc\fP"
.br
.ti -1c
.RI "file \fBjumptable\&.hh\fP"
.br
.ti -1c
.RI "file \fBlibdecomp\&.cc\fP"
.br
.ti -1c
.RI "file \fBlibdecomp\&.hh\fP"
.br
.ti -1c
.RI "file \fBloadimage\&.cc\fP"
.br
.ti -1c
.RI "file \fBloadimage\&.hh\fP"
.br
.RI "Classes and API for accessing a binary load image\&. "
.ti -1c
.RI "file \fBloadimage_bfd\&.cc\fP"
.br
.ti -1c
.RI "file \fBloadimage_bfd\&.hh\fP"
.br
.ti -1c
.RI "file \fBloadimage_ghidra\&.cc\fP"
.br
.ti -1c
.RI "file \fBloadimage_ghidra\&.hh\fP"
.br
.RI "Use the Ghidra client as a load image\&. "
.ti -1c
.RI "file \fBloadimage_xml\&.cc\fP"
.br
.ti -1c
.RI "file \fBloadimage_xml\&.hh\fP"
.br
.RI "Support for programs stored using an XML schema\&. "
.ti -1c
.RI "file \fBmemstate\&.cc\fP"
.br
.ti -1c
.RI "file \fBmemstate\&.hh\fP"
.br
.RI "Classes for keeping track of memory state during emulation\&. "
.ti -1c
.RI "file \fBmerge\&.cc\fP"
.br
.ti -1c
.RI "file \fBmerge\&.hh\fP"
.br
.RI "Utilities for merging low-level Varnodes into high-level variables\&. "
.ti -1c
.RI "file \fBop\&.cc\fP"
.br
.ti -1c
.RI "file \fBop\&.hh\fP"
.br
.RI "The \fBPcodeOp\fP and \fBPcodeOpBank\fP classes\&. "
.ti -1c
.RI "file \fBopbehavior\&.cc\fP"
.br
.ti -1c
.RI "file \fBopbehavior\&.hh\fP"
.br
.RI "Classes for describing the behavior of individual p-code operations\&. "
.ti -1c
.RI "file \fBopcodes\&.cc\fP"
.br
.ti -1c
.RI "file \fBopcodes\&.hh\fP"
.br
.RI "All the individual p-code operations\&. "
.ti -1c
.RI "file \fBoptions\&.cc\fP"
.br
.ti -1c
.RI "file \fBoptions\&.hh\fP"
.br
.RI "Classes for processing architecture configuration options\&. "
.ti -1c
.RI "file \fBoverride\&.cc\fP"
.br
.ti -1c
.RI "file \fBoverride\&.hh\fP"
.br
.RI "A system for sending override commands to the decompiler\&. "
.ti -1c
.RI "file \fBparamid\&.cc\fP"
.br
.ti -1c
.RI "file \fBparamid\&.hh\fP"
.br
.ti -1c
.RI "file \fBpartmap\&.hh\fP"
.br
.RI "The partmap<> template mapping a linear space to value objects\&. "
.ti -1c
.RI "file \fBpcodecompile\&.cc\fP"
.br
.ti -1c
.RI "file \fBpcodecompile\&.hh\fP"
.br
.ti -1c
.RI "file \fBpcodeinject\&.cc\fP"
.br
.ti -1c
.RI "file \fBpcodeinject\&.hh\fP"
.br
.RI "Classes for managing \fBp-code\fP \fBinjection\fP\&. "
.ti -1c
.RI "file \fBpcodeparse\&.hh\fP"
.br
.ti -1c
.RI "file \fBpcoderaw\&.cc\fP"
.br
.ti -1c
.RI "file \fBpcoderaw\&.hh\fP"
.br
.RI "Raw descriptions of varnodes and p-code ops\&. "
.ti -1c
.RI "file \fBprefersplit\&.cc\fP"
.br
.ti -1c
.RI "file \fBprefersplit\&.hh\fP"
.br
.ti -1c
.RI "file \fBprettyprint\&.cc\fP"
.br
.ti -1c
.RI "file \fBprettyprint\&.hh\fP"
.br
.RI "Routines for emitting high-level (C) language syntax in a well formatted way\&. "
.ti -1c
.RI "file \fBprintc\&.cc\fP"
.br
.ti -1c
.RI "file \fBprintc\&.hh\fP"
.br
.RI "Classes to support the c-language back-end of the decompiler\&. "
.ti -1c
.RI "file \fBprintjava\&.cc\fP"
.br
.ti -1c
.RI "file \fBprintjava\&.hh\fP"
.br
.RI "Classes supporting the java-language back-end to the decompiler\&. "
.ti -1c
.RI "file \fBprintlanguage\&.cc\fP"
.br
.ti -1c
.RI "file \fBprintlanguage\&.hh\fP"
.br
.RI "Classes for printing tokens in a high-level language\&. "
.ti -1c
.RI "file \fBrangemap\&.hh\fP"
.br
.ti -1c
.RI "file \fBrangeutil\&.cc\fP"
.br
.ti -1c
.RI "file \fBrangeutil\&.hh\fP"
.br
.RI "Documentation for the \fBCircleRange\fP class\&. "
.ti -1c
.RI "file \fBraw_arch\&.cc\fP"
.br
.ti -1c
.RI "file \fBraw_arch\&.hh\fP"
.br
.RI "Bare bones capability for treating a file as a raw executable image\&. "
.ti -1c
.RI "file \fBruleaction\&.cc\fP"
.br
.ti -1c
.RI "file \fBruleaction\&.hh\fP"
.br
.RI "This is the basic set of transformation \fBRule\fP objects\&. "
.ti -1c
.RI "file \fBrulecompile\&.cc\fP"
.br
.ti -1c
.RI "file \fBrulecompile\&.hh\fP"
.br
.ti -1c
.RI "file \fBsemantics\&.cc\fP"
.br
.ti -1c
.RI "file \fBsemantics\&.hh\fP"
.br
.ti -1c
.RI "file \fBsleigh\&.cc\fP"
.br
.ti -1c
.RI "file \fBsleigh\&.hh\fP"
.br
.ti -1c
.RI "file \fBsleigh_arch\&.cc\fP"
.br
.ti -1c
.RI "file \fBsleigh_arch\&.hh\fP"
.br
.RI "\fBArchitecture\fP objects that use a \fBTranslate\fP object derived from \fBSleigh\fP\&. "
.ti -1c
.RI "file \fBsleighbase\&.cc\fP"
.br
.ti -1c
.RI "file \fBsleighbase\&.hh\fP"
.br
.RI "Base class for applications that process SLEIGH format specifications\&. "
.ti -1c
.RI "file \fBsleighexample\&.cc\fP"
.br
.ti -1c
.RI "file \fBslgh_compile\&.cc\fP"
.br
.ti -1c
.RI "file \fBslgh_compile\&.hh\fP"
.br
.ti -1c
.RI "file \fBslghpatexpress\&.cc\fP"
.br
.ti -1c
.RI "file \fBslghpatexpress\&.hh\fP"
.br
.ti -1c
.RI "file \fBslghpattern\&.cc\fP"
.br
.ti -1c
.RI "file \fBslghpattern\&.hh\fP"
.br
.ti -1c
.RI "file \fBslghsymbol\&.cc\fP"
.br
.ti -1c
.RI "file \fBslghsymbol\&.hh\fP"
.br
.ti -1c
.RI "file \fBspace\&.cc\fP"
.br
.ti -1c
.RI "file \fBspace\&.hh\fP"
.br
.RI "Classes for describing address spaces\&. "
.ti -1c
.RI "file \fBsubflow\&.cc\fP"
.br
.ti -1c
.RI "file \fBsubflow\&.hh\fP"
.br
.ti -1c
.RI "file \fBtranslate\&.cc\fP"
.br
.ti -1c
.RI "file \fBtranslate\&.hh\fP"
.br
.RI "Classes for disassembly and pcode generation\&. "
.ti -1c
.RI "file \fBtype\&.cc\fP"
.br
.ti -1c
.RI "file \fBtype\&.hh\fP"
.br
.RI "Classes for describing and printing data-types\&. "
.ti -1c
.RI "file \fBtypegrp_ghidra\&.cc\fP"
.br
.ti -1c
.RI "file \fBtypegrp_ghidra\&.hh\fP"
.br
.RI "Interface for requesting data-type information from a Ghidra client\&. "
.ti -1c
.RI "file \fBtypeop\&.cc\fP"
.br
.ti -1c
.RI "file \fBtypeop\&.hh\fP"
.br
.RI "Data-type and behavior information associated with specific p-code op-codes\&. "
.ti -1c
.RI "file \fBtypes\&.h\fP"
.br
.ti -1c
.RI "file \fBunify\&.cc\fP"
.br
.ti -1c
.RI "file \fBunify\&.hh\fP"
.br
.ti -1c
.RI "file \fBuserop\&.cc\fP"
.br
.ti -1c
.RI "file \fBuserop\&.hh\fP"
.br
.RI "Classes for more detailed definitions of user defined p-code operations\&. "
.ti -1c
.RI "file \fBvariable\&.cc\fP"
.br
.ti -1c
.RI "file \fBvariable\&.hh\fP"
.br
.RI "Definitions for high-level variables\&. "
.ti -1c
.RI "file \fBvarmap\&.cc\fP"
.br
.ti -1c
.RI "file \fBvarmap\&.hh\fP"
.br
.ti -1c
.RI "file \fBvarnode\&.cc\fP"
.br
.ti -1c
.RI "file \fBvarnode\&.hh\fP"
.br
.RI "The \fBVarnode\fP and \fBVarnodeBank\fP classes\&. "
.ti -1c
.RI "file \fBxml\&.hh\fP"
.br
.ti -1c
.RI "file \fBxml_arch\&.cc\fP"
.br
.ti -1c
.RI "file \fBxml_arch\&.hh\fP"
.br
.RI "Extension to read executables based on an XML format\&. "
.in -1c
