.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions Directory Reference" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBASTGraphSelectionHandler\&.java\fP"
.br
.ti -1c
.RI "file \fBASTGraphTask\&.java\fP"
.br
.ti -1c
.RI "file \fBBackwardsSliceAction\&.java\fP"
.br
.ti -1c
.RI "file \fBBackwardsSliceToPCodeOpsAction\&.java\fP"
.br
.ti -1c
.RI "file \fBCloneDecompilerAction\&.java\fP"
.br
.ti -1c
.RI "file \fBCommitLocalsAction\&.java\fP"
.br
.ti -1c
.RI "file \fBCommitParamsAction\&.java\fP"
.br
.ti -1c
.RI "file \fBCreateStructureVariableAction\&.java\fP"
.br
.ti -1c
.RI "file \fBDebugDecompilerAction\&.java\fP"
.br
.ti -1c
.RI "file \fBDecompilerCursorPosition\&.java\fP"
.br
.ti -1c
.RI "file \fBDecompilerStructureVariableAction\&.java\fP"
.br
.ti -1c
.RI "file \fBDeletePrototypeOverrideAction\&.java\fP"
.br
.ti -1c
.RI "file \fBEditDataTypeAction\&.java\fP"
.br
.ti -1c
.RI "file \fBEditPropertiesAction\&.java\fP"
.br
.ti -1c
.RI "file \fBExportToCAction\&.java\fP"
.br
.ti -1c
.RI "file \fBFieldBasedSearchLocation\&.java\fP"
.br
.ti -1c
.RI "file \fBFillOutStructureCmd\&.java\fP"
.br
.ti -1c
.RI "file \fBFindAction\&.java\fP"
.br
.ti -1c
.RI "file \fBFindReferencesToDataTypeAction\&.java\fP"
.br
.ti -1c
.RI "file \fBForwardSliceAction\&.java\fP"
.br
.ti -1c
.RI "file \fBForwardSliceToPCodeOpsAction\&.java\fP"
.br
.ti -1c
.RI "file \fBGraphASTControlFlowAction\&.java\fP"
.br
.ti -1c
.RI "file \fBHighlightDefinedUseAction\&.java\fP"
.br
.ti -1c
.RI "file \fBListingStructureVariableAction\&.java\fP"
.br
.ti -1c
.RI "file \fBOverridePrototypeAction\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameConstantTask\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameFunctionAction\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameGlobalVariableTask\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameStructureFieldTask\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameTask\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameVariableAction\&.java\fP"
.br
.ti -1c
.RI "file \fBRenameVariableTask\&.java\fP"
.br
.ti -1c
.RI "file \fBRetypeVariableAction\&.java\fP"
.br
.ti -1c
.RI "file \fBSelectAllAction\&.java\fP"
.br
.ti -1c
.RI "file \fBSpecifyCPrototypeAction\&.java\fP"
.br
.in -1c
