.TH "FieldQuality" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldQuality
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slgh_compile\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldQuality\fP (string *nm, \fBuintb\fP *l, \fBuintb\fP *h)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "uint4 \fBlow\fP"
.br
.ti -1c
.RI "uint4 \fBhigh\fP"
.br
.ti -1c
.RI "bool \fBsignext\fP"
.br
.ti -1c
.RI "bool \fBflow\fP"
.br
.ti -1c
.RI "bool \fBhex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file slgh_compile\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldQuality::FieldQuality (string * nm, \fBuintb\fP * l, \fBuintb\fP * h)"

.PP
Definition at line 99 of file slgh_compile\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "bool FieldQuality::flow"

.PP
Definition at line 63 of file slgh_compile\&.hh\&.
.SS "bool FieldQuality::hex"

.PP
Definition at line 64 of file slgh_compile\&.hh\&.
.SS "uint4 FieldQuality::high"

.PP
Definition at line 61 of file slgh_compile\&.hh\&.
.SS "uint4 FieldQuality::low"

.PP
Definition at line 61 of file slgh_compile\&.hh\&.
.SS "string FieldQuality::name"

.PP
Definition at line 60 of file slgh_compile\&.hh\&.
.SS "bool FieldQuality::signext"

.PP
Definition at line 62 of file slgh_compile\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
