.TH "FixedHandle" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FixedHandle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <context\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAddrSpace\fP * \fBspace\fP"
.br
.ti -1c
.RI "uint4 \fBsize\fP"
.br
.ti -1c
.RI "\fBAddrSpace\fP * \fBoffset_space\fP"
.br
.ti -1c
.RI "\fBuintb\fP \fBoffset_offset\fP"
.br
.ti -1c
.RI "uint4 \fBoffset_size\fP"
.br
.ti -1c
.RI "\fBAddrSpace\fP * \fBtemp_space\fP"
.br
.ti -1c
.RI "\fBuintb\fP \fBtemp_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file context\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuintb\fP FixedHandle::offset_offset"

.PP
Definition at line 39 of file context\&.hh\&.
.SS "uint4 FixedHandle::offset_size"

.PP
Definition at line 40 of file context\&.hh\&.
.SS "\fBAddrSpace\fP* FixedHandle::offset_space"

.PP
Definition at line 38 of file context\&.hh\&.
.SS "uint4 FixedHandle::size"

.PP
Definition at line 37 of file context\&.hh\&.
.SS "\fBAddrSpace\fP* FixedHandle::space"

.PP
Definition at line 36 of file context\&.hh\&.
.SS "\fBuintb\fP FixedHandle::temp_offset"

.PP
Definition at line 42 of file context\&.hh\&.
.SS "\fBAddrSpace\fP* FixedHandle::temp_space"

.PP
Definition at line 41 of file context\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
