.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/float.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/float.hh \- Support for decoding different floating-point formats\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'xml\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFloatFormat\fP"
.br
.RI "Encoding information for a single floating-point format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Support for decoding different floating-point formats\&. 


.PP
Definition in file \fBfloat\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
