.TH "FlowRefSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlowRefSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSpecificSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlowRefSymbol\fP (void)"
.br
.ti -1c
.RI "\fBFlowRefSymbol\fP (const string &nm, \fBAddrSpace\fP *cspc)"
.br
.ti -1c
.RI "virtual \fBVarnodeTpl\fP * \fBgetVarnode\fP (void) const"
.br
.ti -1c
.RI "virtual \fBPatternExpression\fP * \fBgetPatternExpression\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBgetFixedHandle\fP (\fBFixedHandle\fP &hand, \fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBsaveXmlHeader\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBSleighBase\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 406 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FlowRefSymbol::FlowRefSymbol (void)\fC [inline]\fP"

.PP
Definition at line 409 of file slghsymbol\&.hh\&.
.SS "FlowRefSymbol::FlowRefSymbol (const string & nm, \fBAddrSpace\fP * cspc)"

.PP
Definition at line 1297 of file slghsymbol\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void FlowRefSymbol::getFixedHandle (\fBFixedHandle\fP & hand, \fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBTripleSymbol\fP\&.
.PP
Definition at line 1312 of file slghsymbol\&.cc\&.
.SS "virtual \fBPatternExpression\fP* FlowRefSymbol::getPatternExpression (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBTripleSymbol\fP\&.
.PP
Definition at line 412 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP FlowRefSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 415 of file slghsymbol\&.hh\&.
.SS "\fBVarnodeTpl\fP * FlowRefSymbol::getVarnode (void) const\fC [virtual]\fP"

.PP
Implements \fBSpecificSymbol\fP\&.
.PP
Definition at line 1303 of file slghsymbol\&.cc\&.
.SS "void FlowRefSymbol::print (ostream & s, \fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBTripleSymbol\fP\&.
.PP
Definition at line 1322 of file slghsymbol\&.cc\&.
.SS "void FlowRefSymbol::restoreXml (const \fBElement\fP * el, \fBSleighBase\fP * trans)\fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 1345 of file slghsymbol\&.cc\&.
.SS "void FlowRefSymbol::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 1329 of file slghsymbol\&.cc\&.
.SS "void FlowRefSymbol::saveXmlHeader (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 1337 of file slghsymbol\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
