.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/fspec.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/fspec.hh \- Definitions for specifying functions prototypes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'op\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBParamUnassignedError\fP"
.br
.RI "Exception thrown when a prototype can't be modeled properly\&. "
.ti -1c
.RI "class \fBParamEntry\fP"
.br
.RI "A contiguous range of memory that can be used to pass parameters\&. "
.ti -1c
.RI "class \fBParamTrial\fP"
.br
.RI "A register or memory register that may be used to pass a parameter or return value\&. "
.ti -1c
.RI "class \fBParamActive\fP"
.br
.RI "Container class for \fBParamTrial\fP objects\&. "
.ti -1c
.RI "class \fBFspecSpace\fP"
.br
.RI "A special space for encoding \fBFuncCallSpecs\fP\&. "
.ti -1c
.RI "struct \fBParameterPieces\fP"
.br
.RI "Basic elements of a parameter: address, data-type, properties\&. "
.ti -1c
.RI "class \fBEffectRecord\fP"
.br
.RI "Description of the indirect effect a sub-function has on a memory range\&. "
.ti -1c
.RI "class \fBParamList\fP"
.br
.ti -1c
.RI "class \fBParamListStandard\fP"
.br
.RI "A standard model for parameters as an ordered list of storage resources\&. "
.ti -1c
.RI "class \fBParamListStandardOut\fP"
.br
.RI "A standard model for passing back return values from a function\&. "
.ti -1c
.RI "class \fBParamListRegister\fP"
.br
.RI "An unstructured model for passing input parameters to a function\&. "
.ti -1c
.RI "class \fBParamListMerged\fP"
.br
.RI "A union of other input parameter passing models\&. "
.ti -1c
.RI "class \fBProtoModel\fP"
.br
.RI "A \fBprototype\fP \fBmodel:\fP a model for passing parameters between functions\&. "
.ti -1c
.RI "class \fBScoreProtoModel\fP"
.br
.RI "Class for calculating 'goodness of fit' of parameter trials against a prototype model\&. "
.ti -1c
.RI "class \fBProtoModelMerged\fP"
.br
.RI "A prototype model made by merging together other models\&. "
.ti -1c
.RI "class \fBProtoParameter\fP"
.br
.RI "A function parameter viewed as a name, data-type, and storage address\&. "
.ti -1c
.RI "class \fBParameterBasic\fP"
.br
.RI "A stand-alone parameter with no backing symbol\&. "
.ti -1c
.RI "class \fBProtoStore\fP"
.br
.RI "A collection parameter descriptions making up a function prototype\&. "
.ti -1c
.RI "class \fBParameterSymbol\fP"
.br
.RI "A parameter with a formal backing \fBSymbol\fP\&. "
.ti -1c
.RI "class \fBProtoStoreSymbol\fP"
.br
.RI "A collection of parameter descriptions backed by \fBSymbol\fP information\&. "
.ti -1c
.RI "class \fBProtoStoreInternal\fP"
.br
.RI "A collection of parameter descriptions without backing symbols\&. "
.ti -1c
.RI "struct \fBPrototypePieces\fP"
.br
.RI "Raw components of a function prototype (obtained from parsing source code) "
.ti -1c
.RI "class \fBFuncProto\fP"
.br
.RI "A \fBfunction\fP \fBprototype\fP\&. "
.ti -1c
.RI "class \fBFuncCallSpecs\fP"
.br
.RI "A class for analyzing parameters to a sub-function call\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definitions for specifying functions prototypes\&. 


.PP
Definition in file \fBfspec\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
