.TH "ghidra.app.decompiler.ClangLine" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangLine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangLine\fP (int lineNumber, int indent)"
.br
.ti -1c
.RI "String \fBgetIndentString\fP ()"
.br
.ti -1c
.RI "int \fBgetIndent\fP ()"
.br
.ti -1c
.RI "void \fBaddToken\fP (\fBClangToken\fP tok)"
.br
.ti -1c
.RI "ArrayList< \fBClangToken\fP > \fBgetAllTokens\fP ()"
.br
.ti -1c
.RI "int \fBgetNumTokens\fP ()"
.br
.ti -1c
.RI "int \fBgetLineNumber\fP ()"
.br
.ti -1c
.RI "\fBClangToken\fP \fBgetToken\fP (int i)"
.br
.ti -1c
.RI "String \fBtoDebugString\fP (\fBList\fP< \fBClangToken\fP > calloutTokens)"
.br
.ti -1c
.RI "String \fBtoDebugString\fP (\fBList\fP< \fBClangToken\fP > calloutTokens, String start, String end)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A line of C code\&. This is an independent grouping of C tokens from the statement, vardecl retype groups 
.PP
Definition at line 26 of file ClangLine\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangLine\&.ClangLine (int lineNumber, int indent)\fC [inline]\fP"

.PP
Definition at line 31 of file ClangLine\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.ClangLine\&.addToken (\fBClangToken\fP tok)\fC [inline]\fP"

.PP
Definition at line 49 of file ClangLine\&.java\&.
.SS "ArrayList<\fBClangToken\fP> ghidra\&.app\&.decompiler\&.ClangLine\&.getAllTokens ()\fC [inline]\fP"

.PP
Definition at line 54 of file ClangLine\&.java\&.
.SS "int ghidra\&.app\&.decompiler\&.ClangLine\&.getIndent ()\fC [inline]\fP"

.PP
Definition at line 45 of file ClangLine\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.ClangLine\&.getIndentString ()\fC [inline]\fP"

.PP
Definition at line 37 of file ClangLine\&.java\&.
.SS "int ghidra\&.app\&.decompiler\&.ClangLine\&.getLineNumber ()\fC [inline]\fP"

.PP
Definition at line 62 of file ClangLine\&.java\&.
.SS "int ghidra\&.app\&.decompiler\&.ClangLine\&.getNumTokens ()\fC [inline]\fP"

.PP
Definition at line 58 of file ClangLine\&.java\&.
.SS "\fBClangToken\fP ghidra\&.app\&.decompiler\&.ClangLine\&.getToken (int i)\fC [inline]\fP"

.PP
Definition at line 66 of file ClangLine\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.ClangLine\&.toDebugString (\fBList\fP< \fBClangToken\fP > calloutTokens)\fC [inline]\fP"

.PP
Definition at line 70 of file ClangLine\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.ClangLine\&.toDebugString (\fBList\fP< \fBClangToken\fP > calloutTokens, String start, String end)\fC [inline]\fP"

.PP
Definition at line 75 of file ClangLine\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.ClangLine\&.toString ()\fC [inline]\fP"

.PP
Definition at line 101 of file ClangLine\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
