.TH "ghidra.app.decompiler.component.DecompilerHoverProvider" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompilerHoverProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractHoverProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerHoverProvider\fP ()"
.br
.ti -1c
.RI "void \fBaddHoverService\fP (\fBDecompilerHoverService\fP hoverService)"
.br
.ti -1c
.RI "void \fBremoveHoverService\fP (\fBDecompilerHoverService\fP hoverService)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "ProgramLocation \fBgetHoverLocation\fP (FieldLocation fieldLocation, Field field, Rectangle fieldBounds, MouseEvent event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file DecompilerHoverProvider\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.DecompilerHoverProvider\&.DecompilerHoverProvider ()\fC [inline]\fP"

.PP
Definition at line 32 of file DecompilerHoverProvider\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerHoverProvider\&.addHoverService (\fBDecompilerHoverService\fP hoverService)\fC [inline]\fP"

.PP
Definition at line 36 of file DecompilerHoverProvider\&.java\&.
.SS "ProgramLocation ghidra\&.app\&.decompiler\&.component\&.DecompilerHoverProvider\&.getHoverLocation (FieldLocation fieldLocation, Field field, Rectangle fieldBounds, MouseEvent event)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 45 of file DecompilerHoverProvider\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerHoverProvider\&.removeHoverService (\fBDecompilerHoverService\fP hoverService)\fC [inline]\fP"

.PP
Definition at line 40 of file DecompilerHoverProvider\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
