.TH "ghidra.app.plugin.core.decompile.PrimaryDecompilerProvider" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.PrimaryDecompilerProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrimaryDecompilerProvider\fP (\fBDecompilePlugin\fP plugin)"
.br
.ti -1c
.RI "boolean \fBisConnected\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file PrimaryDecompilerProvider\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.PrimaryDecompilerProvider\&.PrimaryDecompilerProvider (\fBDecompilePlugin\fP plugin)\fC [inline]\fP"

.PP
Definition at line 20 of file PrimaryDecompilerProvider\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.PrimaryDecompilerProvider\&.isConnected ()\fC [inline]\fP"

.PP
Definition at line 25 of file PrimaryDecompilerProvider\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
