.TH "ghidra.app.decompiler.ClangOpToken" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangOpToken
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangOpToken\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "\fBPcodeOp\fP \fBgetPcodeOp\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMinAddress\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMaxAddress\fP ()"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlElement el, XmlElement end, PcodeFactory pfactory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBToken\fP representing an operation in C code text\&. This could be a keyword like 'if' or 'while' but could also be an operator like '+' or '*' The token may contain an id for the pcode object representing the operation 
.PP
Definition at line 37 of file ClangOpToken\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangOpToken\&.ClangOpToken (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 40 of file ClangOpToken\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangOpToken\&.getMaxAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 54 of file ClangOpToken\&.java\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangOpToken\&.getMinAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 49 of file ClangOpToken\&.java\&.
.SS "\fBPcodeOp\fP ghidra\&.app\&.decompiler\&.ClangOpToken\&.getPcodeOp ()\fC [inline]\fP"

.PP
Definition at line 46 of file ClangOpToken\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangOpToken\&.restoreFromXML (XmlElement el, XmlElement end, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 60 of file ClangOpToken\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
