.TH "ghidra.app.decompiler.component.hover.DecompilerHoverService" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.hover.DecompilerHoverService
.SH SYNOPSIS
.br
.PP
.PP
Inherits HoverService\&.
.PP
Inherited by \fBghidra\&.app\&.decompiler\&.component\&.hover\&.DataTypeDecompilerHover\fP, \fBghidra\&.app\&.decompiler\&.component\&.hover\&.FunctionSignatureDecompilerHover\fP, \fBghidra\&.app\&.decompiler\&.component\&.hover\&.ReferenceDecompilerHover\fP, and \fBghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 20 of file DecompilerHoverService\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
