.TH "ghidra.app.decompiler.parallel.DecompileConfigurer" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.parallel.DecompileConfigurer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBghidra\&.app\&.plugin\&.core\&.analysis\&.ConventionAnalysisDecompileConfigurer\fP, and \fBghidra\&.app\&.plugin\&.core\&.analysis\&.SwitchAnalysisDecompileConfigurer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBconfigure\fP (\fBDecompInterface\fP decompiler)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A callback interface that will be given a newly created \fBDecompInterface\fP to configure\&. 
.PP
Definition at line 24 of file DecompileConfigurer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.parallel\&.DecompileConfigurer\&.configure (\fBDecompInterface\fP decompiler)"
Configure the given decompiler
.PP
\fBParameters:\fP
.RS 4
\fIdecompiler\fP the decompiler to configure 
.RE
.PP

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.analysis\&.ConventionAnalysisDecompileConfigurer\fP, and \fBghidra\&.app\&.plugin\&.core\&.analysis\&.SwitchAnalysisDecompileConfigurer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
