.TH "GhidraDecompCapability" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GhidraDecompCapability \- The core decompiler commands capability\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ghidra_process\&.hh>\fP
.PP
Inherits \fBGhidraCapability\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinitialize\fP (void)"
.br
.RI "Complete initialization of an extension point\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The core decompiler commands capability\&. 

This class is instantiated as a singleton and registers all the basic decompiler commands that the Ghidra client can issue\&. 
.PP
Definition at line 52 of file ghidra_process\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void GhidraDecompCapability::initialize (void)\fC [virtual]\fP"

.PP
Complete initialization of an extension point\&. This method is implemented by each extension so it can do specialized integration 
.PP
Implements \fBCapabilityPoint\fP\&.
.PP
Definition at line 490 of file ghidra_process\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
