.TH "ghidra.app.decompiler.ClangSyntaxToken" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangSyntaxToken
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangSyntaxToken\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "\fBClangSyntaxToken\fP (\fBClangNode\fP par, String txt)"
.br
.ti -1c
.RI "\fBClangSyntaxToken\fP (\fBClangNode\fP par, String txt, String col)"
.br
.ti -1c
.RI "boolean \fBisVariableRef\fP ()"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlElement el, XmlElement end, PcodeFactory pfactory)"
.br
.ti -1c
.RI "int \fBgetOpen\fP ()"
.br
.ti -1c
.RI "int \fBgetClose\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A C code token which is not an operation, variable, function name, or type\&. Like '(' or ',' A SyntaxToken may be or may include spacing 
.PP
Definition at line 35 of file ClangSyntaxToken\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.ClangSyntaxToken (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 37 of file ClangSyntaxToken\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.ClangSyntaxToken (\fBClangNode\fP par, String txt)\fC [inline]\fP"

.PP
Definition at line 41 of file ClangSyntaxToken\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.ClangSyntaxToken (\fBClangNode\fP par, String txt, String col)\fC [inline]\fP"

.PP
Definition at line 45 of file ClangSyntaxToken\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.getClose ()\fC [inline]\fP"

.PP
Definition at line 68 of file ClangSyntaxToken\&.java\&.
.SS "int ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.getOpen ()\fC [inline]\fP"

.PP
Definition at line 67 of file ClangSyntaxToken\&.java\&.
.SS "boolean ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.isVariableRef ()\fC [inline]\fP"

.PP
Definition at line 51 of file ClangSyntaxToken\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangSyntaxToken\&.restoreFromXML (XmlElement el, XmlElement end, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 57 of file ClangSyntaxToken\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
