.TH "ghidra.app.decompiler.component.DecompileResultsListener" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompileResultsListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDecompileData\fP (\fBDecompileData\fP decompileData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file DecompileResultsListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompileResultsListener\&.setDecompileData (\fBDecompileData\fP decompileData)"


.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
