.TH "ghidra.app.plugin.core.analysis.DecompilerFunctionAnalyzer" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.analysis.DecompilerFunctionAnalyzer
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractAnalyzer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerFunctionAnalyzer\fP ()"
.br
.ti -1c
.RI "boolean \fBadded\fP (Program program, AddressSetView set, TaskMonitor monitor, MessageLog log)"
.br
.ti -1c
.RI "boolean \fBcanAnalyze\fP (Program program)"
.br
.ti -1c
.RI "boolean \fBgetDefaultEnablement\fP (Program program)"
.br
.ti -1c
.RI "void \fBregisterOptions\fP (Options options, Program program)"
.br
.ti -1c
.RI "void \fBoptionsChanged\fP (Options options, Program program)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBOPTION_DEFAULT_DECOMPILER_TIMEOUT_SECS\fP = 60"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file DecompilerFunctionAnalyzer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.DecompilerFunctionAnalyzer ()\fC [inline]\fP"

.PP
Definition at line 66 of file DecompilerFunctionAnalyzer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.added (Program program, AddressSetView set, TaskMonitor monitor, MessageLog log)\fC [inline]\fP"

.PP
Definition at line 73 of file DecompilerFunctionAnalyzer\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.canAnalyze (Program program)\fC [inline]\fP"

.PP
Definition at line 82 of file DecompilerFunctionAnalyzer\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.getDefaultEnablement (Program program)\fC [inline]\fP"

.PP
Definition at line 87 of file DecompilerFunctionAnalyzer\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.optionsChanged (Options options, Program program)\fC [inline]\fP"

.PP
Definition at line 129 of file DecompilerFunctionAnalyzer\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.registerOptions (Options options, Program program)\fC [inline]\fP"

.PP
Definition at line 111 of file DecompilerFunctionAnalyzer\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final int ghidra\&.app\&.plugin\&.core\&.analysis\&.DecompilerFunctionAnalyzer\&.OPTION_DEFAULT_DECOMPILER_TIMEOUT_SECS = 60\fC [static]\fP"

.PP
Definition at line 59 of file DecompilerFunctionAnalyzer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
