.TH "ghidra.app.decompiler.ClangReturnType" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangReturnType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangReturnType\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "DataType \fBgetDataType\fP ()"
.br
.ti -1c
.RI "\fBVarnode\fP \fBgetVarnode\fP ()"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlPullParser parser, PcodeFactory pfactory)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A group of C code tokens representing the return type of a function as at the beginning of a function prototype\&. 
.PP
Definition at line 36 of file ClangReturnType\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangReturnType\&.ClangReturnType (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 40 of file ClangReturnType\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "DataType ghidra\&.app\&.decompiler\&.ClangReturnType\&.getDataType ()\fC [inline]\fP"

.PP
Definition at line 46 of file ClangReturnType\&.java\&.
.SS "\fBVarnode\fP ghidra\&.app\&.decompiler\&.ClangReturnType\&.getVarnode (void)\fC [inline]\fP"

.PP
Definition at line 47 of file ClangReturnType\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangReturnType\&.restoreFromXML (XmlPullParser parser, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 50 of file ClangReturnType\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
