.TH "ghidra.app.plugin.core.decompile.actions.OverridePrototypeAction.ProtoOverrideDialog" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.OverridePrototypeAction.ProtoOverrideDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditFunctionSignatureDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FunctionDefinition \fBgetFunctionDefinition\fP ()"
.br
.ti -1c
.RI "\fBProtoOverrideDialog\fP (PluginTool tool, Function func, String signature, String conv)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBokCallback\fP ()"
.br
.ti -1c
.RI "boolean \fBtestResult\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file OverridePrototypeAction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.ProtoOverrideDialog\&.ProtoOverrideDialog (PluginTool tool, Function func, String signature, String conv)\fC [inline]\fP"

.PP
Definition at line 49 of file OverridePrototypeAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "FunctionDefinition ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.ProtoOverrideDialog\&.getFunctionDefinition ()\fC [inline]\fP"

.PP
Definition at line 45 of file OverridePrototypeAction\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.ProtoOverrideDialog\&.okCallback ()\fC [inline]\fP, \fC [protected]\fP"
This method gets called when the user clicks on the OK Button\&. The base class calls this method\&. 
.PP
Definition at line 61 of file OverridePrototypeAction\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.ProtoOverrideDialog\&.testResult ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 67 of file OverridePrototypeAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
