.TH "ghidra.app.plugin.core.decompile.actions.FillOutStructureCmd" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.FillOutStructureCmd
.SH SYNOPSIS
.br
.PP
.PP
Inherits BackgroundCommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFillOutStructureCmd\fP (Program program, ProgramLocation location, PluginTool tool)"
.br
.ti -1c
.RI "boolean \fBapplyTo\fP (DomainObject obj, TaskMonitor taskMonitor)"
.br
.ti -1c
.RI "\fBDecompileResults\fP \fBdecompileFunction\fP (Function f, \fBDecompInterface\fP decomplib)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Automatically creates a structure definition based on the references found by the decompiler\&.
.PP
If the parameter is already a structure pointer, any new references found will be added to the structure, even if the structure must grow\&. 
.PP
Definition at line 46 of file FillOutStructureCmd\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FillOutStructureCmd\&.FillOutStructureCmd (Program program, ProgramLocation location, PluginTool tool)\fC [inline]\fP"
\fBConstructor\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIprogram\fP the current program 
.br
\fIlocation\fP the current program location 
.br
\fItool\fP the current plugin tool 
.RE
.PP

.PP
Definition at line 84 of file FillOutStructureCmd\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FillOutStructureCmd\&.applyTo (DomainObject obj, TaskMonitor taskMonitor)\fC [inline]\fP"

.PP
Definition at line 92 of file FillOutStructureCmd\&.java\&.
.SS "\fBDecompileResults\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FillOutStructureCmd\&.decompileFunction (Function f, \fBDecompInterface\fP decomplib)\fC [inline]\fP"

.PP
Definition at line 354 of file FillOutStructureCmd\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
