.TH "ghidra.app.decompiler.DecompileOptions.IntegerFormatEnum" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.DecompileOptions.IntegerFormatEnum
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHexadecimal\fP =('Force Hexadecimal')"
.br
.ti -1c
.RI "\fBDecimal\fP =('Force Decimal')"
.br
.ti -1c
.RI "\fBBestFit\fP =('Best Fit')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file DecompileOptions\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String ghidra\&.app\&.decompiler\&.DecompileOptions\&.IntegerFormatEnum\&.toString ()\fC [inline]\fP"

.PP
Definition at line 216 of file DecompileOptions\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.DecompileOptions\&.IntegerFormatEnum\&.BestFit =('Best Fit')"

.PP
Definition at line 207 of file DecompileOptions\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.DecompileOptions\&.IntegerFormatEnum\&.Decimal =('Force Decimal')"

.PP
Definition at line 207 of file DecompileOptions\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.DecompileOptions\&.IntegerFormatEnum\&.Hexadecimal =('Force Hexadecimal')"

.PP
Definition at line 207 of file DecompileOptions\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
