.TH "ghidra.app.plugin.core.decompile.DecompilerClangTest" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.DecompilerClangTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestClangTextField_getTokenIndex\fP ()"
.br
.ti -1c
.RI "void \fBtestClangTextField_getNextTokenIndex\fP ()"
.br
.ti -1c
.RI "void \fBtestCommentAnnotation\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetProgramName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 32 of file DecompilerClangTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerClangTest\&.getProgramName ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 35 of file DecompilerClangTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerClangTest\&.testClangTextField_getNextTokenIndex ()\fC [inline]\fP"

.PP
Definition at line 59 of file DecompilerClangTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerClangTest\&.testClangTextField_getTokenIndex ()\fC [inline]\fP"

.PP
Definition at line 40 of file DecompilerClangTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerClangTest\&.testCommentAnnotation ()\fC [inline]\fP"

.PP
Definition at line 79 of file DecompilerClangTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
