.TH "ghidra.app.plugin.core.decompile.actions.OverridePrototypeAction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.OverridePrototypeAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits DockingAction\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProtoOverrideDialog\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOverridePrototypeAction\fP (String owner, PluginTool tool, \fBDecompilerController\fP controller)"
.br
.ti -1c
.RI "boolean \fBisEnabledForContext\fP (ActionContext context)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionContext context)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPcodeOp\fP \fBgetCallOp\fP (\fBDecompilerController\fP controller)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file OverridePrototypeAction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.OverridePrototypeAction (String owner, PluginTool tool, \fBDecompilerController\fP controller)\fC [inline]\fP"

.PP
Definition at line 82 of file OverridePrototypeAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.actionPerformed (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 113 of file OverridePrototypeAction\&.java\&.
.SS "static \fBPcodeOp\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.getCallOp (\fBDecompilerController\fP controller)\fC [inline]\fP, \fC [static]\fP"
Try to find the \fBPcodeOp\fP representing the call the user has selected 
.PP
\fBReturns:\fP
.RS 4
the \fBPcodeOp\fP or null 
.RE
.PP

.PP
Definition at line 174 of file OverridePrototypeAction\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.OverridePrototypeAction\&.isEnabledForContext (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 90 of file OverridePrototypeAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
