.TH "ghidra.app.plugin.core.decompile.actions.RenameGlobalVariableTask" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.RenameGlobalVariableTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenameGlobalVariableTask\fP (PluginTool \fBtool\fP, String old, \fBAddress\fP addr, Program prog)"
.br
.ti -1c
.RI "void \fBcommit\fP ()  throws DuplicateNameException, InvalidInputException "
.br
.ti -1c
.RI "String \fBgetTransactionName\fP ()"
.br
.ti -1c
.RI "boolean \fBisValid\fP (String newNm)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 25 of file RenameGlobalVariableTask\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameGlobalVariableTask\&.RenameGlobalVariableTask (PluginTool tool, String old, \fBAddress\fP addr, Program prog)\fC [inline]\fP"

.PP
Definition at line 31 of file RenameGlobalVariableTask\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameGlobalVariableTask\&.commit () throws DuplicateNameException, InvalidInputException\fC [inline]\fP"

.PP
Definition at line 40 of file RenameGlobalVariableTask\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameGlobalVariableTask\&.getTransactionName ()\fC [inline]\fP"

.PP
Definition at line 50 of file RenameGlobalVariableTask\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameGlobalVariableTask\&.isValid (String newNm)\fC [inline]\fP"

.PP
Definition at line 55 of file RenameGlobalVariableTask\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
