.TH "ghidra.app.decompiler.ClangNode" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangNode
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBghidra\&.app\&.decompiler\&.ClangToken\fP, and \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangNode\fP \fBParent\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMinAddress\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMaxAddress\fP ()"
.br
.ti -1c
.RI "void \fBsetHighlight\fP (Color c)"
.br
.ti -1c
.RI "int \fBnumChildren\fP ()"
.br
.ti -1c
.RI "\fBClangNode\fP \fBChild\fP (int i)"
.br
.ti -1c
.RI "\fBClangFunction\fP \fBgetClangFunction\fP ()"
.br
.ti -1c
.RI "void \fBflatten\fP (\fBList\fP< \fBClangNode\fP > list)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic tree interface 
.PP
Definition at line 34 of file ClangNode\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBClangNode\fP ghidra\&.app\&.decompiler\&.ClangNode\&.Child (int i)"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, and \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangNode\&.flatten (\fBList\fP< \fBClangNode\fP > list)"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, and \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "\fBClangFunction\fP ghidra\&.app\&.decompiler\&.ClangNode\&.getClangFunction ()"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP, and \fBghidra\&.app\&.decompiler\&.ClangFunction\fP\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangNode\&.getMaxAddress ()"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, \fBghidra\&.app\&.decompiler\&.ClangVariableToken\fP, \fBghidra\&.app\&.decompiler\&.ClangCommentToken\fP, \fBghidra\&.app\&.decompiler\&.ClangFuncNameToken\fP, \fBghidra\&.app\&.decompiler\&.ClangOpToken\fP, \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP, and \fBghidra\&.app\&.decompiler\&.ClangLabelToken\fP\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangNode\&.getMinAddress ()"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, \fBghidra\&.app\&.decompiler\&.ClangVariableToken\fP, \fBghidra\&.app\&.decompiler\&.ClangCommentToken\fP, \fBghidra\&.app\&.decompiler\&.ClangFuncNameToken\fP, \fBghidra\&.app\&.decompiler\&.ClangOpToken\fP, \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP, and \fBghidra\&.app\&.decompiler\&.ClangLabelToken\fP\&.
.SS "int ghidra\&.app\&.decompiler\&.ClangNode\&.numChildren ()"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, and \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "\fBClangNode\fP ghidra\&.app\&.decompiler\&.ClangNode\&.Parent ()"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, and \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangNode\&.setHighlight (Color c)"

.PP
Implemented in \fBghidra\&.app\&.decompiler\&.ClangToken\fP, and \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
