.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_arch.cc" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_arch.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'ghidra_context\&.hh'\fP
.br
\fC#include 'loadimage_ghidra\&.hh'\fP
.br
\fC#include 'database_ghidra\&.hh'\fP
.br
\fC#include 'ghidra_translate\&.hh'\fP
.br
\fC#include 'typegrp_ghidra\&.hh'\fP
.br
\fC#include 'comment_ghidra\&.hh'\fP
.br
\fC#include 'cpool_ghidra\&.hh'\fP
.br
\fC#include 'inject_ghidra\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
