.TH "ghidra.app.decompiler.component.EmptyDecompileData" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.EmptyDecompileData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.component\&.DecompileData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmptyDecompileData\fP (String message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file EmptyDecompileData\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.EmptyDecompileData\&.EmptyDecompileData (String message)\fC [inline]\fP"

.PP
Definition at line 21 of file EmptyDecompileData\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
