.TH "ghidra.app.plugin.core.decompile.actions.DecompilerStructureVariableAction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.DecompilerStructureVariableAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.CreateStructureVariableAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerStructureVariableAction\fP (String owner, PluginTool tool, \fBDecompilerController\fP \fBcontroller\fP)"
.br
.ti -1c
.RI "boolean \fBisEnabledForContext\fP (ActionContext context)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 30 of file DecompilerStructureVariableAction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.DecompilerStructureVariableAction\&.DecompilerStructureVariableAction (String owner, PluginTool tool, \fBDecompilerController\fP controller)\fC [inline]\fP"

.PP
Definition at line 32 of file DecompilerStructureVariableAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.DecompilerStructureVariableAction\&.isEnabledForContext (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 38 of file DecompilerStructureVariableAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
