.TH "ghidra.app.decompiler.ClangLabelToken" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangLabelToken
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangLabelToken\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "boolean \fBisVariableRef\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMinAddress\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMaxAddress\fP ()"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlElement el, XmlElement end, PcodeFactory pfactory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file ClangLabelToken\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangLabelToken\&.ClangLabelToken (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 27 of file ClangLabelToken\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangLabelToken\&.getMaxAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 39 of file ClangLabelToken\&.java\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangLabelToken\&.getMinAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 36 of file ClangLabelToken\&.java\&.
.SS "boolean ghidra\&.app\&.decompiler\&.ClangLabelToken\&.isVariableRef ()\fC [inline]\fP"

.PP
Definition at line 33 of file ClangLabelToken\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangLabelToken\&.restoreFromXML (XmlElement el, XmlElement end, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 42 of file ClangLabelToken\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
