.TH "ghidra.app.plugin.core.decompiler.validator.DecompilerValidator" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompiler.validator.DecompilerValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherits PostAnalysisValidator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerValidator\fP (Program program)"
.br
.ti -1c
.RI "ConditionResult \fBdoRun\fP (final TaskMonitor monitor)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file DecompilerValidator\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerValidator\&.DecompilerValidator (Program program)\fC [inline]\fP"

.PP
Definition at line 37 of file DecompilerValidator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "ConditionResult ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerValidator\&.doRun (final TaskMonitor monitor)\fC [inline]\fP"

.PP
Definition at line 42 of file DecompilerValidator\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerValidator\&.getDescription ()\fC [inline]\fP"

.PP
Definition at line 119 of file DecompilerValidator\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerValidator\&.getName (void)\fC [inline]\fP"

.PP
Definition at line 124 of file DecompilerValidator\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerValidator\&.toString ()\fC [inline]\fP"

.PP
Definition at line 129 of file DecompilerValidator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
