.TH "ghidra.app.decompiler.DecompileDebug" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.DecompileDebug
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBByteChunk\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompileDebug\fP (File debugf)"
.br
.ti -1c
.RI "void \fBsetFunction\fP (Function f)"
.br
.ti -1c
.RI "void \fBsetPcodeDataTypeManager\fP (PcodeDataTypeManager dtm)"
.br
.ti -1c
.RI "void \fBshutdown\fP (Language pcodelanguage, String xmlOptions)"
.br
.ti -1c
.RI "void \fBgetPcode\fP (\fBAddress\fP addr, Instruction instr)"
.br
.ti -1c
.RI "void \fBgetBytes\fP (\fBAddress\fP addr, byte[] res)"
.br
.ti -1c
.RI "void \fBgetComments\fP (String comm)"
.br
.ti -1c
.RI "void \fBgetSymbol\fP (\fBAddress\fP addr, String name)"
.br
.ti -1c
.RI "void \fBgetMapped\fP (Namespace namespc, String res)"
.br
.ti -1c
.RI "void \fBgetType\fP (String name, String res)"
.br
.ti -1c
.RI "void \fBgetType\fP (DataType dt)"
.br
.ti -1c
.RI "void \fBgetFNTypes\fP (HighFunction hfunc)"
.br
.ti -1c
.RI "void \fBgetTrackedRegisters\fP (String doc)"
.br
.ti -1c
.RI "void \fBgetCPoolRef\fP (String rec, long[] refs)"
.br
.ti -1c
.RI "void \fBaddFlowOverride\fP (\fBAddress\fP addr, FlowOverride fo)"
.br
.ti -1c
.RI "void \fBaddInject\fP (\fBAddress\fP addr, String name, int type, String payload)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file DecompileDebug\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.DecompileDebug\&.DecompileDebug (File debugf)\fC [inline]\fP"

.PP
Definition at line 95 of file DecompileDebug\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.addFlowOverride (\fBAddress\fP addr, FlowOverride fo)\fC [inline]\fP"

.PP
Definition at line 586 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.addInject (\fBAddress\fP addr, String name, int type, String payload)\fC [inline]\fP"

.PP
Definition at line 607 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getBytes (\fBAddress\fP addr, byte [] res)\fC [inline]\fP"

.PP
Definition at line 515 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getComments (String comm)\fC [inline]\fP"

.PP
Definition at line 532 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getCPoolRef (String rec, long [] refs)\fC [inline]\fP"

.PP
Definition at line 573 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getFNTypes (HighFunction hfunc)\fC [inline]\fP"

.PP
Definition at line 563 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getMapped (Namespace namespc, String res)\fC [inline]\fP"

.PP
Definition at line 547 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getPcode (\fBAddress\fP addr, Instruction instr)\fC [inline]\fP"

.PP
Definition at line 478 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getSymbol (\fBAddress\fP addr, String name)\fC [inline]\fP"

.PP
Definition at line 536 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getTrackedRegisters (String doc)\fC [inline]\fP"

.PP
Definition at line 569 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getType (String name, String res)\fC [inline]\fP"

.PP
Definition at line 555 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.getType (DataType dt)\fC [inline]\fP"

.PP
Definition at line 559 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.setFunction (Function f)\fC [inline]\fP"

.PP
Definition at line 116 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.setPcodeDataTypeManager (PcodeDataTypeManager dtm)\fC [inline]\fP"

.PP
Definition at line 124 of file DecompileDebug\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.DecompileDebug\&.shutdown (Language pcodelanguage, String xmlOptions)\fC [inline]\fP"

.PP
Definition at line 128 of file DecompileDebug\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
