.TH "ghidra.app.decompiler.component.hover.ScalarValueDecompilerHover" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.hover.ScalarValueDecompilerHover
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractScalarOperandHover, and \fBghidra\&.app\&.decompiler\&.component\&.hover\&.DecompilerHoverService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScalarValueDecompilerHover\fP (PluginTool tool)"
.br
.ti -1c
.RI "void \fBinitializeOptions\fP ()"
.br
.ti -1c
.RI "void \fBsetOptions\fP (Options options, String optionName)"
.br
.ti -1c
.RI "JComponent \fBgetHoverComponent\fP (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static final String \fBNAME\fP = 'Scalar Operand Display'"
.br
.ti -1c
.RI "static final String \fBDESCRIPTION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file ScalarValueDecompilerHover\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\&.ScalarValueDecompilerHover (PluginTool tool)\fC [inline]\fP"

.PP
Definition at line 47 of file ScalarValueDecompilerHover\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JComponent ghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\&.getHoverComponent (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)\fC [inline]\fP"

.PP
Definition at line 67 of file ScalarValueDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\&.initializeOptions ()\fC [inline]\fP"

.PP
Definition at line 52 of file ScalarValueDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\&.setOptions (Options options, String optionName)\fC [inline]\fP"

.PP
Definition at line 60 of file ScalarValueDecompilerHover\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String ghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\&.DESCRIPTION\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
=
        "Scalars are shown as 1-, 2-, 4-, and 8-byte values, each in decimal, hexadecimal, and " +
            "as ASCII character sequences\&."
.fi
.PP
Definition at line 43 of file ScalarValueDecompilerHover\&.java\&.
.SS "final String ghidra\&.app\&.decompiler\&.component\&.hover\&.ScalarValueDecompilerHover\&.NAME = 'Scalar Operand Display'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 42 of file ScalarValueDecompilerHover\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
