.TH "ghidra.app.plugin.core.decompiler.validator.DecompilerParameterIDValidator" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompiler.validator.DecompilerParameterIDValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherits PostAnalysisValidator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerParameterIDValidator\fP (Program program)"
.br
.ti -1c
.RI "ConditionResult \fBdoRun\fP (TaskMonitor monitor)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBMIN_NUM_FUNCS\fP = 'Minimum analysis threshold (% of funcs)'"
.br
.ti -1c
.RI "static final int \fBMIN_NUM_FUNCS_DEFAULT\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file DecompilerParameterIDValidator\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.DecompilerParameterIDValidator (Program program)\fC [inline]\fP"

.PP
Definition at line 32 of file DecompilerParameterIDValidator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "ConditionResult ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.doRun (TaskMonitor monitor)\fC [inline]\fP"

.PP
Definition at line 37 of file DecompilerParameterIDValidator\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.getDescription ()\fC [inline]\fP"

.PP
Definition at line 76 of file DecompilerParameterIDValidator\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.getName (void)\fC [inline]\fP"

.PP
Definition at line 82 of file DecompilerParameterIDValidator\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.toString ()\fC [inline]\fP"

.PP
Definition at line 87 of file DecompilerParameterIDValidator\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.MIN_NUM_FUNCS = 'Minimum analysis threshold (% of funcs)'\fC [static]\fP"

.PP
Definition at line 29 of file DecompilerParameterIDValidator\&.java\&.
.SS "final int ghidra\&.app\&.plugin\&.core\&.decompiler\&.validator\&.DecompilerParameterIDValidator\&.MIN_NUM_FUNCS_DEFAULT = 1\fC [static]\fP"

.PP
Definition at line 30 of file DecompilerParameterIDValidator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
