.TH "ghidra.app.decompiler.ClangFunction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangFunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangFunction\fP (\fBClangNode\fP par, HighFunction hf)"
.br
.ti -1c
.RI "\fBClangFunction\fP \fBgetClangFunction\fP ()"
.br
.ti -1c
.RI "HighFunction \fBgetHighFunction\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
All the fields making up one function in the display 
.PP
Definition at line 33 of file ClangFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangFunction\&.ClangFunction (\fBClangNode\fP par, HighFunction hf)\fC [inline]\fP"

.PP
Definition at line 36 of file ClangFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBClangFunction\fP ghidra\&.app\&.decompiler\&.ClangFunction\&.getClangFunction ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 38 of file ClangFunction\&.java\&.
.SS "HighFunction ghidra\&.app\&.decompiler\&.ClangFunction\&.getHighFunction ()\fC [inline]\fP"

.PP
Definition at line 39 of file ClangFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
