.TH "ghidra.app.decompiler.component.DualDecompilerActionContext" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DualDecompilerActionContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits ActionContext, RestrictedAddressSetContext, and CodeComparisonPanelActionContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDualDecompilerActionContext\fP (ComponentProvider provider, \fBCDisplayPanel\fP cPanel, Object sourceObject)"
.br
.ti -1c
.RI "void \fBsetCodeComparisonPanel\fP (CodeComparisonPanel<? extends FieldPanelCoordinator > codeComparisonPanel)"
.br
.ti -1c
.RI "CodeComparisonPanel<? extends FieldPanelCoordinator > \fBgetCodeComparisonPanel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAction\fP context for a dual decompiler panel\&. 
.PP
Definition at line 28 of file DualDecompilerActionContext\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.DualDecompilerActionContext\&.DualDecompilerActionContext (ComponentProvider provider, \fBCDisplayPanel\fP cPanel, Object sourceObject)\fC [inline]\fP"
Creates an action context for a dual decompiler panel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprovider\fP the provider for this context 
.br
\fIcPanel\fP the decompiler panel associated with this context 
.br
\fIsourceObject\fP the source of the action 
.RE
.PP

.PP
Definition at line 39 of file DualDecompilerActionContext\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "CodeComparisonPanel<? extends FieldPanelCoordinator> ghidra\&.app\&.decompiler\&.component\&.DualDecompilerActionContext\&.getCodeComparisonPanel ()\fC [inline]\fP"

.PP
Definition at line 54 of file DualDecompilerActionContext\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DualDecompilerActionContext\&.setCodeComparisonPanel (CodeComparisonPanel<? extends FieldPanelCoordinator > codeComparisonPanel)\fC [inline]\fP"
Sets the CodeComparisonPanel associated with this context\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcodeComparisonPanel\fP the code comparison panel\&. 
.RE
.PP

.PP
Definition at line 48 of file DualDecompilerActionContext\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
