.TH "ghidra.app.decompiler.parallel.DecompilerReducer< R, D >" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.parallel.DecompilerReducer< R, D >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "R \fBreduce\fP (\fBList\fP< DominantPair< \fBAddress\fP, D >> list)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file DecompilerReducer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "R \fBghidra\&.app\&.decompiler\&.parallel\&.DecompilerReducer\fP< R, D >\&.reduce (\fBList\fP< DominantPair< \fBAddress\fP, D >> list)"


.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
