.TH "ghidra.app.decompiler.component.DecompilerHighlightService" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompilerHighlightService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "LayoutModel \fBgetLayoutModel\fP ()"
.br
.ti -1c
.RI "void \fBclearHighlights\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file DecompilerHighlightService\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerHighlightService\&.clearHighlights ()"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP\&.
.SS "LayoutModel ghidra\&.app\&.decompiler\&.component\&.DecompilerHighlightService\&.getLayoutModel ()"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
