.TH "ghidra.app.plugin.core.decompile.AbstractDecompilerTest" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.AbstractDecompilerTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractProgramBasedTest\&.
.PP
Inherited by \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\fP, and \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerClangTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtearDown\fP ()  throws Exception "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBdecompile\fP (long addr)"
.br
.ti -1c
.RI "void \fBdecompile\fP (String addr)"
.br
.ti -1c
.RI "\fBDecompilerProvider\fP \fBgetDecompilerProvider\fP ()"
.br
.ti -1c
.RI "void \fBwaitForDecompiler\fP ()"
.br
.ti -1c
.RI "void \fBsetDecompilerLocation\fP (int line, int charPosition)"
.br
.ti -1c
.RI "void \fBdoubleClick\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDecompilePlugin\fP \fBdecompiler\fP"
.br
.ti -1c
.RI "\fBDecompilerProvider\fP \fBprovider\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file AbstractDecompilerTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.decompile (long addr)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 48 of file AbstractDecompilerTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.decompile (String addr)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 53 of file AbstractDecompilerTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.doubleClick ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 72 of file AbstractDecompilerTest\&.java\&.
.SS "\fBDecompilerProvider\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.getDecompilerProvider ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 58 of file AbstractDecompilerTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.setDecompilerLocation (int line, int charPosition)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 68 of file AbstractDecompilerTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.setUp () throws Exception\fC [inline]\fP"

.PP
Definition at line 31 of file AbstractDecompilerTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.tearDown () throws Exception\fC [inline]\fP"

.PP
Definition at line 42 of file AbstractDecompilerTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.waitForDecompiler ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 63 of file AbstractDecompilerTest\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDecompilePlugin\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.decompiler\fC [protected]\fP"

.PP
Definition at line 27 of file AbstractDecompilerTest\&.java\&.
.SS "\fBDecompilerProvider\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\&.provider\fC [protected]\fP"

.PP
Definition at line 28 of file AbstractDecompilerTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
