.TH "ghidra.app.decompiler.component.LocationClangHighlightController" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.LocationClangHighlightController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.component\&.ClangHighlightController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocationClangHighlightController\fP ()"
.br
.ti -1c
.RI "void \fBfieldLocationChanged\fP (FieldLocation location, Field field, EventTrigger trigger)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class to handle location based highlights for a decompiled function\&. 
.PP
Definition at line 28 of file LocationClangHighlightController\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.LocationClangHighlightController\&.LocationClangHighlightController ()\fC [inline]\fP"

.PP
Definition at line 30 of file LocationClangHighlightController\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.LocationClangHighlightController\&.fieldLocationChanged (FieldLocation location, Field field, EventTrigger trigger)\fC [inline]\fP"

.PP
Definition at line 34 of file LocationClangHighlightController\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
