.TH "ghidra.app.decompiler.DecompileOptions.CommentStyleEnum" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.DecompileOptions.CommentStyleEnum
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCStyle\fP =('/* C\-style comments */')"
.br
.ti -1c
.RI "\fBCPPStyle\fP =('// C++\-style comments')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file DecompileOptions\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String ghidra\&.app\&.decompiler\&.DecompileOptions\&.CommentStyleEnum\&.toString ()\fC [inline]\fP"

.PP
Definition at line 153 of file DecompileOptions\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.DecompileOptions\&.CommentStyleEnum\&.CPPStyle =('// C++\-style comments')"

.PP
Definition at line 144 of file DecompileOptions\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.DecompileOptions\&.CommentStyleEnum\&.CStyle =('/* C\-style comments */')"

.PP
Definition at line 144 of file DecompileOptions\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
