.TH "ghidra.app.decompiler.component.DecompilerCachingTest.FakeDecompilerController" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompilerCachingTest.FakeDecompilerController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MockUp< DecompilerController >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Cache< Function, \fBDecompileResults\fP > \fBbuildCache\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file DecompilerCachingTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Cache<Function, \fBDecompileResults\fP> ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.FakeDecompilerController\&.buildCache ()\fC [inline]\fP"

.PP
Definition at line 62 of file DecompilerCachingTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
