.TH "ghidra.app.cmd.function.DecompilerSwitchAnalysisCmd" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.cmd.function.DecompilerSwitchAnalysisCmd
.SH SYNOPSIS
.br
.PP
.PP
Inherits BackgroundCommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerSwitchAnalysisCmd\fP (\fBDecompileResults\fP decopmileResults)"
.br
.ti -1c
.RI "boolean \fBapplyTo\fP (DomainObject obj, TaskMonitor monitor)"
.br
.ti -1c
.RI "final void \fBmarkDataAsConstant\fP (\fBAddress\fP addr)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDecompInterface\fP \fBdecompiler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file DecompilerSwitchAnalysisCmd\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.cmd\&.function\&.DecompilerSwitchAnalysisCmd\&.DecompilerSwitchAnalysisCmd (\fBDecompileResults\fP decopmileResults)\fC [inline]\fP"

.PP
Definition at line 52 of file DecompilerSwitchAnalysisCmd\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.cmd\&.function\&.DecompilerSwitchAnalysisCmd\&.applyTo (DomainObject obj, TaskMonitor monitor)\fC [inline]\fP"

.PP
Definition at line 57 of file DecompilerSwitchAnalysisCmd\&.java\&.
.SS "final void ghidra\&.app\&.cmd\&.function\&.DecompilerSwitchAnalysisCmd\&.markDataAsConstant (\fBAddress\fP addr)\fC [inline]\fP"

.PP
Definition at line 392 of file DecompilerSwitchAnalysisCmd\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDecompInterface\fP ghidra\&.app\&.cmd\&.function\&.DecompilerSwitchAnalysisCmd\&.decompiler\fC [protected]\fP"

.PP
Definition at line 49 of file DecompilerSwitchAnalysisCmd\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
