.TH "ghidra.app.decompiler.ClangTokenGroup" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangTokenGroup
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Inherited by \fBghidra\&.app\&.decompiler\&.ClangFuncProto\fP, \fBghidra\&.app\&.decompiler\&.ClangFunction\fP, \fBghidra\&.app\&.decompiler\&.ClangReturnType\fP, \fBghidra\&.app\&.decompiler\&.ClangStatement\fP, and \fBghidra\&.app\&.decompiler\&.ClangVariableDecl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangTokenGroup\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMinAddress\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMaxAddress\fP ()"
.br
.ti -1c
.RI "void \fBAddTokenGroup\fP (Object obj)"
.br
.ti -1c
.RI "\fBClangNode\fP \fBParent\fP ()"
.br
.ti -1c
.RI "int \fBnumChildren\fP ()"
.br
.ti -1c
.RI "\fBClangNode\fP \fBChild\fP (int i)"
.br
.ti -1c
.RI "\fBClangFunction\fP \fBgetClangFunction\fP ()"
.br
.ti -1c
.RI "void \fBsetHighlight\fP (Color val)"
.br
.ti -1c
.RI "void \fBflatten\fP (\fBList\fP< \fBClangNode\fP > list)"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlPullParser parser, PcodeFactory pfactory)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A node in a tree of C code tokens\&. 
.PP
Definition at line 38 of file ClangTokenGroup\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.ClangTokenGroup (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 43 of file ClangTokenGroup\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.AddTokenGroup (Object obj)\fC [inline]\fP"

.PP
Definition at line 52 of file ClangTokenGroup\&.java\&.
.SS "\fBClangNode\fP ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.Child (int i)\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 73 of file ClangTokenGroup\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.flatten (\fBList\fP< \fBClangNode\fP > list)\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 81 of file ClangTokenGroup\&.java\&.
.SS "\fBClangFunction\fP ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.getClangFunction ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 74 of file ClangTokenGroup\&.java\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.getMaxAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 50 of file ClangTokenGroup\&.java\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.getMinAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 49 of file ClangTokenGroup\&.java\&.
.SS "int ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.numChildren ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 72 of file ClangTokenGroup\&.java\&.
.SS "\fBClangNode\fP ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.Parent ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 71 of file ClangTokenGroup\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.restoreFromXML (XmlPullParser parser, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 87 of file ClangTokenGroup\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.setHighlight (Color val)\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 76 of file ClangTokenGroup\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.ClangTokenGroup\&.toString ()\fC [inline]\fP"

.PP
Definition at line 129 of file ClangTokenGroup\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
