.TH "ghidra.app.plugin.core.decompile.DecompilePlugin" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.DecompilePlugin
.SH SYNOPSIS
.br
.PP
.PP
Inherits Plugin\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilePlugin\fP (PluginTool tool)"
.br
.ti -1c
.RI "void \fBwriteDataState\fP (SaveState saveState)"
.br
.ti -1c
.RI "void \fBreadDataState\fP (SaveState saveState)"
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.ti -1c
.RI "void \fBselectionChanged\fP (\fBDecompilerProvider\fP provider, ProgramSelection selection)"
.br
.ti -1c
.RI "void \fBprocessEvent\fP (PluginEvent event)"
.br
.ti -1c
.RI "ProgramLocation \fBgetCurrentLocation\fP ()"
.br
.ti -1c
.RI "void \fBserviceAdded\fP (Class<?> interfaceClass, Object service)"
.br
.ti -1c
.RI "void \fBserviceRemoved\fP (Class<?> interfaceClass, Object service)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plugin for producing a high-level C interpretation of assembly functions\&. 
.PP
Definition at line 66 of file DecompilePlugin\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.DecompilePlugin (PluginTool tool)\fC [inline]\fP"

.PP
Definition at line 91 of file DecompilePlugin\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.dispose ()\fC [inline]\fP"

.PP
Definition at line 203 of file DecompilePlugin\&.java\&.
.SS "ProgramLocation ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.getCurrentLocation ()\fC [inline]\fP"

.PP
Definition at line 317 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.init ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 108 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.processEvent (PluginEvent event)\fC [inline]\fP"
Process the plugin event; delegates the processing to the byte block\&. 
.PP
Definition at line 263 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.readDataState (SaveState saveState)\fC [inline]\fP"
Read data state; called after readConfigState()\&. Events generated by plugins we depend on should have been already been thrown by the time this method is called\&. 
.PP
Definition at line 166 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.selectionChanged (\fBDecompilerProvider\fP provider, ProgramSelection selection)\fC [inline]\fP"

.PP
Definition at line 247 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.serviceAdded (Class<?> interfaceClass, Object service)\fC [inline]\fP"

.PP
Definition at line 322 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.serviceRemoved (Class<?> interfaceClass, Object service)\fC [inline]\fP"

.PP
Definition at line 333 of file DecompilePlugin\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilePlugin\&.writeDataState (SaveState saveState)\fC [inline]\fP"
Tells the Plugin to write any data-dependent state to the output stream\&. 
.PP
Definition at line 139 of file DecompilePlugin\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
