.TH "ghidra.app.util.exporter.CppExporter" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.util.exporter.CppExporter
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exporter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCppExporter\fP ()"
.br
.ti -1c
.RI "\fBCppExporter\fP (\fBDecompileOptions\fP options)"
.br
.ti -1c
.RI "boolean \fBexport\fP (File file, DomainObject domainObj, AddressSetView addrSet, TaskMonitor monitor)  throws IOException, ExporterException "
.br
.ti -1c
.RI "\fBList\fP< Option > \fBgetOptions\fP (DomainObjectService domainObjectService)"
.br
.ti -1c
.RI "void \fBsetOptions\fP (\fBList\fP< Option > options)  throws OptionException "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBSPLIT_FILE\fP = 'Split each function into individual file'"
.br
.ti -1c
.RI "static final String \fBCREATE_C_FILE\fP = 'Create C File (\&.c)'"
.br
.ti -1c
.RI "static final String \fBCREATE_HEADER_FILE\fP = 'Create Header File (\&.h)'"
.br
.ti -1c
.RI "static final String \fBUSE_CPP_STYLE_COMMENTS\fP = 'Use C++ Style comments (//)'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file CppExporter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.util\&.exporter\&.CppExporter\&.CppExporter ()\fC [inline]\fP"

.PP
Definition at line 58 of file CppExporter\&.java\&.
.SS "ghidra\&.app\&.util\&.exporter\&.CppExporter\&.CppExporter (\fBDecompileOptions\fP options)\fC [inline]\fP"

.PP
Definition at line 62 of file CppExporter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.util\&.exporter\&.CppExporter\&.export (File file, DomainObject domainObj, AddressSetView addrSet, TaskMonitor monitor) throws IOException, ExporterException\fC [inline]\fP"

.PP
Definition at line 69 of file CppExporter\&.java\&.
.SS "\fBList\fP<Option> ghidra\&.app\&.util\&.exporter\&.CppExporter\&.getOptions (DomainObjectService domainObjectService)\fC [inline]\fP"

.PP
Definition at line 259 of file CppExporter\&.java\&.
.SS "void ghidra\&.app\&.util\&.exporter\&.CppExporter\&.setOptions (\fBList\fP< Option > options) throws OptionException\fC [inline]\fP"

.PP
Definition at line 269 of file CppExporter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String ghidra\&.app\&.util\&.exporter\&.CppExporter\&.CREATE_C_FILE = 'Create C File (\&.c)'\fC [static]\fP"

.PP
Definition at line 45 of file CppExporter\&.java\&.
.SS "final String ghidra\&.app\&.util\&.exporter\&.CppExporter\&.CREATE_HEADER_FILE = 'Create Header File (\&.h)'\fC [static]\fP"

.PP
Definition at line 46 of file CppExporter\&.java\&.
.SS "final String ghidra\&.app\&.util\&.exporter\&.CppExporter\&.SPLIT_FILE = 'Split each function into individual file'\fC [static]\fP"

.PP
Definition at line 44 of file CppExporter\&.java\&.
.SS "final String ghidra\&.app\&.util\&.exporter\&.CppExporter\&.USE_CPP_STYLE_COMMENTS = 'Use C++ Style comments (//)'\fC [static]\fP"

.PP
Definition at line 47 of file CppExporter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
