.TH "ghidra.app.decompiler.parallel.ChunkingParallelDecompiler< R >" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.parallel.ChunkingParallelDecompiler< R >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBList\fP< R > \fBdecompileFunctions\fP (\fBList\fP< Function > functions)  throws InterruptedException, 			Exception "
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class that simplifies some the concurrent datastructure setup required for decompiling functions\&. This class is meant to be used when you wish to decompile functions in groups (or chunks) rather than decompiling all functions at once\&.
.PP
\fBParameters:\fP
.RS 4
\fI<R>\fP The result type 
.RE
.PP

.PP
Definition at line 33 of file ChunkingParallelDecompiler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBList\fP<R> \fBghidra\&.app\&.decompiler\&.parallel\&.ChunkingParallelDecompiler\fP< R >\&.decompileFunctions (\fBList\fP< Function > functions) throws InterruptedException, 			Exception\fC [inline]\fP"

.PP
Definition at line 43 of file ChunkingParallelDecompiler\&.java\&.
.SS "void \fBghidra\&.app\&.decompiler\&.parallel\&.ChunkingParallelDecompiler\fP< R >\&.dispose ()\fC [inline]\fP"

.PP
Definition at line 58 of file ChunkingParallelDecompiler\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
