.TH "ghidra.app.decompiler.component.hover.ReferenceDecompilerHover" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.hover.ReferenceDecompilerHover
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractReferenceHover, and \fBghidra\&.app\&.decompiler\&.component\&.hover\&.DecompilerHoverService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReferenceDecompilerHover\fP (PluginTool tool)"
.br
.ti -1c
.RI "void \fBinitializeOptions\fP ()"
.br
.ti -1c
.RI "JComponent \fBgetHoverComponent\fP (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static final String \fBNAME\fP = 'Decompiler Reference Viewer'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file ReferenceDecompilerHover\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.hover\&.ReferenceDecompilerHover\&.ReferenceDecompilerHover (PluginTool tool)\fC [inline]\fP"

.PP
Definition at line 43 of file ReferenceDecompilerHover\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JComponent ghidra\&.app\&.decompiler\&.component\&.hover\&.ReferenceDecompilerHover\&.getHoverComponent (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)\fC [inline]\fP"

.PP
Definition at line 67 of file ReferenceDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.ReferenceDecompilerHover\&.initializeOptions ()\fC [inline]\fP"

.PP
Definition at line 48 of file ReferenceDecompilerHover\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String ghidra\&.app\&.decompiler\&.component\&.hover\&.ReferenceDecompilerHover\&.NAME = 'Decompiler Reference Viewer'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 36 of file ReferenceDecompilerHover\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
