.TH "ghidra.app.decompiler.DecompileProcess.DisposeState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.DecompileProcess.DisposeState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNOT_DISPOSED\fP"
.br
.ti -1c
.RI "\fBDISPOSED_ON_TIMEOUT\fP"
.br
.ti -1c
.RI "\fBDISPOSED_ON_CANCEL\fP"
.br
.ti -1c
.RI "\fBDISPOSED_ON_STARTUP_FAILURE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file DecompileProcess\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.DecompileProcess\&.DisposeState\&.DISPOSED_ON_CANCEL"

.PP
Definition at line 78 of file DecompileProcess\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.DecompileProcess\&.DisposeState\&.DISPOSED_ON_STARTUP_FAILURE"

.PP
Definition at line 79 of file DecompileProcess\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.DecompileProcess\&.DisposeState\&.DISPOSED_ON_TIMEOUT"

.PP
Definition at line 77 of file DecompileProcess\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.DecompileProcess\&.DisposeState\&.NOT_DISPOSED"

.PP
Definition at line 76 of file DecompileProcess\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
