.TH "ghidra.app.plugin.core.comments.DecompilerCommentsActionFactory" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.comments.DecompilerCommentsActionFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits CommentsActionFactory\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "DockingAction \fBdoGetEditCommentsAction\fP (CommentsDialog dialog, String name)"
.br
.ti -1c
.RI "DockingAction \fBdoGetSetCommentsAction\fP (CommentsDialog dialog, String name, String actionName, int commentType)"
.br
.ti -1c
.RI "boolean \fBdoIsCommentSupported\fP (ProgramLocation loc)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file DecompilerCommentsActionFactory\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "DockingAction ghidra\&.app\&.plugin\&.core\&.comments\&.DecompilerCommentsActionFactory\&.doGetEditCommentsAction (CommentsDialog dialog, String name)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 36 of file DecompilerCommentsActionFactory\&.java\&.
.SS "DockingAction ghidra\&.app\&.plugin\&.core\&.comments\&.DecompilerCommentsActionFactory\&.doGetSetCommentsAction (CommentsDialog dialog, String name, String actionName, int commentType)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 42 of file DecompilerCommentsActionFactory\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.comments\&.DecompilerCommentsActionFactory\&.doIsCommentSupported (ProgramLocation loc)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 48 of file DecompilerCommentsActionFactory\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
