.TH "ghidra.app.decompiler.component.ClangFieldElement" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.ClangFieldElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractTextFieldElement\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangFieldElement\fP (\fBClangToken\fP token, AttributedString as, int col)"
.br
.ti -1c
.RI "void \fBpaint\fP (JComponent c, Graphics g, int x, int y)"
.br
.ti -1c
.RI "FieldElement \fBsubstring\fP (int start, int end)"
.br
.ti -1c
.RI "FieldElement \fBreplaceAll\fP (char[] targets, char replacement)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file ClangFieldElement\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.ClangFieldElement\&.ClangFieldElement (\fBClangToken\fP token, AttributedString as, int col)\fC [inline]\fP"

.PP
Definition at line 30 of file ClangFieldElement\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.ClangFieldElement\&.paint (JComponent c, Graphics g, int x, int y)\fC [inline]\fP"

.PP
Definition at line 40 of file ClangFieldElement\&.java\&.
.SS "FieldElement ghidra\&.app\&.decompiler\&.component\&.ClangFieldElement\&.replaceAll (char [] targets, char replacement)\fC [inline]\fP"

.PP
Definition at line 69 of file ClangFieldElement\&.java\&.
.SS "FieldElement ghidra\&.app\&.decompiler\&.component\&.ClangFieldElement\&.substring (int start, int end)\fC [inline]\fP"

.PP
Definition at line 60 of file ClangFieldElement\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
