.TH "ghidra.app.plugin.core.decompile.actions.FieldBasedSearchLocation" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.FieldBasedSearchLocation
.SH SYNOPSIS
.br
.PP
.PP
Inherits SearchLocation\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldBasedSearchLocation\fP (FieldLocation fieldLocation, int startIndexInclusive, int endIndexInclusive, String searchText, boolean forwardDirection)"
.br
.ti -1c
.RI "FieldLocation \fBgetFieldLocation\fP ()"
.br
.ti -1c
.RI "CursorPosition \fBgetCursorPosition\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "String \fBfieldsToString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file FieldBasedSearchLocation\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FieldBasedSearchLocation\&.FieldBasedSearchLocation (FieldLocation fieldLocation, int startIndexInclusive, int endIndexInclusive, String searchText, boolean forwardDirection)\fC [inline]\fP"

.PP
Definition at line 26 of file FieldBasedSearchLocation\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FieldBasedSearchLocation\&.fieldsToString ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 43 of file FieldBasedSearchLocation\&.java\&.
.SS "CursorPosition ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FieldBasedSearchLocation\&.getCursorPosition ()\fC [inline]\fP"

.PP
Definition at line 38 of file FieldBasedSearchLocation\&.java\&.
.SS "FieldLocation ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FieldBasedSearchLocation\&.getFieldLocation ()\fC [inline]\fP"

.PP
Definition at line 33 of file FieldBasedSearchLocation\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
