.TH "ghidra.app.decompiler.component" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBhover\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApplyFunctionSignatureAction\fP"
.br
.ti -1c
.RI "class \fBBasicDecompilerCodeComparisonPanel\fP"
.br
.ti -1c
.RI "class \fBBasicDecompilerFieldPanelCoordinator\fP"
.br
.ti -1c
.RI "class \fBCDisplayPanel\fP"
.br
.ti -1c
.RI "class \fBClangFieldElement\fP"
.br
.ti -1c
.RI "class \fBClangHighlightController\fP"
.br
.ti -1c
.RI "interface \fBClangHighlightListener\fP"
.br
.ti -1c
.RI "class \fBClangLayoutController\fP"
.br
.ti -1c
.RI "class \fBClangTextField\fP"
.br
.ti -1c
.RI "class \fBDecompileData\fP"
.br
.ti -1c
.RI "class \fBDecompiler\fP"
.br
.ti -1c
.RI "class \fBDecompilerCachingTest\fP"
.br
.ti -1c
.RI "interface \fBDecompilerCallbackHandler\fP"
.br
.ti -1c
.RI "class \fBDecompilerCodeComparisonPanel\fP"
.br
.ti -1c
.RI "class \fBDecompilerController\fP"
.br
.ti -1c
.RI "interface \fBDecompileResultsListener\fP"
.br
.ti -1c
.RI "interface \fBDecompilerHighlightService\fP"
.br
.ti -1c
.RI "class \fBDecompilerHoverProvider\fP"
.br
.ti -1c
.RI "class \fBDecompilerManager\fP"
.br
.ti -1c
.RI "class \fBDecompilerPanel\fP"
.br
.ti -1c
.RI "class \fBDecompileRunnable\fP"
.br
.ti -1c
.RI "class \fBDecompilerUtils\fP"
.br
.ti -1c
.RI "class \fBDualDecompilerActionContext\fP"
.br
.ti -1c
.RI "interface \fBDualDecompileResultsListener\fP"
.br
.ti -1c
.RI "class \fBDualDecompilerFieldPanelCoordinator\fP"
.br
.ti -1c
.RI "class \fBEmptyDecompileData\fP"
.br
.ti -1c
.RI "class \fBLocationClangHighlightController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
