.TH "ghidra.app.plugin.core.decompile.DecompilerLocationMemento" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.DecompilerLocationMemento
.SH SYNOPSIS
.br
.PP
.PP
Inherits LocationMemento\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerLocationMemento\fP (Program program, ProgramLocation location, ViewerPosition viewerPosition)"
.br
.ti -1c
.RI "\fBDecompilerLocationMemento\fP (SaveState \fBsaveState\fP, Program[] programs)"
.br
.ti -1c
.RI "ViewerPosition \fBgetViewerPosition\fP ()"
.br
.ti -1c
.RI "void \fBsaveState\fP (SaveState saveState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file DecompilerLocationMemento\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerLocationMemento\&.DecompilerLocationMemento (Program program, ProgramLocation location, ViewerPosition viewerPosition)\fC [inline]\fP"

.PP
Definition at line 29 of file DecompilerLocationMemento\&.java\&.
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerLocationMemento\&.DecompilerLocationMemento (SaveState saveState, Program [] programs)\fC [inline]\fP"

.PP
Definition at line 34 of file DecompilerLocationMemento\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "ViewerPosition ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerLocationMemento\&.getViewerPosition ()\fC [inline]\fP"

.PP
Definition at line 42 of file DecompilerLocationMemento\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerLocationMemento\&.saveState (SaveState saveState)\fC [inline]\fP"

.PP
Definition at line 47 of file DecompilerLocationMemento\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
