.TH "ghidra.app.plugin.core.decompile.actions.ASTGraphTask" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.ASTGraphTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits Task\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBASTGraphTask\fP (GraphService graphService, boolean newGraph, int codeLimitPerBlock, \fBAddress\fP location, HighFunction hfunction, int graphType)"
.br
.ti -1c
.RI "void \fBrun\fP (TaskMonitor monitor)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateDataFlowGraph\fP (GraphData graph, TaskMonitor monitor)  throws CancelledException "
.br
.ti -1c
.RI "void \fBcreateControlFlowGraph\fP (GraphData graph, TaskMonitor monitor)  throws CancelledException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file ASTGraphTask\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.ASTGraphTask\&.ASTGraphTask (GraphService graphService, boolean newGraph, int codeLimitPerBlock, \fBAddress\fP location, HighFunction hfunction, int graphType)\fC [inline]\fP"

.PP
Definition at line 68 of file ASTGraphTask\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.ASTGraphTask\&.createControlFlowGraph (GraphData graph, TaskMonitor monitor) throws CancelledException\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 280 of file ASTGraphTask\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.ASTGraphTask\&.createDataFlowGraph (GraphData graph, TaskMonitor monitor) throws CancelledException\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 158 of file ASTGraphTask\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.ASTGraphTask\&.run (TaskMonitor monitor)\fC [inline]\fP"

.PP
Definition at line 103 of file ASTGraphTask\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
