.TH "ghidra.app.decompiler.component.ClangHighlightListener" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.ClangHighlightListener
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBghidra\&.app\&.decompiler\&.component\&.DecompilerPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtokenHighlightsChanged\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for a decompiler highlight change listener\&. 
.PP
Definition at line 22 of file ClangHighlightListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.ClangHighlightListener\&.tokenHighlightsChanged ()"
Method to invoke whenever the decompiler token highlights have changed\&. 
.PP
Implemented in \fBghidra\&.app\&.decompiler\&.component\&.DecompilerPanel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
