.TH "ghidra.app" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcmd\fP"
.br
.ti -1c
.RI "package \fBdecompiler\fP"
.br
.ti -1c
.RI "package \fBplugin\fP"
.br
.ti -1c
.RI "package \fButil\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
