.TH "ghidra.app.plugin.core.decompile.AbstractDecompilerFindReferencesActionTest.SpyDataTypeReferenceFinder< T extends DataTypeReferenceFinder >" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.AbstractDecompilerFindReferencesActionTest.SpyDataTypeReferenceFinder< T extends DataTypeReferenceFinder >
.SH SYNOPSIS
.br
.PP
.PP
Inherits MockUp< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfindReferences\fP (Program p, DataType dataType, Consumer< DataTypeReference > callback, TaskMonitor monitor)"
.br
.ti -1c
.RI "void \fBfindReferences\fP (Program p, Composite composite, String fieldName, Consumer< DataTypeReference > callback, TaskMonitor monitor)"
.br
.ti -1c
.RI "int \fBgetFindDataTypeReferencesCallCount\fP ()"
.br
.ti -1c
.RI "int \fBgetFindCompositeFieldReferencesCallCount\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.SpyDataTypeReferenceFinder\fP< T extends DataTypeReferenceFinder >\&.findReferences (Program p, DataType dataType, Consumer< DataTypeReference > callback, TaskMonitor monitor)\fC [inline]\fP"

.PP
Definition at line 120 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "void \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.SpyDataTypeReferenceFinder\fP< T extends DataTypeReferenceFinder >\&.findReferences (Program p, Composite composite, String fieldName, Consumer< DataTypeReference > callback, TaskMonitor monitor)\fC [inline]\fP"

.PP
Definition at line 127 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "int \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.SpyDataTypeReferenceFinder\fP< T extends DataTypeReferenceFinder >\&.getFindCompositeFieldReferencesCallCount ()\fC [inline]\fP"

.PP
Definition at line 137 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "int \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.SpyDataTypeReferenceFinder\fP< T extends DataTypeReferenceFinder >\&.getFindDataTypeReferencesCallCount ()\fC [inline]\fP"

.PP
Definition at line 133 of file AbstractDecompilerFindReferencesActionTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
