.TH "ghidra.app.decompiler.component.hover.DataTypeDecompilerHoverPlugin" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.hover.DataTypeDecompilerHoverPlugin
.SH SYNOPSIS
.br
.PP
.PP
Inherits Plugin\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataTypeDecompilerHoverPlugin\fP (PluginTool tool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A plugin to show tool tip text for hovering over data types in the decompiler\&. 
.PP
Definition at line 38 of file DataTypeDecompilerHoverPlugin\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.hover\&.DataTypeDecompilerHoverPlugin\&.DataTypeDecompilerHoverPlugin (PluginTool tool)\fC [inline]\fP"

.PP
Definition at line 42 of file DataTypeDecompilerHoverPlugin\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
