.TH "ghidra.app.decompiler.component.DecompilerCachingTest" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompilerCachingTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractGhidraHeadedIntegrationTest\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFakeDecompilerController\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBtestNewFunctionIsCacheMiss\fP ()"
.br
.ti -1c
.RI "void \fBtestReturnToPreviousFunctionIsCacheHit\fP ()"
.br
.ti -1c
.RI "void \fBtestCacheRemovesEntryWhenSizeIsExceeded\fP ()"
.br
.ti -1c
.RI "void \fBtestDomainChangeClearsTheCache\fP ()"
.br
.ti -1c
.RI "void \fBtestCacheIsClearedWhenProgramIsClosed\fP ()"
.br
.ti -1c
.RI "void \fBtestCacheIsClearedWhenOptionsChange\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Cache< Function, \fBDecompileResults\fP > \fBcache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file DecompilerCachingTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.setUp () throws Exception\fC [inline]\fP"

.PP
Definition at line 76 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.tearDown ()\fC [inline]\fP"

.PP
Definition at line 90 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.testCacheIsClearedWhenOptionsChange ()\fC [inline]\fP"

.PP
Definition at line 180 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.testCacheIsClearedWhenProgramIsClosed ()\fC [inline]\fP"

.PP
Definition at line 167 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.testCacheRemovesEntryWhenSizeIsExceeded ()\fC [inline]\fP"

.PP
Definition at line 120 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.testDomainChangeClearsTheCache ()\fC [inline]\fP"

.PP
Definition at line 147 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.testNewFunctionIsCacheMiss ()\fC [inline]\fP"

.PP
Definition at line 95 of file DecompilerCachingTest\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.testReturnToPreviousFunctionIsCacheHit ()\fC [inline]\fP"

.PP
Definition at line 107 of file DecompilerCachingTest\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "Cache<Function, \fBDecompileResults\fP> ghidra\&.app\&.decompiler\&.component\&.DecompilerCachingTest\&.cache"

.PP
Definition at line 56 of file DecompilerCachingTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
