.TH "ghidra.app.plugin.core.decompile.actions.DecompilerCursorPosition" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.DecompilerCursorPosition
.SH SYNOPSIS
.br
.PP
.PP
Inherits CursorPosition\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetOffset\fP (int offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file DecompilerCursorPosition\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.DecompilerCursorPosition\&.setOffset (int offset)\fC [inline]\fP"

.PP
Definition at line 35 of file DecompilerCursorPosition\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
