.TH "ghidra.app.decompiler.ClangFuncProto" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangFuncProto
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangTokenGroup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangFuncProto\fP (\fBClangNode\fP par)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The C code syntax for a function prototype 
.PP
Definition at line 31 of file ClangFuncProto\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangFuncProto\&.ClangFuncProto (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 32 of file ClangFuncProto\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
