.TH "ghidra.app.decompiler.DecompiledFunction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.DecompiledFunction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompiledFunction\fP (String signature, String c)"
.br
.ti -1c
.RI "String \fBgetSignature\fP ()"
.br
.ti -1c
.RI "String \fBgetC\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to hold pieces of a decompiled function\&. 
.PP
Definition at line 22 of file DecompiledFunction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.DecompiledFunction\&.DecompiledFunction (String signature, String c)\fC [inline]\fP"
Constructs a new decompiled function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsignature\fP the function signature or prototype (eg, 'int foo(double d)') 
.br
\fIc\fP the complete C code of the function\&. 
.RE
.PP

.PP
Definition at line 31 of file DecompiledFunction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String ghidra\&.app\&.decompiler\&.DecompiledFunction\&.getC ()\fC [inline]\fP"
Returns the complete C code of the function\&. 
.PP
\fBReturns:\fP
.RS 4
the complete C code of the function 
.RE
.PP

.PP
Definition at line 48 of file DecompiledFunction\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.DecompiledFunction\&.getSignature ()\fC [inline]\fP"
Returns the function signature or prototype (eg, 'int foo(double d)')\&. 
.PP
\fBReturns:\fP
.RS 4
the function signature or prototype (eg, 'int foo(double d)') 
.RE
.PP

.PP
Definition at line 40 of file DecompiledFunction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
