.TH "ghidra.app.decompiler.parallel" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.parallel
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChunkingParallelDecompiler\fP"
.br
.ti -1c
.RI "interface \fBDecompileConfigurer\fP"
.br
.ti -1c
.RI "class \fBDecompilerCallback\fP"
.br
.ti -1c
.RI "interface \fBDecompilerMapFunction\fP"
.br
.ti -1c
.RI "interface \fBDecompilerReducer\fP"
.br
.ti -1c
.RI "class \fBParallelDecompiler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
