.TH "ghidra.app.plugin.core.decompile.actions.FindAction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.FindAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits DockingAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFindAction\fP (PluginTool tool, \fBDecompilerController\fP controller, String owner)"
.br
.ti -1c
.RI "boolean \fBisEnabledForContext\fP (ActionContext context)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionContext context)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "FindDialog \fBgetFindDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file FindAction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FindAction\&.FindAction (PluginTool tool, \fBDecompilerController\fP controller, String owner)\fC [inline]\fP"

.PP
Definition at line 39 of file FindAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FindAction\&.actionPerformed (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 65 of file FindAction\&.java\&.
.SS "FindDialog ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FindAction\&.getFindDialog ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 86 of file FindAction\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.FindAction\&.isEnabledForContext (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 49 of file FindAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
