.TH "ghidra.app.plugin.core.decompile.actions.RenameVariableAction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.RenameVariableAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits DockingAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenameVariableAction\fP (String owner, PluginTool tool, \fBDecompilerController\fP controller)"
.br
.ti -1c
.RI "boolean \fBisEnabledForContext\fP (ActionContext context)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionContext context)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAddress\fP \fBgetStorageAddress\fP (\fBClangToken\fP tokenAtCursor, \fBDecompilerController\fP controller)"
.br
.ti -1c
.RI "static \fBHighVariable\fP \fBforgeHighVariable\fP (\fBAddress\fP addr, \fBDecompilerController\fP controller)"
.br
.ti -1c
.RI "static Structure \fBgetStructDataType\fP (\fBClangToken\fP tok)"
.br
.ti -1c
.RI "static int \fBgetDataTypeOffset\fP (\fBClangToken\fP tok)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file RenameVariableAction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.RenameVariableAction (String owner, PluginTool tool, \fBDecompilerController\fP controller)\fC [inline]\fP"

.PP
Definition at line 44 of file RenameVariableAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.actionPerformed (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 173 of file RenameVariableAction\&.java\&.
.SS "static \fBHighVariable\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.forgeHighVariable (\fBAddress\fP addr, \fBDecompilerController\fP controller)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 145 of file RenameVariableAction\&.java\&.
.SS "static int ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.getDataTypeOffset (\fBClangToken\fP tok)\fC [inline]\fP, \fC [static]\fP"
Get the offset of the field within its structure 
.PP
\fBParameters:\fP
.RS 4
\fItok\fP is the display token associated with the field 
.RE
.PP
\fBReturns:\fP
.RS 4
the offset, in bytes, of that field within its structure 
.RE
.PP

.PP
Definition at line 282 of file RenameVariableAction\&.java\&.
.SS "static \fBAddress\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.getStorageAddress (\fBClangToken\fP tokenAtCursor, \fBDecompilerController\fP controller)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 112 of file RenameVariableAction\&.java\&.
.SS "static Structure ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.getStructDataType (\fBClangToken\fP tok)\fC [inline]\fP, \fC [static]\fP"
Get the structure associated with a field token 
.PP
\fBParameters:\fP
.RS 4
\fItok\fP is the token representing a field 
.RE
.PP
\fBReturns:\fP
.RS 4
the structure which contains this field 
.RE
.PP

.PP
Definition at line 264 of file RenameVariableAction\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableAction\&.isEnabledForContext (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 53 of file RenameVariableAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
