.TH "ghidra.app.plugin.core.decompile.actions" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBASTGraphSelectionHandler\fP"
.br
.ti -1c
.RI "class \fBASTGraphTask\fP"
.br
.ti -1c
.RI "class \fBBackwardsSliceAction\fP"
.br
.ti -1c
.RI "class \fBBackwardsSliceToPCodeOpsAction\fP"
.br
.ti -1c
.RI "class \fBCloneDecompilerAction\fP"
.br
.ti -1c
.RI "class \fBCommitLocalsAction\fP"
.br
.ti -1c
.RI "class \fBCommitParamsAction\fP"
.br
.ti -1c
.RI "class \fBCreateStructureVariableAction\fP"
.br
.ti -1c
.RI "class \fBDebugDecompilerAction\fP"
.br
.ti -1c
.RI "class \fBDecompilerCursorPosition\fP"
.br
.ti -1c
.RI "class \fBDecompilerStructureVariableAction\fP"
.br
.ti -1c
.RI "class \fBDeletePrototypeOverrideAction\fP"
.br
.ti -1c
.RI "class \fBEditDataTypeAction\fP"
.br
.ti -1c
.RI "class \fBEditPropertiesAction\fP"
.br
.ti -1c
.RI "class \fBExportToCAction\fP"
.br
.ti -1c
.RI "class \fBFieldBasedSearchLocation\fP"
.br
.ti -1c
.RI "class \fBFillOutStructureCmd\fP"
.br
.ti -1c
.RI "class \fBFindAction\fP"
.br
.ti -1c
.RI "class \fBFindReferencesToDataTypeAction\fP"
.br
.ti -1c
.RI "class \fBForwardSliceAction\fP"
.br
.ti -1c
.RI "class \fBForwardSliceToPCodeOpsAction\fP"
.br
.ti -1c
.RI "class \fBGraphASTControlFlowAction\fP"
.br
.ti -1c
.RI "class \fBHighlightDefinedUseAction\fP"
.br
.ti -1c
.RI "class \fBListingStructureVariableAction\fP"
.br
.ti -1c
.RI "class \fBOverridePrototypeAction\fP"
.br
.ti -1c
.RI "class \fBRenameConstantTask\fP"
.br
.ti -1c
.RI "class \fBRenameFunctionAction\fP"
.br
.ti -1c
.RI "class \fBRenameGlobalVariableTask\fP"
.br
.ti -1c
.RI "class \fBRenameStructureFieldTask\fP"
.br
.ti -1c
.RI "class \fBRenameTask\fP"
.br
.ti -1c
.RI "class \fBRenameVariableAction\fP"
.br
.ti -1c
.RI "class \fBRenameVariableTask\fP"
.br
.ti -1c
.RI "class \fBRetypeVariableAction\fP"
.br
.ti -1c
.RI "class \fBSelectAllAction\fP"
.br
.ti -1c
.RI "class \fBSpecifyCPrototypeAction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
