.TH "ghidra.app.decompiler.ClangVariableToken" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangVariableToken
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangVariableToken\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "\fBVarnode\fP \fBgetVarnode\fP ()"
.br
.ti -1c
.RI "\fBPcodeOp\fP \fBgetPcodeOp\fP ()"
.br
.ti -1c
.RI "boolean \fBisVariableRef\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMinAddress\fP ()"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetMaxAddress\fP ()"
.br
.ti -1c
.RI "\fBHighVariable\fP \fBgetHighVariable\fP ()"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlElement el, XmlElement end, PcodeFactory pfactory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBToken\fP representing a C variable 
.PP
Definition at line 34 of file ClangVariableToken\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangVariableToken\&.ClangVariableToken (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 38 of file ClangVariableToken\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHighVariable\fP ghidra\&.app\&.decompiler\&.ClangVariableToken\&.getHighVariable ()\fC [inline]\fP"

.PP
Definition at line 70 of file ClangVariableToken\&.java\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangVariableToken\&.getMaxAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 65 of file ClangVariableToken\&.java\&.
.SS "\fBAddress\fP ghidra\&.app\&.decompiler\&.ClangVariableToken\&.getMinAddress ()\fC [inline]\fP"

.PP
Implements \fBghidra\&.app\&.decompiler\&.ClangNode\fP\&.
.PP
Definition at line 60 of file ClangVariableToken\&.java\&.
.SS "\fBPcodeOp\fP ghidra\&.app\&.decompiler\&.ClangVariableToken\&.getPcodeOp ()\fC [inline]\fP"

.PP
Definition at line 50 of file ClangVariableToken\&.java\&.
.SS "\fBVarnode\fP ghidra\&.app\&.decompiler\&.ClangVariableToken\&.getVarnode (void)\fC [inline]\fP"

.PP
Definition at line 45 of file ClangVariableToken\&.java\&.
.SS "boolean ghidra\&.app\&.decompiler\&.ClangVariableToken\&.isVariableRef ()\fC [inline]\fP"

.PP
Definition at line 55 of file ClangVariableToken\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangVariableToken\&.restoreFromXML (XmlElement el, XmlElement end, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 85 of file ClangVariableToken\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
