.TH "ghidra.app.plugin.core.analysis.SwitchAnalysisDecompileConfigurer" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.analysis.SwitchAnalysisDecompileConfigurer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.parallel\&.DecompileConfigurer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwitchAnalysisDecompileConfigurer\fP (Program p)"
.br
.ti -1c
.RI "void \fBconfigure\fP (\fBDecompInterface\fP decompiler)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A configurer for performing switch analysis\&. 
.PP
Definition at line 26 of file SwitchAnalysisDecompileConfigurer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.analysis\&.SwitchAnalysisDecompileConfigurer\&.SwitchAnalysisDecompileConfigurer (Program p)\fC [inline]\fP"

.PP
Definition at line 30 of file SwitchAnalysisDecompileConfigurer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.analysis\&.SwitchAnalysisDecompileConfigurer\&.configure (\fBDecompInterface\fP decompiler)\fC [inline]\fP"
Configure the given decompiler
.PP
\fBParameters:\fP
.RS 4
\fIdecompiler\fP the decompiler to configure 
.RE
.PP

.PP
Implements \fBghidra\&.app\&.decompiler\&.parallel\&.DecompileConfigurer\fP\&.
.PP
Definition at line 35 of file SwitchAnalysisDecompileConfigurer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
