.TH "ghidra.app.decompiler.component.hover.DataTypeDecompilerHover" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.hover.DataTypeDecompilerHover
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractDataTypeHover, and \fBghidra\&.app\&.decompiler\&.component\&.hover\&.DecompilerHoverService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitializeOptions\fP ()"
.br
.ti -1c
.RI "void \fBsetOptions\fP (Options options, String optionName)"
.br
.ti -1c
.RI "JComponent \fBgetHoverComponent\fP (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDataTypeDecompilerHover\fP (PluginTool tool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file DataTypeDecompilerHover\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.hover\&.DataTypeDecompilerHover\&.DataTypeDecompilerHover (PluginTool tool)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 42 of file DataTypeDecompilerHover\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JComponent ghidra\&.app\&.decompiler\&.component\&.hover\&.DataTypeDecompilerHover\&.getHoverComponent (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)\fC [inline]\fP"

.PP
Definition at line 62 of file DataTypeDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.DataTypeDecompilerHover\&.initializeOptions ()\fC [inline]\fP"

.PP
Definition at line 47 of file DataTypeDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.DataTypeDecompilerHover\&.setOptions (Options options, String optionName)\fC [inline]\fP"

.PP
Definition at line 55 of file DataTypeDecompilerHover\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
