.TH "ghidra.app.decompiler.component.DecompileData" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompileData
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBghidra\&.app\&.decompiler\&.component\&.EmptyDecompileData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompileData\fP (Program program, Function function, ProgramLocation location, \fBDecompileResults\fP decompileResults, String errorMessage, File debugFile, ViewerPosition viewerPosition)"
.br
.ti -1c
.RI "boolean \fBhasDecompileResults\fP ()"
.br
.ti -1c
.RI "\fBDecompileResults\fP \fBgetDecompileResults\fP ()"
.br
.ti -1c
.RI "Program \fBgetProgram\fP ()"
.br
.ti -1c
.RI "Function \fBgetFunction\fP ()"
.br
.ti -1c
.RI "HighFunction \fBgetHighFunction\fP ()"
.br
.ti -1c
.RI "ProgramLocation \fBgetLocation\fP ()"
.br
.ti -1c
.RI "\fBClangTokenGroup\fP \fBgetCCodeMarkup\fP ()"
.br
.ti -1c
.RI "String \fBgetErrorMessage\fP ()"
.br
.ti -1c
.RI "File \fBgetDebugFile\fP ()"
.br
.ti -1c
.RI "boolean \fBcontains\fP (ProgramLocation programLocation)"
.br
.ti -1c
.RI "AddressSpace \fBgetFunctionSpace\fP ()"
.br
.ti -1c
.RI "ViewerPosition \fBgetViewerPosition\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file DecompileData\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.DecompileData (Program program, Function function, ProgramLocation location, \fBDecompileResults\fP decompileResults, String errorMessage, File debugFile, ViewerPosition viewerPosition)\fC [inline]\fP"

.PP
Definition at line 41 of file DecompileData\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.contains (ProgramLocation programLocation)\fC [inline]\fP"

.PP
Definition at line 110 of file DecompileData\&.java\&.
.SS "\fBClangTokenGroup\fP ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getCCodeMarkup ()\fC [inline]\fP"

.PP
Definition at line 83 of file DecompileData\&.java\&.
.SS "File ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getDebugFile ()\fC [inline]\fP"

.PP
Definition at line 106 of file DecompileData\&.java\&.
.SS "\fBDecompileResults\fP ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getDecompileResults ()\fC [inline]\fP"

.PP
Definition at line 60 of file DecompileData\&.java\&.
.SS "String ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getErrorMessage ()\fC [inline]\fP"

.PP
Definition at line 90 of file DecompileData\&.java\&.
.SS "Function ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getFunction (void)\fC [inline]\fP"

.PP
Definition at line 68 of file DecompileData\&.java\&.
.SS "AddressSpace ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getFunctionSpace ()\fC [inline]\fP"

.PP
Definition at line 124 of file DecompileData\&.java\&.
.SS "HighFunction ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getHighFunction ()\fC [inline]\fP"

.PP
Definition at line 72 of file DecompileData\&.java\&.
.SS "ProgramLocation ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getLocation ()\fC [inline]\fP"

.PP
Definition at line 79 of file DecompileData\&.java\&.
.SS "Program ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getProgram ()\fC [inline]\fP"

.PP
Definition at line 64 of file DecompileData\&.java\&.
.SS "ViewerPosition ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.getViewerPosition ()\fC [inline]\fP"

.PP
Definition at line 128 of file DecompileData\&.java\&.
.SS "boolean ghidra\&.app\&.decompiler\&.component\&.DecompileData\&.hasDecompileResults ()\fC [inline]\fP"

.PP
Definition at line 53 of file DecompileData\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
