.TH "ghidra.app.plugin.core.decompile.actions.RenameVariableTask" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.RenameVariableTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenameVariableTask\fP (PluginTool \fBtool\fP, String old, HighFunction hfunc, \fBHighVariable\fP v, \fBVarnode\fP ex, SourceType st)"
.br
.ti -1c
.RI "void \fBcommit\fP ()  throws DuplicateNameException, InvalidInputException "
.br
.ti -1c
.RI "boolean \fBisValid\fP (String newNm)"
.br
.ti -1c
.RI "String \fBgetTransactionName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 28 of file RenameVariableTask\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableTask\&.RenameVariableTask (PluginTool tool, String old, HighFunction hfunc, \fBHighVariable\fP v, \fBVarnode\fP ex, SourceType st)\fC [inline]\fP"

.PP
Definition at line 38 of file RenameVariableTask\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableTask\&.commit () throws DuplicateNameException, InvalidInputException\fC [inline]\fP"

.PP
Definition at line 50 of file RenameVariableTask\&.java\&.
.SS "String ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableTask\&.getTransactionName ()\fC [inline]\fP"

.PP
Definition at line 96 of file RenameVariableTask\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.RenameVariableTask\&.isValid (String newNm)\fC [inline]\fP"

.PP
Definition at line 59 of file RenameVariableTask\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
