.TH "ghidra.app.decompiler.ClangBreak" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.ClangBreak
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.decompiler\&.ClangToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClangBreak\fP (\fBClangNode\fP par)"
.br
.ti -1c
.RI "\fBClangBreak\fP (\fBClangNode\fP par, int indent)"
.br
.ti -1c
.RI "int \fBgetIndent\fP ()"
.br
.ti -1c
.RI "void \fBrestoreFromXML\fP (XmlElement el, XmlElement end, PcodeFactory pfactory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file ClangBreak\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.ClangBreak\&.ClangBreak (\fBClangNode\fP par)\fC [inline]\fP"

.PP
Definition at line 27 of file ClangBreak\&.java\&.
.SS "ghidra\&.app\&.decompiler\&.ClangBreak\&.ClangBreak (\fBClangNode\fP par, int indent)\fC [inline]\fP"

.PP
Definition at line 32 of file ClangBreak\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int ghidra\&.app\&.decompiler\&.ClangBreak\&.getIndent ()\fC [inline]\fP"

.PP
Definition at line 37 of file ClangBreak\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.ClangBreak\&.restoreFromXML (XmlElement el, XmlElement end, PcodeFactory pfactory)\fC [inline]\fP"

.PP
Definition at line 40 of file ClangBreak\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
