.TH "ghidra.app.plugin.core.analysis" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.analysis
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConventionAnalysisDecompileConfigurer\fP"
.br
.ti -1c
.RI "class \fBDecompilerCallConventionAnalyzer\fP"
.br
.ti -1c
.RI "class \fBDecompilerFunctionAnalyzer\fP"
.br
.ti -1c
.RI "class \fBDecompilerSwitchAnalyzer\fP"
.br
.ti -1c
.RI "class \fBObjectiveC2_DecompilerMessageAnalyzer\fP"
.br
.ti -1c
.RI "class \fBSwitchAnalysisDecompileConfigurer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
