.TH "ghidra.app.decompiler.component.hover.FunctionSignatureDecompilerHover" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.hover.FunctionSignatureDecompilerHover
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractConfigurableHover, and \fBghidra\&.app\&.decompiler\&.component\&.hover\&.DecompilerHoverService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitializeOptions\fP ()"
.br
.ti -1c
.RI "void \fBsetOptions\fP (Options options, String optionName)"
.br
.ti -1c
.RI "JComponent \fBgetHoverComponent\fP (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionSignatureDecompilerHover\fP (PluginTool tool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A hover service to show tool tip text for hovering over a function name in the decompiler\&. The tooltip shows the function signature per the listing\&. 
.PP
Definition at line 45 of file FunctionSignatureDecompilerHover\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.decompiler\&.component\&.hover\&.FunctionSignatureDecompilerHover\&.FunctionSignatureDecompilerHover (PluginTool tool)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 53 of file FunctionSignatureDecompilerHover\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JComponent ghidra\&.app\&.decompiler\&.component\&.hover\&.FunctionSignatureDecompilerHover\&.getHoverComponent (Program program, ProgramLocation programLocation, FieldLocation fieldLocation, Field field)\fC [inline]\fP"

.PP
Definition at line 73 of file FunctionSignatureDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.FunctionSignatureDecompilerHover\&.initializeOptions ()\fC [inline]\fP"

.PP
Definition at line 58 of file FunctionSignatureDecompilerHover\&.java\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.hover\&.FunctionSignatureDecompilerHover\&.setOptions (Options options, String optionName)\fC [inline]\fP"

.PP
Definition at line 66 of file FunctionSignatureDecompilerHover\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
