.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_translate.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_translate.hh \- Class for fetching p-code from a Ghidra client\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'translate\&.hh'\fP
.br
\fC#include 'ghidra_arch\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGhidraTranslate\fP"
.br
.RI "An implementation of \fBTranslate\fP that queries a Ghidra client for p-code information\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class for fetching p-code from a Ghidra client\&. 


.PP
Definition in file \fBghidra_translate\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
