.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_context.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_context.hh \- Obtaining context information from a Ghidra client\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'globalcontext\&.hh'\fP
.br
\fC#include 'ghidra_arch\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContextGhidra\fP"
.br
.RI "An implementation of a \fBContextDatabase\fP obtaining context information via a Ghidra client\&. "
.in -1c
.SH "Detailed Description"
.PP 
Obtaining context information from a Ghidra client\&. 


.PP
Definition in file \fBghidra_context\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
