.TH "ghidra.app.plugin.core.decompile.AbstractDecompilerFindReferencesActionTest" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.AbstractDecompilerFindReferencesActionTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerTest\fP\&.
.PP
Inherited by \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerFindReferencesToActionTest\fP, and \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerFindReferencesToNestedStructureActionTest\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpyDataTypeReferenceFinder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()  throws Exception "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBassertFindAllReferencesToCompositeFieldWasCalled\fP ()"
.br
.ti -1c
.RI "void \fBassertFindAllReferencesToDataTypeWasCalled\fP ()"
.br
.ti -1c
.RI "ThreadedTableModel<?, ?> \fBperfomFindDataTypes\fP ()"
.br
.ti -1c
.RI "ThreadedTableModel<?, ?> \fBwaitForSearchProvider\fP ()"
.br
.ti -1c
.RI "ThreadedTableModel<?, ?> \fBgetTableModel\fP (LocationReferencesProvider referencesProvider)"
.br
.ti -1c
.RI "void \fBassertActionInPopup\fP ()"
.br
.ti -1c
.RI "void \fBassertActionNotInPopup\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "DockingActionIf \fBfindReferencesAction\fP"
.br
.ti -1c
.RI "\fBSpyDataTypeReferenceFinder\fP< DataTypeReferenceFinder > \fBspyReferenceFinder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.assertActionInPopup ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 100 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.assertActionNotInPopup ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 106 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.assertFindAllReferencesToCompositeFieldWasCalled ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 62 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.assertFindAllReferencesToDataTypeWasCalled ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 67 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "ThreadedTableModel<?, ?> ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.getTableModel (LocationReferencesProvider referencesProvider)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 94 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "ThreadedTableModel<?, ?> ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.perfomFindDataTypes ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 72 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.setUp () throws Exception\fC [inline]\fP"

.PP
Definition at line 47 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "ThreadedTableModel<?, ?> ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.waitForSearchProvider ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 83 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "DockingActionIf ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.findReferencesAction\fC [protected]\fP"

.PP
Definition at line 41 of file AbstractDecompilerFindReferencesActionTest\&.java\&.
.SS "\fBSpyDataTypeReferenceFinder\fP<DataTypeReferenceFinder> ghidra\&.app\&.plugin\&.core\&.decompile\&.AbstractDecompilerFindReferencesActionTest\&.spyReferenceFinder\fC [protected]\fP"

.PP
Definition at line 43 of file AbstractDecompilerFindReferencesActionTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
