.TH "ghidra.app.plugin.core.decompile.actions.CreateStructureVariableAction" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.actions.CreateStructureVariableAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits DockingAction\&.
.PP
Inherited by \fBghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.DecompilerStructureVariableAction\fP, and \fBghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.ListingStructureVariableAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateStructureVariableAction\fP (String owner, PluginTool tool, \fBDecompilerController\fP \fBcontroller\fP)"
.br
.ti -1c
.RI "abstract boolean \fBisEnabledForContext\fP (ActionContext context)"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionContext context)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBadjustCreateStructureMenuText\fP (DataType dt, boolean isThisParam)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "final \fBDecompilerController\fP \fBcontroller\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file CreateStructureVariableAction\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.CreateStructureVariableAction\&.CreateStructureVariableAction (String owner, PluginTool tool, \fBDecompilerController\fP controller)\fC [inline]\fP"

.PP
Definition at line 38 of file CreateStructureVariableAction\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.CreateStructureVariableAction\&.actionPerformed (ActionContext context)\fC [inline]\fP"

.PP
Definition at line 93 of file CreateStructureVariableAction\&.java\&.
.SS "void ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.CreateStructureVariableAction\&.adjustCreateStructureMenuText (DataType dt, boolean isThisParam)\fC [inline]\fP, \fC [protected]\fP"
Change the menu text for the create/fill structure action based on the current data type at the location and whether the location is for a 'this' parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdt\fP the current data type\&. 
.br
\fIisThisParam\fP true indicates the data type is for a 'this' parameter\&. 
.RE
.PP

.PP
Definition at line 68 of file CreateStructureVariableAction\&.java\&.
.SS "abstract boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.CreateStructureVariableAction\&.isEnabledForContext (ActionContext context)\fC [abstract]\fP"

.SH "Member Data Documentation"
.PP 
.SS "final \fBDecompilerController\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.actions\&.CreateStructureVariableAction\&.controller\fC [protected]\fP"

.PP
Definition at line 35 of file CreateStructureVariableAction\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
