.TH "ghidra.app.decompiler.component.DecompilerCallbackHandler" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.decompiler.component.DecompilerCallbackHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP, and \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdecompileDataChanged\fP (\fBDecompileData\fP decompileData)"
.br
.ti -1c
.RI "void \fBcontextChanged\fP ()"
.br
.ti -1c
.RI "void \fBsetStatusMessage\fP (String message)"
.br
.ti -1c
.RI "void \fBlocationChanged\fP (ProgramLocation programLocation)"
.br
.ti -1c
.RI "void \fBselectionChanged\fP (ProgramSelection programSelection)"
.br
.ti -1c
.RI "void \fBannotationClicked\fP (AnnotatedTextFieldElement annotation, boolean newWindow)"
.br
.ti -1c
.RI "void \fBgoToLabel\fP (String labelName, boolean newWindow)"
.br
.ti -1c
.RI "void \fBgoToAddress\fP (\fBAddress\fP addr, boolean newWindow)"
.br
.ti -1c
.RI "void \fBgoToScalar\fP (long value, boolean newWindow)"
.br
.ti -1c
.RI "void \fBexportLocation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file DecompilerCallbackHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.annotationClicked (AnnotatedTextFieldElement annotation, boolean newWindow)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.contextChanged ()"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.decompileDataChanged (\fBDecompileData\fP decompileData)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.exportLocation ()"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.goToAddress (\fBAddress\fP addr, boolean newWindow)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.goToLabel (String labelName, boolean newWindow)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.goToScalar (long value, boolean newWindow)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.locationChanged (ProgramLocation programLocation)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.selectionChanged (ProgramSelection programSelection)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.
.SS "void ghidra\&.app\&.decompiler\&.component\&.DecompilerCallbackHandler\&.setStatusMessage (String message)"

.PP
Implemented in \fBghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerProvider\fP, and \fBghidra\&.app\&.decompiler\&.component\&.CDisplayPanel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
