.TH "ghidra.app.plugin.core.decompile.DecompilerActionContext" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ghidra.app.plugin.core.decompile.DecompilerActionContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits NavigatableActionContext, and RestrictedAddressSetContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecompilerActionContext\fP (\fBDecompilerProvider\fP provider, \fBAddress\fP functionEntryPoint, boolean isDecompiling)"
.br
.ti -1c
.RI "\fBAddress\fP \fBgetFunctionEntryPoint\fP ()"
.br
.ti -1c
.RI "boolean \fBisDecompiling\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file DecompilerActionContext\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerActionContext\&.DecompilerActionContext (\fBDecompilerProvider\fP provider, \fBAddress\fP functionEntryPoint, boolean isDecompiling)\fC [inline]\fP"

.PP
Definition at line 28 of file DecompilerActionContext\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAddress\fP ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerActionContext\&.getFunctionEntryPoint ()\fC [inline]\fP"

.PP
Definition at line 35 of file DecompilerActionContext\&.java\&.
.SS "boolean ghidra\&.app\&.plugin\&.core\&.decompile\&.DecompilerActionContext\&.isDecompiling ()\fC [inline]\fP"

.PP
Definition at line 39 of file DecompilerActionContext\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
