.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/globalcontext.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/globalcontext.hh \- Utilities for getting address-based context to the disassembler and decompiler\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pcoderaw\&.hh'\fP
.br
\fC#include 'partmap\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContextBitRange\fP"
.br
.RI "Description of a context variable within the disassembly context \fIblob\fP\&. "
.ti -1c
.RI "struct \fBTrackedContext\fP"
.br
.RI "A tracked register (\fBVarnode\fP) and the value it contains\&. "
.ti -1c
.RI "class \fBContextDatabase\fP"
.br
.RI "An interface to a database of disassembly/decompiler \fBcontext\fP information\&. "
.ti -1c
.RI "class \fBContextInternal\fP"
.br
.RI "An in-memory implementation of the \fBContextDatabase\fP interface\&. "
.ti -1c
.RI "class \fBContextCache\fP"
.br
.RI "A helper class for caching the active context blob to minimize database lookups\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< \fBTrackedContext\fP > \fBTrackedSet\fP"
.br
.RI "A set of tracked registers and their values (at one code point) "
.in -1c
.SH "Detailed Description"
.PP 
Utilities for getting address-based context to the disassembler and decompiler\&. 


.PP
Definition in file \fBglobalcontext\&.hh\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef vector<\fBTrackedContext\fP> \fBTrackedSet\fP"

.PP
A set of tracked registers and their values (at one code point) 
.PP
Definition at line 74 of file globalcontext\&.hh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
