.TH "HandleTpl" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HandleTpl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <semantics\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHandleTpl\fP (void)"
.br
.ti -1c
.RI "\fBHandleTpl\fP (const \fBVarnodeTpl\fP *vn)"
.br
.ti -1c
.RI "\fBHandleTpl\fP (const \fBConstTpl\fP &spc, const \fBConstTpl\fP &sz, const \fBVarnodeTpl\fP *vn, \fBAddrSpace\fP *t_space, \fBuintb\fP t_offset)"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetSpace\fP (void) const"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetPtrSpace\fP (void) const"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetPtrOffset\fP (void) const"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetPtrSize\fP (void) const"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetSize\fP (void) const"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetTempSpace\fP (void) const"
.br
.ti -1c
.RI "const \fBConstTpl\fP & \fBgetTempOffset\fP (void) const"
.br
.ti -1c
.RI "void \fBsetSize\fP (const \fBConstTpl\fP &sz)"
.br
.ti -1c
.RI "void \fBsetPtrSize\fP (const \fBConstTpl\fP &sz)"
.br
.ti -1c
.RI "void \fBsetPtrOffset\fP (\fBuintb\fP val)"
.br
.ti -1c
.RI "void \fBsetTempOffset\fP (\fBuintb\fP val)"
.br
.ti -1c
.RI "void \fBfix\fP (\fBFixedHandle\fP &hand, const \fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "void \fBchangeHandleIndex\fP (const vector< int4 > &handmap)"
.br
.ti -1c
.RI "void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "void \fBrestoreXml\fP (const \fBElement\fP *el, const \fBAddrSpaceManager\fP *manage)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file semantics\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HandleTpl::HandleTpl (void)\fC [inline]\fP"

.PP
Definition at line 116 of file semantics\&.hh\&.
.SS "HandleTpl::HandleTpl (const \fBVarnodeTpl\fP * vn)"

.PP
Definition at line 568 of file semantics\&.cc\&.
.SS "HandleTpl::HandleTpl (const \fBConstTpl\fP & spc, const \fBConstTpl\fP & sz, const \fBVarnodeTpl\fP * vn, \fBAddrSpace\fP * t_space, \fBuintb\fP t_offset)"

.PP
Definition at line 577 of file semantics\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void HandleTpl::changeHandleIndex (const vector< int4 > & handmap)"

.PP
Definition at line 613 of file semantics\&.cc\&.
.SS "void HandleTpl::fix (\fBFixedHandle\fP & hand, const \fBParserWalker\fP & walker) const"

.PP
Definition at line 584 of file semantics\&.cc\&.
.SS "const \fBConstTpl\fP& HandleTpl::getPtrOffset (void) const\fC [inline]\fP"

.PP
Definition at line 122 of file semantics\&.hh\&.
.SS "const \fBConstTpl\fP& HandleTpl::getPtrSize (void) const\fC [inline]\fP"

.PP
Definition at line 123 of file semantics\&.hh\&.
.SS "const \fBConstTpl\fP& HandleTpl::getPtrSpace (void) const\fC [inline]\fP"

.PP
Definition at line 121 of file semantics\&.hh\&.
.SS "const \fBConstTpl\fP& HandleTpl::getSize (void) const\fC [inline]\fP"

.PP
Definition at line 124 of file semantics\&.hh\&.
.SS "const \fBConstTpl\fP& HandleTpl::getSpace (void) const\fC [inline]\fP"

.PP
Definition at line 120 of file semantics\&.hh\&.
.SS "const \fBConstTpl\fP& HandleTpl::getTempOffset (void) const\fC [inline]\fP"

.PP
Definition at line 126 of file semantics\&.hh\&.
.SS "const \fBConstTpl\fP& HandleTpl::getTempSpace (void) const\fC [inline]\fP"

.PP
Definition at line 125 of file semantics\&.hh\&.
.SS "void HandleTpl::restoreXml (const \fBElement\fP * el, const \fBAddrSpaceManager\fP * manage)"

.PP
Definition at line 639 of file semantics\&.cc\&.
.SS "void HandleTpl::saveXml (ostream & s) const"

.PP
Definition at line 625 of file semantics\&.cc\&.
.SS "void HandleTpl::setPtrOffset (\fBuintb\fP val)\fC [inline]\fP"

.PP
Definition at line 129 of file semantics\&.hh\&.
.SS "void HandleTpl::setPtrSize (const \fBConstTpl\fP & sz)\fC [inline]\fP"

.PP
Definition at line 128 of file semantics\&.hh\&.
.SS "void HandleTpl::setSize (const \fBConstTpl\fP & sz)\fC [inline]\fP"

.PP
Definition at line 127 of file semantics\&.hh\&.
.SS "void HandleTpl::setTempOffset (\fBuintb\fP val)\fC [inline]\fP"

.PP
Definition at line 130 of file semantics\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
