.TH "HeritageInfo" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeritageInfo \- Information about heritage passes performed for a specific address space\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <heritage\&.hh>\fP
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBHeritage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about heritage passes performed for a specific address space\&. 

For a particular address space, this keeps track of:
.IP "\(bu" 2
how long to delay heritage
.IP "\(bu" 2
how long to delay dead code removal
.IP "\(bu" 2
whether dead code has been removed (for this space)
.IP "\(bu" 2
have warnings been issued 
.PP

.PP
Definition at line 84 of file heritage\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBHeritage\fP\fC [friend]\fP"

.PP
Definition at line 85 of file heritage\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
