.TH "HighEdge" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HighEdge \- A record for caching a \fBCover\fP intersection test between two \fBHighVariable\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <merge\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBHighEdge\fP &op2) const"
.br
.RI "Comparator\&. "
.ti -1c
.RI "\fBHighEdge\fP (\fBHighVariable\fP *c, \fBHighVariable\fP *d)"
.br
.RI "\fBConstructor\fP\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMerge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A record for caching a \fBCover\fP intersection test between two \fBHighVariable\fP objects\&. 

This is just a pair of \fBHighVariable\fP objects that can be used as a map key\&. The main \fBMerge\fP class uses it to cache intersection test results between the two variables in a map\&. 
.PP
Definition at line 29 of file merge\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HighEdge::HighEdge (\fBHighVariable\fP * c, \fBHighVariable\fP * d)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 36 of file merge\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool HighEdge::operator< (const \fBHighEdge\fP & op2) const\fC [inline]\fP"

.PP
Comparator\&. 
.PP
Definition at line 35 of file merge\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBMerge\fP\fC [friend]\fP"

.PP
Definition at line 30 of file merge\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
