.TH "IfaceBaseCommand" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfaceBaseCommand
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface\&.hh>\fP
.PP
Inherits \fBIfaceCommand\fP\&.
.PP
Inherited by \fBIfcClosefile\fP, \fBIfcEcho\fP, \fBIfcHistory\fP, \fBIfcOpenfile\fP, \fBIfcOpenfileAppend\fP, and \fBIfcQuit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetData\fP (\fBIfaceStatus\fP *root, \fBIfaceData\fP *data)"
.br
.ti -1c
.RI "virtual string \fBgetModule\fP (void) const"
.br
.ti -1c
.RI "virtual \fBIfaceData\fP * \fBcreateData\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBIfaceStatus\fP * \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 156 of file interface\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBIfaceData\fP* IfaceBaseCommand::createData (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIfaceCommand\fP\&.
.PP
Definition at line 162 of file interface\&.hh\&.
.SS "virtual string IfaceBaseCommand::getModule (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIfaceCommand\fP\&.
.PP
Definition at line 161 of file interface\&.hh\&.
.SS "virtual void IfaceBaseCommand::setData (\fBIfaceStatus\fP * root, \fBIfaceData\fP * data)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBIfaceCommand\fP\&.
.PP
Definition at line 160 of file interface\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBIfaceStatus\fP* IfaceBaseCommand::status\fC [protected]\fP"

.PP
Definition at line 158 of file interface\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
