.TH "IfaceCodeDataCapability" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfaceCodeDataCapability
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <codedata\&.hh>\fP
.PP
Inherits \fBIfaceCapability\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBregisterCommands\fP (\fBIfaceStatus\fP *status)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file codedata\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void IfaceCodeDataCapability::registerCommands (\fBIfaceStatus\fP * status)\fC [virtual]\fP"

.PP
Implements \fBIfaceCapability\fP\&.
.PP
Definition at line 30 of file codedata\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
