.TH "IfaceTerm" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfaceTerm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifaceterm\&.hh>\fP
.PP
Inherits \fBIfaceStatus\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIfaceTerm\fP (const string &prmpt, istream &is, ostream &os)"
.br
.ti -1c
.RI "virtual \fB~IfaceTerm\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file ifaceterm\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IfaceTerm::IfaceTerm (const string & prmpt, istream & is, ostream & os)"

.PP
Definition at line 18 of file ifaceterm\&.cc\&.
.SS "IfaceTerm::~IfaceTerm (void)\fC [virtual]\fP"

.PP
Definition at line 50 of file ifaceterm\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
