.TH "IfaceError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfaceError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface\&.hh>\fP
.PP
Inherited by \fBIfaceExecutionError\fP, and \fBIfaceParseError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIfaceError\fP (const string &s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBexplain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file interface\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IfaceError::IfaceError (const string & s)\fC [inline]\fP"

.PP
Definition at line 49 of file interface\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "string IfaceError::explain"

.PP
Definition at line 48 of file interface\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
