.TH "IfaceData" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfaceData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface\&.hh>\fP
.PP
Inherited by \fBCodeDataAnalysis\fP, and \fBIfaceDecompData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IfaceData\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file interface\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual IfaceData::~IfaceData (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 64 of file interface\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
