.TH "IfaceDecompData" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfaceDecompData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifacedecomp\&.hh>\fP
.PP
Inherits \fBIfaceData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstorePrototypePieces\fP (\fBFuncdata\fP *fd_in, \fBPrototypePieces\fP pp_in)"
.br
.ti -1c
.RI "\fBPrototypePieces\fP \fBfindPrototypePieces\fP (\fBFuncdata\fP *fd_in)"
.br
.ti -1c
.RI "\fBIfaceDecompData\fP (void)"
.br
.ti -1c
.RI "virtual \fB~IfaceDecompData\fP (void)"
.br
.ti -1c
.RI "void \fBabortFunction\fP (ostream &s)"
.br
.ti -1c
.RI "void \fBclearArchitecture\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFuncdata\fP * \fBfd\fP"
.br
.ti -1c
.RI "\fBArchitecture\fP * \fBconf\fP"
.br
.ti -1c
.RI "\fBCallGraph\fP * \fBcgraph\fP"
.br
.ti -1c
.RI "map< \fBFuncdata\fP *, \fBPrototypePieces\fP > \fBprototypePieces\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file ifacedecomp\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IfaceDecompData::IfaceDecompData (void)"

.PP
Definition at line 205 of file ifacedecomp\&.cc\&.
.SS "IfaceDecompData::~IfaceDecompData (void)\fC [virtual]\fP"

.PP
Definition at line 216 of file ifacedecomp\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void IfaceDecompData::abortFunction (ostream & s)"

.PP
Definition at line 226 of file ifacedecomp\&.cc\&.
.SS "void IfaceDecompData::clearArchitecture (void)"

.PP
Definition at line 235 of file ifacedecomp\&.cc\&.
.SS "\fBPrototypePieces\fP IfaceDecompData::findPrototypePieces (\fBFuncdata\fP * fd_in)\fC [inline]\fP"

.PP
Definition at line 47 of file ifacedecomp\&.hh\&.
.SS "void IfaceDecompData::storePrototypePieces (\fBFuncdata\fP * fd_in, \fBPrototypePieces\fP pp_in)\fC [inline]\fP"

.PP
Definition at line 46 of file ifacedecomp\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCallGraph\fP* IfaceDecompData::cgraph"

.PP
Definition at line 43 of file ifacedecomp\&.hh\&.
.SS "\fBArchitecture\fP* IfaceDecompData::conf"

.PP
Definition at line 42 of file ifacedecomp\&.hh\&.
.SS "\fBFuncdata\fP* IfaceDecompData::fd"

.PP
Definition at line 41 of file ifacedecomp\&.hh\&.
.SS "map<\fBFuncdata\fP*,\fBPrototypePieces\fP> IfaceDecompData::prototypePieces"

.PP
Definition at line 45 of file ifacedecomp\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
