.TH "IfcCallGraphBuildQuick" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfcCallGraphBuildQuick
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifacedecomp\&.hh>\fP
.PP
Inherits \fBIfcCallGraphBuild\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 482 of file ifacedecomp\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
