.TH "IfcGraphControlflow" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IfcGraphControlflow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ifacedecomp\&.hh>\fP
.PP
Inherits \fBIfaceDecompCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBexecute\fP (istream &s)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 448 of file ifacedecomp\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void IfcGraphControlflow::execute (istream & s)\fC [virtual]\fP"

.PP
Implements \fBIfaceCommand\fP\&.
.PP
Definition at line 1937 of file ifacedecomp\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
