.TH "ImportRecord" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportRecord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loadimage_bfd\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdllname\fP"
.br
.ti -1c
.RI "string \fBfuncname\fP"
.br
.ti -1c
.RI "int \fBordinal\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBaddress\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBthunkaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file loadimage_bfd\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAddress\fP ImportRecord::address"

.PP
Definition at line 30 of file loadimage_bfd\&.hh\&.
.SS "string ImportRecord::dllname"

.PP
Definition at line 27 of file loadimage_bfd\&.hh\&.
.SS "string ImportRecord::funcname"

.PP
Definition at line 28 of file loadimage_bfd\&.hh\&.
.SS "int ImportRecord::ordinal"

.PP
Definition at line 29 of file loadimage_bfd\&.hh\&.
.SS "\fBAddress\fP ImportRecord::thunkaddress"

.PP
Definition at line 31 of file loadimage_bfd\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
