.TH "InjectCallfixupGhidra" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InjectCallfixupGhidra \- A call-fixup injection that uses a Ghidra client to generate the p-code ops\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inject_ghidra\&.hh>\fP
.PP
Inherits \fBInjectPayloadGhidra\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInjectCallfixupGhidra\fP (const string &src, const string &nm)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A call-fixup injection that uses a Ghidra client to generate the p-code ops\&. 
.PP
Definition at line 50 of file inject_ghidra\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InjectCallfixupGhidra::InjectCallfixupGhidra (const string & src, const string & nm)"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 78 of file inject_ghidra\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void InjectCallfixupGhidra::restoreXml (const \fBElement\fP * el)\fC [virtual]\fP"

.PP
Reimplemented from \fBInjectPayloadGhidra\fP\&.
.PP
Definition at line 83 of file inject_ghidra\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
