.TH "InjectPayloadDynamic" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InjectPayloadDynamic
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inject_sleigh\&.hh>\fP
.PP
Inherits InjectPayload\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInjectPayloadDynamic\fP (\fBArchitecture\fP *g, const string &nm, int4 tp)"
.br
.ti -1c
.RI "virtual \fB~InjectPayloadDynamic\fP (void)"
.br
.ti -1c
.RI "void \fBrestoreEntry\fP (const \fBElement\fP *el)"
.br
.ti -1c
.RI "virtual void \fBinject\fP (\fBInjectContext\fP &context, \fBPcodeEmit\fP &emit) const"
.br
.ti -1c
.RI "virtual void \fBprintTemplate\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual string \fBgetSource\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file inject_sleigh\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InjectPayloadDynamic::InjectPayloadDynamic (\fBArchitecture\fP * g, const string & nm, int4 tp)\fC [inline]\fP"

.PP
Definition at line 81 of file inject_sleigh\&.hh\&.
.SS "InjectPayloadDynamic::~InjectPayloadDynamic (void)\fC [virtual]\fP"

.PP
Definition at line 238 of file inject_sleigh\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual string InjectPayloadDynamic::getSource (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 86 of file inject_sleigh\&.hh\&.
.SS "void InjectPayloadDynamic::inject (\fBInjectContext\fP & context, \fBPcodeEmit\fP & emit) const\fC [virtual]\fP"

.PP
Definition at line 268 of file inject_sleigh\&.cc\&.
.SS "virtual void InjectPayloadDynamic::printTemplate (ostream & s) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 85 of file inject_sleigh\&.hh\&.
.SS "void InjectPayloadDynamic::restoreEntry (const \fBElement\fP * el)"

.PP
Definition at line 246 of file inject_sleigh\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
