.TH "InjectedUserOp" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InjectedUserOp \- A user defined operation that is injected with other p-code\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <userop\&.hh>\fP
.PP
Inherits \fBUserPcodeOp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInjectedUserOp\fP (\fBArchitecture\fP *g, const string &nm, int4 ind, int4 injid)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "uint4 \fBgetInjectId\fP (void) const"
.br
.RI "Get the id of the injection object\&. "
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el)"
.br
.RI "Restore the detailed description from an XML stream\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A user defined operation that is injected with other p-code\&. 

The system can configure user defined p-code ops as a hook point within the control-flow where other p-code is injected during analysis\&. This class maps the raw CALLOTHER p-code op, via its constant id, to its injection object\&. The injection object is also referenced by an id and is managed by \fBPcodeInjectLibrary\fP\&. 
.PP
Definition at line 83 of file userop\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InjectedUserOp::InjectedUserOp (\fBArchitecture\fP * g, const string & nm, int4 ind, int4 injid)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 86 of file userop\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "uint4 InjectedUserOp::getInjectId (void) const\fC [inline]\fP"

.PP
Get the id of the injection object\&. 
.PP
Definition at line 88 of file userop\&.hh\&.
.SS "void InjectedUserOp::restoreXml (const \fBElement\fP * el)\fC [virtual]\fP"

.PP
Restore the detailed description from an XML stream\&. The details of how a user defined operation behaves can be dynamically configured from an XML tag\&. 
.PP
\fBParameters:\fP
.RS 4
\fIel\fP is the root XML element describing the op 
.RE
.PP

.PP
Implements \fBUserPcodeOp\fP\&.
.PP
Definition at line 19 of file userop\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
