.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/interface.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/interface.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'capability\&.hh'\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIfaceError\fP"
.br
.ti -1c
.RI "struct \fBIfaceParseError\fP"
.br
.ti -1c
.RI "struct \fBIfaceExecutionError\fP"
.br
.ti -1c
.RI "class \fBIfaceData\fP"
.br
.ti -1c
.RI "class \fBIfaceCommand\fP"
.br
.ti -1c
.RI "class \fBIfaceCommandDummy\fP"
.br
.ti -1c
.RI "class \fBIfaceCapability\fP"
.br
.ti -1c
.RI "class \fBIfaceStatus\fP"
.br
.ti -1c
.RI "class \fBIfaceBaseCommand\fP"
.br
.ti -1c
.RI "class \fBIfcQuit\fP"
.br
.ti -1c
.RI "class \fBIfcHistory\fP"
.br
.ti -1c
.RI "class \fBIfcOpenfile\fP"
.br
.ti -1c
.RI "class \fBIfcOpenfileAppend\fP"
.br
.ti -1c
.RI "class \fBIfcClosefile\fP"
.br
.ti -1c
.RI "class \fBIfcEcho\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcompare_ifacecommand\fP (const \fBIfaceCommand\fP *a, const \fBIfaceCommand\fP *b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool compare_ifacecommand (const \fBIfaceCommand\fP * a, const \fBIfaceCommand\fP * b)\fC [inline]\fP"

.PP
Definition at line 92 of file interface\&.hh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
