.TH "JoinRecordCompare" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JoinRecordCompare \- Comparator for \fBJoinRecord\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <translate\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBJoinRecord\fP *a, const \fBJoinRecord\fP *b) const"
.br
.RI "Compare to JoinRecords using their built-in comparison\&. "
.in -1c
.SH "Detailed Description"
.PP 
Comparator for \fBJoinRecord\fP objects\&. 
.PP
Definition at line 203 of file translate\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool JoinRecordCompare::operator() (const \fBJoinRecord\fP * a, const \fBJoinRecord\fP * b) const\fC [inline]\fP"

.PP
Compare to JoinRecords using their built-in comparison\&. 
.PP
Definition at line 204 of file translate\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
