.TH "JumpBasic2" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JumpBasic2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jumptable\&.hh>\fP
.PP
Inherits \fBJumpBasic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJumpBasic2\fP (\fBJumpTable\fP *jt)"
.br
.ti -1c
.RI "void \fBinitializeStart\fP (const \fBPathMeld\fP &\fBpathMeld\fP)"
.br
.ti -1c
.RI "virtual bool \fBrecoverModel\fP (\fBFuncdata\fP *fd, \fBPcodeOp\fP *indop, uint4 matchsize, uint4 maxtablesize)"
.br
.ti -1c
.RI "virtual void \fBfindUnnormalized\fP (uint4 maxaddsub, uint4 maxleftright, uint4 maxext)"
.br
.ti -1c
.RI "virtual \fBJumpModel\fP * \fBclone\fP (\fBJumpTable\fP *jt) const"
.br
.ti -1c
.RI "virtual void \fBclear\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 269 of file jumptable\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JumpBasic2::JumpBasic2 (\fBJumpTable\fP * jt)\fC [inline]\fP"

.PP
Definition at line 275 of file jumptable\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void JumpBasic2::clear (void)\fC [virtual]\fP"

.PP
Reimplemented from \fBJumpBasic\fP\&.
.PP
Definition at line 1420 of file jumptable\&.cc\&.
.SS "\fBJumpModel\fP * JumpBasic2::clone (\fBJumpTable\fP * jt) const\fC [virtual]\fP"

.PP
Reimplemented from \fBJumpBasic\fP\&.
.PP
Definition at line 1412 of file jumptable\&.cc\&.
.SS "void JumpBasic2::findUnnormalized (uint4 maxaddsub, uint4 maxleftright, uint4 maxext)\fC [virtual]\fP"

.PP
Reimplemented from \fBJumpBasic\fP\&.
.PP
Definition at line 1392 of file jumptable\&.cc\&.
.SS "void JumpBasic2::initializeStart (const \fBPathMeld\fP & pathMeld)"

.PP
Definition at line 1314 of file jumptable\&.cc\&.
.SS "bool JumpBasic2::recoverModel (\fBFuncdata\fP * fd, \fBPcodeOp\fP * indop, uint4 matchsize, uint4 maxtablesize)\fC [virtual]\fP"

.PP
Reimplemented from \fBJumpBasic\fP\&.
.PP
Definition at line 1325 of file jumptable\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
