.TH "JumptableThunkError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JumptableThunkError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jumptable\&.hh>\fP
.PP
Inherits \fBLowlevelError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJumptableThunkError\fP (const string &s)"
.br
.RI "Initialize the error with an explanatory string\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file jumptable\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JumptableThunkError::JumptableThunkError (const string & s)\fC [inline]\fP"

.PP
Initialize the error with an explanatory string\&. 
.PP
Definition at line 28 of file jumptable\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
