.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/jumptable.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/jumptable.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'emulateutil\&.hh'\fP
.br
\fC#include 'rangeutil\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBJumptableThunkError\fP"
.br
.ti -1c
.RI "struct \fBJumptableNotReachableError\fP"
.br
.ti -1c
.RI "class \fBLoadTable\fP"
.br
.ti -1c
.RI "class \fBPathMeld\fP"
.br
.ti -1c
.RI "class \fBEmulateFunction\fP"
.br
.ti -1c
.RI "class \fBGuardRecord\fP"
.br
.ti -1c
.RI "class \fBJumpValues\fP"
.br
.ti -1c
.RI "class \fBJumpValuesRange\fP"
.br
.ti -1c
.RI "class \fBJumpValuesRangeDefault\fP"
.br
.ti -1c
.RI "class \fBJumpModel\fP"
.br
.ti -1c
.RI "class \fBJumpModelTrivial\fP"
.br
.ti -1c
.RI "class \fBJumpBasic\fP"
.br
.ti -1c
.RI "class \fBJumpBasic2\fP"
.br
.ti -1c
.RI "class \fBJumpBasicOverride\fP"
.br
.ti -1c
.RI "class \fBJumpAssisted\fP"
.br
.ti -1c
.RI "class \fBJumpTable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
