.TH "LabSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LabSymbol \- A \fBSymbol\fP that labels code internal to a function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <database\&.hh>\fP
.PP
Inherits Symbol\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLabSymbol\fP (\fBScope\fP *sc, const string &nm)"
.br
.RI "Construct given name\&. "
.ti -1c
.RI "\fBLabSymbol\fP (\fBScope\fP *sc)"
.br
.RI "\fBConstructor\fP for use with restoreXml\&. "
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBSymbol\fP that labels code internal to a function\&. 
.PP
Definition at line 264 of file database\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LabSymbol::LabSymbol (\fBScope\fP * sc, const string & nm)"

.PP
Construct given name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsc\fP is the \fBScope\fP that will contain the new \fBSymbol\fP 
.br
\fInm\fP is the name of the new \fBSymbol\fP 
.RE
.PP

.PP
Definition at line 552 of file database\&.cc\&.
.SS "LabSymbol::LabSymbol (\fBScope\fP * sc)"

.PP
\fBConstructor\fP for use with restoreXml\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsc\fP is the \fBScope\fP that will contain the new \fBSymbol\fP 
.RE
.PP

.PP
Definition at line 560 of file database\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void LabSymbol::restoreXml (const \fBElement\fP * el)\fC [virtual]\fP"

.PP
Definition at line 574 of file database\&.cc\&.
.SS "void LabSymbol::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Definition at line 566 of file database\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
