.TH "LessConstForm" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LessConstForm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <double\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBapplyRule\fP (\fBSplitVarnode\fP &i, \fBPcodeOp\fP *op, bool workishi, \fBFuncdata\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 210 of file double\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool LessConstForm::applyRule (\fBSplitVarnode\fP & i, \fBPcodeOp\fP * op, bool workishi, \fBFuncdata\fP & data)"

.PP
Definition at line 2244 of file double\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
