.TH "LessEquation" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LessEquation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBValExpressEquation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLessEquation\fP (\fBPatternValue\fP *l, \fBPatternExpression\fP *r)"
.br
.ti -1c
.RI "virtual void \fBgenPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 392 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LessEquation::LessEquation (\fBPatternValue\fP * l, \fBPatternExpression\fP * r)\fC [inline]\fP"

.PP
Definition at line 394 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void LessEquation::genPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [virtual]\fP"

.PP
Implements \fBPatternEquation\fP\&.
.PP
Definition at line 1313 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
