.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/libdecomp.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/libdecomp.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'architecture\&.hh'\fP
.br
\fC#include 'sleigh_arch\&.hh'\fP
.br
\fC#include 'ifacedecomp\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstartDecompilerLibrary\fP (const char *sleighhome)"
.br
.ti -1c
.RI "void \fBstartDecompilerLibrary\fP (const vector< string > &extrapaths)"
.br
.ti -1c
.RI "void \fBstartDecompilerLibrary\fP (const char *sleighhome, const vector< string > &extrapaths)"
.br
.ti -1c
.RI "void \fBshutdownDecompilerLibrary\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void shutdownDecompilerLibrary (void)"

.PP
Definition at line 51 of file libdecomp\&.cc\&.
.SS "void startDecompilerLibrary (const char * sleighhome)"

.PP
Definition at line 18 of file libdecomp\&.cc\&.
.SS "void startDecompilerLibrary (const vector< string > & extrapaths)"

.PP
Definition at line 28 of file libdecomp\&.cc\&.
.SS "void startDecompilerLibrary (const char * sleighhome, const vector< string > & extrapaths)"

.PP
Definition at line 38 of file libdecomp\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
