.TH "LoadTable" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jumptable\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadTable\fP (void)"
.br
.ti -1c
.RI "\fBLoadTable\fP (const \fBAddress\fP &ad, int4 sz)"
.br
.ti -1c
.RI "\fBLoadTable\fP (const \fBAddress\fP &ad, int4 sz, int4 nm)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBLoadTable\fP &op2) const"
.br
.ti -1c
.RI "void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "void \fBrestoreXml\fP (const \fBElement\fP *el, \fBArchitecture\fP *glb)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcollapseTable\fP (vector< \fBLoadTable\fP > &table)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEmulateFunction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file jumptable\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoadTable::LoadTable (void)\fC [inline]\fP"

.PP
Definition at line 41 of file jumptable\&.hh\&.
.SS "LoadTable::LoadTable (const \fBAddress\fP & ad, int4 sz)\fC [inline]\fP"

.PP
Definition at line 42 of file jumptable\&.hh\&.
.SS "LoadTable::LoadTable (const \fBAddress\fP & ad, int4 sz, int4 nm)\fC [inline]\fP"

.PP
Definition at line 43 of file jumptable\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void LoadTable::collapseTable (vector< \fBLoadTable\fP > & table)\fC [static]\fP"

.PP
Definition at line 45 of file jumptable\&.cc\&.
.SS "bool LoadTable::operator< (const \fBLoadTable\fP & op2) const\fC [inline]\fP"

.PP
Definition at line 44 of file jumptable\&.hh\&.
.SS "void LoadTable::restoreXml (const \fBElement\fP * el, \fBArchitecture\fP * glb)"

.PP
Definition at line 31 of file jumptable\&.cc\&.
.SS "void LoadTable::saveXml (ostream & s) const"

.PP
Definition at line 20 of file jumptable\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBEmulateFunction\fP\fC [friend]\fP"

.PP
Definition at line 36 of file jumptable\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
