.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/loadimage.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/loadimage.hh \- Classes and API for accessing a binary load image\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'address\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDataUnavailError\fP"
.br
.RI "Exception indicating data was not available\&. "
.ti -1c
.RI "struct \fBLoadImageFunc\fP"
.br
.RI "A record indicating a function symbol\&. "
.ti -1c
.RI "struct \fBLoadImageSection\fP"
.br
.RI "A record describing a section bytes in the executable\&. "
.ti -1c
.RI "class \fBLoadImage\fP"
.br
.RI "An interface into a particular binary executable image\&. "
.ti -1c
.RI "class \fBRawLoadImage\fP"
.br
.RI "A simple raw binary loadimage\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classes and API for accessing a binary load image\&. 


.PP
Definition in file \fBloadimage\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
