.TH "LoadImageFunc" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadImageFunc \- A record indicating a function symbol\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loadimage\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAddress\fP \fBaddress\fP"
.br
.RI "Start of function\&. "
.ti -1c
.RI "string \fBname\fP"
.br
.RI "Name of function\&. "
.in -1c
.SH "Detailed Description"
.PP 
A record indicating a function symbol\&. 

This is a lightweight object holding the \fBAddress\fP and name of a function 
.PP
Definition at line 36 of file loadimage\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAddress\fP LoadImageFunc::address"

.PP
Start of function\&. 
.PP
Definition at line 37 of file loadimage\&.hh\&.
.SS "string LoadImageFunc::name"

.PP
Name of function\&. 
.PP
Definition at line 38 of file loadimage\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
