.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/loadimage_ghidra.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/loadimage_ghidra.hh \- Use the Ghidra client as a load image\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'loadimage\&.hh'\fP
.br
\fC#include 'ghidra_arch\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoadImageGhidra\fP"
.br
.RI "An implementation of the \fBLoadImage\fP interface using a Ghidra client as the back-end\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use the Ghidra client as a load image\&. 


.PP
Definition in file \fBloadimage_ghidra\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
