.TH "LogicalForm" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogicalForm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <double\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBverify\fP (\fBVarnode\fP *h, \fBVarnode\fP *l, \fBPcodeOp\fP *lop)"
.br
.ti -1c
.RI "bool \fBapplyRule\fP (\fBSplitVarnode\fP &i, \fBPcodeOp\fP *lop, bool workishi, \fBFuncdata\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file double\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool LogicalForm::applyRule (\fBSplitVarnode\fP & i, \fBPcodeOp\fP * lop, bool workishi, \fBFuncdata\fP & data)"

.PP
Definition at line 1489 of file double\&.cc\&.
.SS "bool LogicalForm::verify (\fBVarnode\fP * h, \fBVarnode\fP * l, \fBPcodeOp\fP * lop)"

.PP
Definition at line 1471 of file double\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
