.TH "MacroSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MacroSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSleighSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMacroSymbol\fP (const string &nm, int4 i)"
.br
.ti -1c
.RI "int4 \fBgetIndex\fP (void) const"
.br
.ti -1c
.RI "void \fBsetConstruct\fP (\fBConstructTpl\fP *ct)"
.br
.ti -1c
.RI "\fBConstructTpl\fP * \fBgetConstruct\fP (void) const"
.br
.ti -1c
.RI "void \fBaddOperand\fP (\fBOperandSymbol\fP *sym)"
.br
.ti -1c
.RI "int4 \fBgetNumOperands\fP (void) const"
.br
.ti -1c
.RI "\fBOperandSymbol\fP * \fBgetOperand\fP (int4 i) const"
.br
.ti -1c
.RI "virtual \fB~MacroSymbol\fP (void)"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 587 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MacroSymbol::MacroSymbol (const string & nm, int4 i)\fC [inline]\fP"

.PP
Definition at line 592 of file slghsymbol\&.hh\&.
.SS "virtual MacroSymbol::~MacroSymbol (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 599 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void MacroSymbol::addOperand (\fBOperandSymbol\fP * sym)\fC [inline]\fP"

.PP
Definition at line 596 of file slghsymbol\&.hh\&.
.SS "\fBConstructTpl\fP* MacroSymbol::getConstruct (void) const\fC [inline]\fP"

.PP
Definition at line 595 of file slghsymbol\&.hh\&.
.SS "int4 MacroSymbol::getIndex (void) const\fC [inline]\fP"

.PP
Definition at line 593 of file slghsymbol\&.hh\&.
.SS "int4 MacroSymbol::getNumOperands (void) const\fC [inline]\fP"

.PP
Definition at line 597 of file slghsymbol\&.hh\&.
.SS "\fBOperandSymbol\fP* MacroSymbol::getOperand (int4 i) const\fC [inline]\fP"

.PP
Definition at line 598 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP MacroSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 600 of file slghsymbol\&.hh\&.
.SS "void MacroSymbol::setConstruct (\fBConstructTpl\fP * ct)\fC [inline]\fP"

.PP
Definition at line 594 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
