.TH "MacroBuilder" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MacroBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slgh_compile\&.hh>\fP
.PP
Inherits \fBPcodeBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMacroBuilder\fP (\fBSleighCompile\fP *sl, vector< \fBOpTpl\fP * > &ovec, uint4 lbcnt)"
.br
.ti -1c
.RI "void \fBsetMacroOp\fP (\fBOpTpl\fP *macroop)"
.br
.ti -1c
.RI "bool \fBhasError\fP (void) const"
.br
.ti -1c
.RI "virtual \fB~MacroBuilder\fP (void)"
.br
.ti -1c
.RI "virtual void \fBappendBuild\fP (\fBOpTpl\fP *bld, int4 secnum)"
.br
.ti -1c
.RI "virtual void \fBdelaySlot\fP (\fBOpTpl\fP *op)"
.br
.ti -1c
.RI "virtual void \fBsetLabel\fP (\fBOpTpl\fP *op)"
.br
.ti -1c
.RI "virtual void \fBappendCrossBuild\fP (\fBOpTpl\fP *bld, int4 secnum)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 145 of file slgh_compile\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MacroBuilder::MacroBuilder (\fBSleighCompile\fP * sl, vector< \fBOpTpl\fP * > & ovec, uint4 lbcnt)\fC [inline]\fP"

.PP
Definition at line 155 of file slgh_compile\&.hh\&.
.SS "virtual MacroBuilder::~MacroBuilder (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 159 of file slgh_compile\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void MacroBuilder::appendBuild (\fBOpTpl\fP * bld, int4 secnum)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPcodeBuilder\fP\&.
.PP
Definition at line 160 of file slgh_compile\&.hh\&.
.SS "virtual void MacroBuilder::appendCrossBuild (\fBOpTpl\fP * bld, int4 secnum)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPcodeBuilder\fP\&.
.PP
Definition at line 163 of file slgh_compile\&.hh\&.
.SS "virtual void MacroBuilder::delaySlot (\fBOpTpl\fP * op)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPcodeBuilder\fP\&.
.PP
Definition at line 161 of file slgh_compile\&.hh\&.
.SS "bool MacroBuilder::hasError (void) const\fC [inline]\fP"

.PP
Definition at line 158 of file slgh_compile\&.hh\&.
.SS "void MacroBuilder::setLabel (\fBOpTpl\fP * op)\fC [virtual]\fP"

.PP
Implements \fBPcodeBuilder\fP\&.
.PP
Definition at line 1420 of file slgh_compile\&.cc\&.
.SS "void MacroBuilder::setMacroOp (\fBOpTpl\fP * macroop)"

.PP
Definition at line 1328 of file slgh_compile\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
