.TH "MapRange" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapRange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <varmap\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapRange\fP (void)"
.br
.ti -1c
.RI "\fBMapRange\fP (\fBuintb\fP st, int4 sz, \fBintb\fP sst, \fBDatatype\fP *ct, uint4 fl, bool ay, int4 lo, int4 hi)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuintb\fP \fBstart\fP"
.br
.ti -1c
.RI "int4 \fBsize\fP"
.br
.ti -1c
.RI "\fBintb\fP \fBsstart\fP"
.br
.ti -1c
.RI "\fBDatatype\fP * \fBtype\fP"
.br
.ti -1c
.RI "uint4 \fBflags\fP"
.br
.ti -1c
.RI "bool \fBarrayyes\fP"
.br
.ti -1c
.RI "int4 \fBlowind\fP"
.br
.ti -1c
.RI "int4 \fBhighind\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file varmap\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MapRange::MapRange (void)\fC [inline]\fP"

.PP
Definition at line 50 of file varmap\&.hh\&.
.SS "MapRange::MapRange (\fBuintb\fP st, int4 sz, \fBintb\fP sst, \fBDatatype\fP * ct, uint4 fl, bool ay, int4 lo, int4 hi)\fC [inline]\fP"

.PP
Definition at line 51 of file varmap\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "bool MapRange::arrayyes"

.PP
Definition at line 47 of file varmap\&.hh\&.
.SS "uint4 MapRange::flags"

.PP
Definition at line 46 of file varmap\&.hh\&.
.SS "int4 MapRange::highind"

.PP
Definition at line 49 of file varmap\&.hh\&.
.SS "int4 MapRange::lowind"

.PP
Definition at line 48 of file varmap\&.hh\&.
.SS "int4 MapRange::size"

.PP
Definition at line 43 of file varmap\&.hh\&.
.SS "\fBintb\fP MapRange::sstart"

.PP
Definition at line 44 of file varmap\&.hh\&.
.SS "\fBuintb\fP MapRange::start"

.PP
Definition at line 42 of file varmap\&.hh\&.
.SS "\fBDatatype\fP* MapRange::type"

.PP
Definition at line 45 of file varmap\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
