.TH "MapState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <varmap\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapState\fP (\fBAddrSpace\fP *spc, const \fBRangeList\fP &rn, const \fBRangeList\fP &pm, \fBDatatype\fP *dt)"
.br
.ti -1c
.RI "\fB~MapState\fP (void)"
.br
.ti -1c
.RI "void \fBaddRange\fP (\fBuintb\fP st, \fBDatatype\fP *ct, uint4 fl, bool ay, int4 lo, int4 hi)"
.br
.ti -1c
.RI "void \fBaddRange\fP (const \fBEntryMap\fP *\fBrangemap\fP)"
.br
.ti -1c
.RI "bool \fBinitialize\fP (void)"
.br
.ti -1c
.RI "void \fBsortAlias\fP (void)"
.br
.ti -1c
.RI "const vector< \fBuintb\fP > & \fBgetAlias\fP (void)"
.br
.ti -1c
.RI "void \fBgatherVarnodes\fP (const \fBFuncdata\fP &fd)"
.br
.ti -1c
.RI "void \fBgatherHighs\fP (const \fBFuncdata\fP &fd)"
.br
.ti -1c
.RI "void \fBgatherOpen\fP (const \fBFuncdata\fP &fd)"
.br
.ti -1c
.RI "\fBMapRange\fP * \fBnext\fP (void)"
.br
.ti -1c
.RI "bool \fBgetNext\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file varmap\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MapState::MapState (\fBAddrSpace\fP * spc, const \fBRangeList\fP & rn, const \fBRangeList\fP & pm, \fBDatatype\fP * dt)"

.PP
Definition at line 462 of file varmap\&.cc\&.
.SS "MapState::~MapState (void)"

.PP
Definition at line 479 of file varmap\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void MapState::addRange (\fBuintb\fP st, \fBDatatype\fP * ct, uint4 fl, bool ay, int4 lo, int4 hi)"

.PP
Definition at line 487 of file varmap\&.cc\&.
.SS "void MapState::addRange (const \fBEntryMap\fP * rangemap)"

.PP
Definition at line 512 of file varmap\&.cc\&.
.SS "void MapState::gatherHighs (const \fBFuncdata\fP & fd)"

.PP
Definition at line 568 of file varmap\&.cc\&.
.SS "void MapState::gatherOpen (const \fBFuncdata\fP & fd)"

.PP
Definition at line 594 of file varmap\&.cc\&.
.SS "void MapState::gatherVarnodes (const \fBFuncdata\fP & fd)"

.PP
Definition at line 548 of file varmap\&.cc\&.
.SS "const vector<\fBuintb\fP>& MapState::getAlias (void)\fC [inline]\fP"

.PP
Definition at line 107 of file varmap\&.hh\&.
.SS "bool MapState::getNext (void)\fC [inline]\fP"

.PP
Definition at line 112 of file varmap\&.hh\&.
.SS "bool MapState::initialize (void)"

.PP
Definition at line 528 of file varmap\&.cc\&.
.SS "\fBMapRange\fP* MapState::next (void)\fC [inline]\fP"

.PP
Definition at line 111 of file varmap\&.hh\&.
.SS "void MapState::sortAlias (void)\fC [inline]\fP"

.PP
Definition at line 106 of file varmap\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
