.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/memstate.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/memstate.hh \- Classes for keeping track of memory state during emulation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pcoderaw\&.hh'\fP
.br
\fC#include 'loadimage\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMemoryBank\fP"
.br
.RI "Memory storage/state for a single AddressSpace\&. "
.ti -1c
.RI "class \fBMemoryImage\fP"
.br
.RI "A kind of \fBMemoryBank\fP which retrieves its data from an underlying \fBLoadImage\fP\&. "
.ti -1c
.RI "class \fBMemoryPageOverlay\fP"
.br
.RI "Memory bank that overlays some other memory bank, using a 'copy on write' behavior\&. "
.ti -1c
.RI "class \fBMemoryHashOverlay\fP"
.br
.RI "A memory bank that implements reads and writes using a hash table\&. "
.ti -1c
.RI "class \fBMemoryState\fP"
.br
.RI "All storage/state for a pcode machine\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classes for keeping track of memory state during emulation\&. 


.PP
Definition in file \fBmemstate\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
