.TH "MinusExpression" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MinusExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBUnaryExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinusExpression\fP (void)"
.br
.ti -1c
.RI "\fBMinusExpression\fP (\fBPatternExpression\fP *u)"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetSubValue\fP (const vector< \fBintb\fP > &replace, int4 &listpos) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 306 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MinusExpression::MinusExpression (void)\fC [inline]\fP"

.PP
Definition at line 308 of file slghpatexpress\&.hh\&.
.SS "MinusExpression::MinusExpression (\fBPatternExpression\fP * u)\fC [inline]\fP"

.PP
Definition at line 309 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBintb\fP MinusExpression::getSubValue (const vector< \fBintb\fP > & replace, int4 & listpos) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 1093 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP MinusExpression::getValue (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 1086 of file slghpatexpress\&.cc\&.
.SS "void MinusExpression::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBUnaryExpression\fP\&.
.PP
Definition at line 1100 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
