.TH "MultExpression" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBBinaryExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultExpression\fP (void)"
.br
.ti -1c
.RI "\fBMultExpression\fP (\fBPatternExpression\fP *l, \fBPatternExpression\fP *r)"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetSubValue\fP (const vector< \fBintb\fP > &replace, int4 &listpos) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 243 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MultExpression::MultExpression (void)\fC [inline]\fP"

.PP
Definition at line 245 of file slghpatexpress\&.hh\&.
.SS "MultExpression::MultExpression (\fBPatternExpression\fP * l, \fBPatternExpression\fP * r)\fC [inline]\fP"

.PP
Definition at line 246 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBintb\fP MultExpression::getSubValue (const vector< \fBintb\fP > & replace, int4 & listpos) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 926 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP MultExpression::getValue (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 918 of file slghpatexpress\&.cc\&.
.SS "void MultExpression::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBBinaryExpression\fP\&.
.PP
Definition at line 934 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
