.TH "NameSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBValueSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameSymbol\fP (void)"
.br
.ti -1c
.RI "\fBNameSymbol\fP (const string &nm, \fBPatternValue\fP *pv, const vector< string > &nt)"
.br
.ti -1c
.RI "virtual \fBConstructor\fP * \fBresolve\fP (\fBParserWalker\fP &walker)"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBsaveXmlHeader\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBSleighBase\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 229 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NameSymbol::NameSymbol (void)\fC [inline]\fP"

.PP
Definition at line 234 of file slghsymbol\&.hh\&.
.SS "NameSymbol::NameSymbol (const string & nm, \fBPatternValue\fP * pv, const vector< string > & nt)\fC [inline]\fP"

.PP
Definition at line 235 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBsymbol_type\fP NameSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBValueSymbol\fP\&.
.PP
Definition at line 238 of file slghsymbol\&.hh\&.
.SS "void NameSymbol::print (ostream & s, \fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Reimplemented from \fBValueSymbol\fP\&.
.PP
Definition at line 655 of file slghsymbol\&.cc\&.
.SS "\fBConstructor\fP * NameSymbol::resolve (\fBParserWalker\fP & walker)\fC [virtual]\fP"

.PP
Reimplemented from \fBTripleSymbol\fP\&.
.PP
Definition at line 639 of file slghsymbol\&.cc\&.
.SS "void NameSymbol::restoreXml (const \fBElement\fP * el, \fBSleighBase\fP * trans)\fC [virtual]\fP"

.PP
Reimplemented from \fBValueSymbol\fP\&.
.PP
Definition at line 687 of file slghsymbol\&.cc\&.
.SS "void NameSymbol::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBValueSymbol\fP\&.
.PP
Definition at line 663 of file slghsymbol\&.cc\&.
.SS "void NameSymbol::saveXmlHeader (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBValueSymbol\fP\&.
.PP
Definition at line 679 of file slghsymbol\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
