.TH "OpBehaviorIntSext" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpBehaviorIntSext \- CPUI_INT_SEXT behavior\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opbehavior\&.hh>\fP
.PP
Inherits \fBOpBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpBehaviorIntSext\fP (void)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual \fBuintb\fP \fBevaluateUnary\fP (int4 sizeout, int4 sizein, \fBuintb\fP in1) const"
.br
.RI "\fBEmulate\fP the unary op-code on an input value\&. "
.ti -1c
.RI "virtual \fBuintb\fP \fBrecoverInputUnary\fP (int4 sizeout, \fBuintb\fP out, int4 sizein) const"
.br
.RI "Reverse the unary op-code operation, recovering the input value\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
CPUI_INT_SEXT behavior\&. 
.PP
Definition at line 181 of file opbehavior\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpBehaviorIntSext::OpBehaviorIntSext (void)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 183 of file opbehavior\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuintb\fP OpBehaviorIntSext::evaluateUnary (int4 sizeout, int4 sizein, \fBuintb\fP in1) const\fC [virtual]\fP"

.PP
\fBEmulate\fP the unary op-code on an input value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsizeout\fP is the size of the output in bytes 
.br
\fIsizein\fP is the size of the input in bytes 
.br
\fIin1\fP is the input value 
.RE
.PP
\fBReturns:\fP
.RS 4
the output value 
.RE
.PP

.PP
Reimplemented from \fBOpBehavior\fP\&.
.PP
Definition at line 247 of file opbehavior\&.cc\&.
.SS "\fBuintb\fP OpBehaviorIntSext::recoverInputUnary (int4 sizeout, \fBuintb\fP out, int4 sizein) const\fC [virtual]\fP"

.PP
Reverse the unary op-code operation, recovering the input value\&. If the output value is known, recover the input value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsizeout\fP is the size of the output in bytes 
.br
\fIout\fP is the output value 
.br
\fIsizein\fP is the size of the input in bytes 
.RE
.PP
\fBReturns:\fP
.RS 4
the input value 
.RE
.PP

.PP
Reimplemented from \fBOpBehavior\fP\&.
.PP
Definition at line 254 of file opbehavior\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
