.TH "OpBehaviorFloatNan" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpBehaviorFloatNan \- CPUI_FLOAT_NAN behavior\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opbehavior\&.hh>\fP
.PP
Inherits \fBOpBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpBehaviorFloatNan\fP (const \fBTranslate\fP *trans)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual \fBuintb\fP \fBevaluateUnary\fP (int4 sizeout, int4 sizein, \fBuintb\fP in1) const"
.br
.RI "\fBEmulate\fP the unary op-code on an input value\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
CPUI_FLOAT_NAN behavior\&. 
.PP
Definition at line 380 of file opbehavior\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpBehaviorFloatNan::OpBehaviorFloatNan (const \fBTranslate\fP * trans)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 383 of file opbehavior\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuintb\fP OpBehaviorFloatNan::evaluateUnary (int4 sizeout, int4 sizein, \fBuintb\fP in1) const\fC [virtual]\fP"

.PP
\fBEmulate\fP the unary op-code on an input value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsizeout\fP is the size of the output in bytes 
.br
\fIsizein\fP is the size of the input in bytes 
.br
\fIin1\fP is the input value 
.RE
.PP
\fBReturns:\fP
.RS 4
the output value 
.RE
.PP

.PP
Reimplemented from \fBOpBehavior\fP\&.
.PP
Definition at line 571 of file opbehavior\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
