.TH "OpBehaviorIntSdiv" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpBehaviorIntSdiv \- CPUI_INT_SDIV behavior\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opbehavior\&.hh>\fP
.PP
Inherits \fBOpBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpBehaviorIntSdiv\fP (void)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual \fBuintb\fP \fBevaluateBinary\fP (int4 sizeout, int4 sizein, \fBuintb\fP in1, \fBuintb\fP in2) const"
.br
.RI "\fBEmulate\fP the binary op-code on input values\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
CPUI_INT_SDIV behavior\&. 
.PP
Definition at line 299 of file opbehavior\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpBehaviorIntSdiv::OpBehaviorIntSdiv (void)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 301 of file opbehavior\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuintb\fP OpBehaviorIntSdiv::evaluateBinary (int4 sizeout, int4 sizein, \fBuintb\fP in1, \fBuintb\fP in2) const\fC [virtual]\fP"

.PP
\fBEmulate\fP the binary op-code on input values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsizeout\fP is the size of the output in bytes 
.br
\fIsizein\fP is the size of the inputs in bytes 
.br
\fIin1\fP is the first input value 
.br
\fIin2\fP is the second input value 
.RE
.PP
\fBReturns:\fP
.RS 4
the output value 
.RE
.PP

.PP
Reimplemented from \fBOpBehavior\fP\&.
.PP
Definition at line 465 of file opbehavior\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
