.TH "OperandValue" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperandValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperandValue\fP (void)"
.br
.ti -1c
.RI "\fBOperandValue\fP (int4 ind, \fBConstructor\fP *c)"
.br
.ti -1c
.RI "void \fBchangeIndex\fP (int4 newind)"
.br
.ti -1c
.RI "bool \fBisConstructorRelative\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetName\fP (void) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenPattern\fP (\fBintb\fP val) const"
.br
.ti -1c
.RI "virtual \fBTokenPattern\fP \fBgenMinPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetSubValue\fP (const vector< \fBintb\fP > &replace, int4 &listpos) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBminValue\fP (void) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBmaxValue\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBTranslate\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 170 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OperandValue::OperandValue (void)\fC [inline]\fP"

.PP
Definition at line 174 of file slghpatexpress\&.hh\&.
.SS "OperandValue::OperandValue (int4 ind, \fBConstructor\fP * c)\fC [inline]\fP"

.PP
Definition at line 175 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void OperandValue::changeIndex (int4 newind)\fC [inline]\fP"

.PP
Definition at line 176 of file slghpatexpress\&.hh\&.
.SS "virtual \fBTokenPattern\fP OperandValue::genMinPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 180 of file slghpatexpress\&.hh\&.
.SS "\fBTokenPattern\fP OperandValue::genPattern (\fBintb\fP val) const\fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 704 of file slghpatexpress\&.cc\&.
.SS "const string & OperandValue::getName (void) const"

.PP
Definition at line 765 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP OperandValue::getSubValue (const vector< \fBintb\fP > & replace, int4 & listpos) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPatternValue\fP\&.
.PP
Definition at line 751 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP OperandValue::getValue (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 731 of file slghpatexpress\&.cc\&.
.SS "bool OperandValue::isConstructorRelative (void) const"

.PP
Definition at line 758 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP OperandValue::maxValue (void) const\fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 725 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP OperandValue::minValue (void) const\fC [virtual]\fP"

.PP
Implements \fBPatternValue\fP\&.
.PP
Definition at line 719 of file slghpatexpress\&.cc\&.
.SS "void OperandValue::restoreXml (const \fBElement\fP * el, \fBTranslate\fP * trans)\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 781 of file slghpatexpress\&.cc\&.
.SS "void OperandValue::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 772 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
