.TH "OperandEquation" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperandEquation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternEquation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperandEquation\fP (int4 ind)"
.br
.ti -1c
.RI "virtual void \fBgenPattern\fP (const vector< \fBTokenPattern\fP > &ops) const"
.br
.ti -1c
.RI "virtual bool \fBresolveOperandLeft\fP (\fBOperandResolve\fP &state) const"
.br
.ti -1c
.RI "virtual void \fBoperandOrder\fP (\fBConstructor\fP *ct, vector< \fBOperandSymbol\fP * > &order) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 351 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OperandEquation::OperandEquation (int4 ind)\fC [inline]\fP"

.PP
Definition at line 354 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void OperandEquation::genPattern (const vector< \fBTokenPattern\fP > & ops) const\fC [virtual]\fP"

.PP
Implements \fBPatternEquation\fP\&.
.PP
Definition at line 1165 of file slghpatexpress\&.cc\&.
.SS "void OperandEquation::operandOrder (\fBConstructor\fP * ct, vector< \fBOperandSymbol\fP * > & order) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPatternEquation\fP\&.
.PP
Definition at line 1189 of file slghpatexpress\&.cc\&.
.SS "bool OperandEquation::resolveOperandLeft (\fBOperandResolve\fP & state) const\fC [virtual]\fP"

.PP
Implements \fBPatternEquation\fP\&.
.PP
Definition at line 1171 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
