.TH "OpTpl" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpTpl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <semantics\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpTpl\fP (void)"
.br
.ti -1c
.RI "\fBOpTpl\fP (\fBOpCode\fP oc)"
.br
.ti -1c
.RI "\fB~OpTpl\fP (void)"
.br
.ti -1c
.RI "\fBVarnodeTpl\fP * \fBgetOut\fP (void) const"
.br
.ti -1c
.RI "int4 \fBnumInput\fP (void) const"
.br
.ti -1c
.RI "\fBVarnodeTpl\fP * \fBgetIn\fP (int4 i) const"
.br
.ti -1c
.RI "\fBOpCode\fP \fBgetOpcode\fP (void) const"
.br
.ti -1c
.RI "bool \fBisZeroSize\fP (void) const"
.br
.ti -1c
.RI "void \fBsetOpcode\fP (\fBOpCode\fP o)"
.br
.ti -1c
.RI "void \fBsetOutput\fP (\fBVarnodeTpl\fP *vt)"
.br
.ti -1c
.RI "void \fBclearOutput\fP (void)"
.br
.ti -1c
.RI "void \fBaddInput\fP (\fBVarnodeTpl\fP *vt)"
.br
.ti -1c
.RI "void \fBsetInput\fP (\fBVarnodeTpl\fP *vt, int4 slot)"
.br
.ti -1c
.RI "void \fBremoveInput\fP (int4 index)"
.br
.ti -1c
.RI "void \fBchangeHandleIndex\fP (const vector< int4 > &handmap)"
.br
.ti -1c
.RI "void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "void \fBrestoreXml\fP (const \fBElement\fP *el, const \fBAddrSpaceManager\fP *manage)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 137 of file semantics\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpTpl::OpTpl (void)\fC [inline]\fP"

.PP
Definition at line 142 of file semantics\&.hh\&.
.SS "OpTpl::OpTpl (\fBOpCode\fP oc)\fC [inline]\fP"

.PP
Definition at line 143 of file semantics\&.hh\&.
.SS "OpTpl::~OpTpl (void)"

.PP
Definition at line 660 of file semantics\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void OpTpl::addInput (\fBVarnodeTpl\fP * vt)\fC [inline]\fP"

.PP
Definition at line 153 of file semantics\&.hh\&.
.SS "void OpTpl::changeHandleIndex (const vector< int4 > & handmap)"

.PP
Definition at line 691 of file semantics\&.cc\&.
.SS "void OpTpl::clearOutput (void)\fC [inline]\fP"

.PP
Definition at line 152 of file semantics\&.hh\&.
.SS "\fBVarnodeTpl\fP* OpTpl::getIn (int4 i) const\fC [inline]\fP"

.PP
Definition at line 147 of file semantics\&.hh\&.
.SS "\fBOpCode\fP OpTpl::getOpcode (void) const\fC [inline]\fP"

.PP
Definition at line 148 of file semantics\&.hh\&.
.SS "\fBVarnodeTpl\fP* OpTpl::getOut (void) const\fC [inline]\fP"

.PP
Definition at line 145 of file semantics\&.hh\&.
.SS "bool OpTpl::isZeroSize (void) const"

.PP
Definition at line 670 of file semantics\&.cc\&.
.SS "int4 OpTpl::numInput (void) const\fC [inline]\fP"

.PP
Definition at line 146 of file semantics\&.hh\&.
.SS "void OpTpl::removeInput (int4 index)"

.PP
Definition at line 682 of file semantics\&.cc\&.
.SS "void OpTpl::restoreXml (const \fBElement\fP * el, const \fBAddrSpaceManager\fP * manage)"

.PP
Definition at line 715 of file semantics\&.cc\&.
.SS "void OpTpl::saveXml (ostream & s) const"

.PP
Definition at line 702 of file semantics\&.cc\&.
.SS "void OpTpl::setInput (\fBVarnodeTpl\fP * vt, int4 slot)\fC [inline]\fP"

.PP
Definition at line 154 of file semantics\&.hh\&.
.SS "void OpTpl::setOpcode (\fBOpCode\fP o)\fC [inline]\fP"

.PP
Definition at line 150 of file semantics\&.hh\&.
.SS "void OpTpl::setOutput (\fBVarnodeTpl\fP * vt)\fC [inline]\fP"

.PP
Definition at line 151 of file semantics\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
