.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/override.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/override.hh \- A system for sending override commands to the decompiler\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'database\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOverride\fP"
.br
.RI "A container of commands that override the decompiler's default behavior for a single function\&. "
.in -1c
.SH "Detailed Description"
.PP 
A system for sending override commands to the decompiler\&. 


.PP
Definition in file \fBoverride\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
