.TH "ParameterPieces" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParameterPieces \- Basic elements of a parameter: address, data-type, properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fspec\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAddress\fP \fBaddr\fP"
.br
.RI "Storage address of the parameter\&. "
.ti -1c
.RI "\fBDatatype\fP * \fBtype\fP"
.br
.RI "The datatype of the parameter\&. "
.ti -1c
.RI "uint4 \fBflags\fP"
.br
.RI "additional attributes of the parameter "
.in -1c
.SH "Detailed Description"
.PP 
Basic elements of a parameter: address, data-type, properties\&. 
.PP
Definition at line 252 of file fspec\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAddress\fP ParameterPieces::addr"

.PP
Storage address of the parameter\&. 
.PP
Definition at line 253 of file fspec\&.hh\&.
.SS "uint4 ParameterPieces::flags"

.PP
additional attributes of the parameter 
.PP
Definition at line 255 of file fspec\&.hh\&.
.SS "\fBDatatype\fP* ParameterPieces::type"

.PP
The datatype of the parameter\&. 
.PP
Definition at line 254 of file fspec\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
