.TH "ParamIDAnalysis" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamIDAnalysis
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <paramid\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParamIDAnalysis\fP (\fBFuncdata\fP *fd_in, bool justproto)"
.br
.ti -1c
.RI "void \fBsaveXml\fP (ostream &s, bool moredetail) const"
.br
.ti -1c
.RI "void \fBsavePretty\fP (ostream &s, bool moredetail) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file paramid\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParamIDAnalysis::ParamIDAnalysis (\fBFuncdata\fP * fd_in, bool justproto)"

.PP
Definition at line 179 of file paramid\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void ParamIDAnalysis::savePretty (ostream & s, bool moredetail) const"

.PP
Definition at line 261 of file paramid\&.cc\&.
.SS "void ParamIDAnalysis::saveXml (ostream & s, bool moredetail) const"

.PP
Definition at line 230 of file paramid\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
