.TH "ParamMeasure::WalkState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamMeasure::WalkState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <paramid\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbest\fP"
.br
.ti -1c
.RI "int4 \fBdepth\fP"
.br
.ti -1c
.RI "\fBParamRank\fP \fBterminalrank\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file paramid\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ParamMeasure::WalkState::best"

.PP
Definition at line 42 of file paramid\&.hh\&.
.SS "int4 ParamMeasure::WalkState::depth"

.PP
Definition at line 43 of file paramid\&.hh\&.
.SS "\fBParamRank\fP ParamMeasure::WalkState::terminalrank"

.PP
Definition at line 44 of file paramid\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
