.TH "ParamUnassignedError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamUnassignedError \- Exception thrown when a prototype can't be modeled properly\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fspec\&.hh>\fP
.PP
Inherits \fBLowlevelError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParamUnassignedError\fP (const string &s)"
.br
.RI "\fBConstructor\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Exception thrown when a prototype can't be modeled properly\&. 
.PP
Definition at line 27 of file fspec\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParamUnassignedError::ParamUnassignedError (const string & s)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 28 of file fspec\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
