.TH "ParseError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseError \- An error generated while parsing a command or language\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <error\&.hh>\fP
.PP
Inherits \fBLowlevelError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseError\fP (const string &s)"
.br
.RI "Initialize the error with an explanatory string\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An error generated while parsing a command or language\&. 

This error is generated when parsing character data of some form, as in a user command from the console or when parsing C syntax\&. 
.PP
Definition at line 65 of file error\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseError::ParseError (const string & s)\fC [inline]\fP"

.PP
Initialize the error with an explanatory string\&. 
.PP
Definition at line 67 of file error\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
