.TH "ParserWalkerChange" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParserWalkerChange
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <context\&.hh>\fP
.PP
Inherits \fBParserWalker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParserWalkerChange\fP (\fBParserContext\fP *c)"
.br
.ti -1c
.RI "\fBParserContext\fP * \fBgetParserContext\fP (void)"
.br
.ti -1c
.RI "\fBConstructState\fP * \fBgetPoint\fP (void)"
.br
.ti -1c
.RI "void \fBsetOffset\fP (uint4 off)"
.br
.ti -1c
.RI "void \fBsetConstructor\fP (\fBConstructor\fP *c)"
.br
.ti -1c
.RI "void \fBsetCurrentLength\fP (int4 len)"
.br
.ti -1c
.RI "void \fBcalcCurrentLength\fP (int4 length, int4 numopers)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBParserContext\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 163 of file context\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParserWalkerChange::ParserWalkerChange (\fBParserContext\fP * c)\fC [inline]\fP"

.PP
Definition at line 167 of file context\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void ParserWalkerChange::calcCurrentLength (int4 length, int4 numopers)"

.PP
Definition at line 208 of file context\&.cc\&.
.SS "\fBParserContext\fP* ParserWalkerChange::getParserContext (void)\fC [inline]\fP"

.PP
Definition at line 168 of file context\&.hh\&.
.SS "\fBConstructState\fP* ParserWalkerChange::getPoint (void)\fC [inline]\fP"

.PP
Definition at line 169 of file context\&.hh\&.
.SS "void ParserWalkerChange::setConstructor (\fBConstructor\fP * c)\fC [inline]\fP"

.PP
Definition at line 171 of file context\&.hh\&.
.SS "void ParserWalkerChange::setCurrentLength (int4 len)\fC [inline]\fP"

.PP
Definition at line 172 of file context\&.hh\&.
.SS "void ParserWalkerChange::setOffset (uint4 off)\fC [inline]\fP"

.PP
Definition at line 170 of file context\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBParserContext\fP\fC [friend]\fP"

.PP
Definition at line 164 of file context\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
