.TH "PathMeld" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PathMeld
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jumptable\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset\fP (const \fBPathMeld\fP &op2)"
.br
.ti -1c
.RI "void \fBset\fP (const vector< \fBPcodeOp\fP * > &path, const vector< int4 > &slot)"
.br
.ti -1c
.RI "void \fBset\fP (\fBPcodeOp\fP *op, \fBVarnode\fP *vn)"
.br
.ti -1c
.RI "void \fBappend\fP (const \fBPathMeld\fP &op2)"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "void \fBmeld\fP (vector< \fBPcodeOp\fP * > &path, vector< int4 > &slot)"
.br
.ti -1c
.RI "int4 \fBnumCommonVarnode\fP (void) const"
.br
.ti -1c
.RI "int4 \fBnumOps\fP (void) const"
.br
.ti -1c
.RI "\fBVarnode\fP * \fBgetVarnode\fP (int4 i) const"
.br
.ti -1c
.RI "\fBVarnode\fP * \fBgetOpParent\fP (int4 i) const"
.br
.ti -1c
.RI "\fBPcodeOp\fP * \fBgetOp\fP (int4 i) const"
.br
.ti -1c
.RI "\fBPcodeOp\fP * \fBgetEarliestOp\fP (int4 pos) const"
.br
.ti -1c
.RI "bool \fBempty\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file jumptable\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void PathMeld::append (const \fBPathMeld\fP & op2)"

.PP
Definition at line 797 of file jumptable\&.cc\&.
.SS "void PathMeld::clear (void)"

.PP
Definition at line 807 of file jumptable\&.cc\&.
.SS "bool PathMeld::empty (void) const\fC [inline]\fP"

.PP
Definition at line 74 of file jumptable\&.hh\&.
.SS "\fBPcodeOp\fP * PathMeld::getEarliestOp (int4 pos) const"

.PP
Definition at line 843 of file jumptable\&.cc\&.
.SS "\fBPcodeOp\fP* PathMeld::getOp (int4 i) const\fC [inline]\fP"

.PP
Definition at line 72 of file jumptable\&.hh\&.
.SS "\fBVarnode\fP* PathMeld::getOpParent (int4 i) const\fC [inline]\fP"

.PP
Definition at line 71 of file jumptable\&.hh\&.
.SS "\fBVarnode\fP* PathMeld::getVarnode (int4 i) const\fC [inline]\fP"

.PP
Definition at line 70 of file jumptable\&.hh\&.
.SS "void PathMeld::meld (vector< \fBPcodeOp\fP * > & path, vector< int4 > & slot)"

.PP
Definition at line 814 of file jumptable\&.cc\&.
.SS "int4 PathMeld::numCommonVarnode (void) const\fC [inline]\fP"

.PP
Definition at line 68 of file jumptable\&.hh\&.
.SS "int4 PathMeld::numOps (void) const\fC [inline]\fP"

.PP
Definition at line 69 of file jumptable\&.hh\&.
.SS "void PathMeld::set (const \fBPathMeld\fP & op2)"

.PP
Definition at line 772 of file jumptable\&.cc\&.
.SS "void PathMeld::set (const vector< \fBPcodeOp\fP * > & path, const vector< int4 > & slot)"

.PP
Definition at line 779 of file jumptable\&.cc\&.
.SS "void PathMeld::set (\fBPcodeOp\fP * op, \fBVarnode\fP * vn)"

.PP
Definition at line 790 of file jumptable\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
