.TH "PatternlessSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PatternlessSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSpecificSymbol\fP\&.
.PP
Inherited by \fBEpsilonSymbol\fP, and \fBVarnodeSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatternlessSymbol\fP (void)"
.br
.ti -1c
.RI "\fBPatternlessSymbol\fP (const string &nm)"
.br
.ti -1c
.RI "virtual \fB~PatternlessSymbol\fP (void)"
.br
.ti -1c
.RI "virtual \fBPatternExpression\fP * \fBgetPatternExpression\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBSleighBase\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 171 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PatternlessSymbol::PatternlessSymbol (void)"

.PP
Definition at line 406 of file slghsymbol\&.cc\&.
.SS "PatternlessSymbol::PatternlessSymbol (const string & nm)"

.PP
Definition at line 415 of file slghsymbol\&.cc\&.
.SS "PatternlessSymbol::~PatternlessSymbol (void)\fC [virtual]\fP"

.PP
Definition at line 422 of file slghsymbol\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBPatternExpression\fP* PatternlessSymbol::getPatternExpression (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBTripleSymbol\fP\&.
.PP
Definition at line 177 of file slghsymbol\&.hh\&.
.SS "virtual void PatternlessSymbol::restoreXml (const \fBElement\fP * el, \fBSleighBase\fP * trans)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Reimplemented in \fBVarnodeSymbol\fP, and \fBEpsilonSymbol\fP\&.
.PP
Definition at line 179 of file slghsymbol\&.hh\&.
.SS "virtual void PatternlessSymbol::saveXml (ostream & s) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Reimplemented in \fBVarnodeSymbol\fP, and \fBEpsilonSymbol\fP\&.
.PP
Definition at line 178 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
