.TH "PcodeCacher" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PcodeCacher
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sleigh\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPcodeCacher\fP (void)"
.br
.ti -1c
.RI "\fB~PcodeCacher\fP (void)"
.br
.ti -1c
.RI "\fBVarnodeData\fP * \fBallocateVarnodes\fP (uint4 size)"
.br
.ti -1c
.RI "\fBPcodeData\fP * \fBallocateInstruction\fP (void)"
.br
.ti -1c
.RI "void \fBaddLabelRef\fP (\fBVarnodeData\fP *ptr)"
.br
.ti -1c
.RI "void \fBaddLabel\fP (uint4 id)"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "void \fBresolveRelatives\fP (void)"
.br
.ti -1c
.RI "void \fBemit\fP (const \fBAddress\fP &addr, \fBPcodeEmit\fP *emt) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file sleigh\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PcodeCacher::PcodeCacher (void)"

.PP
Definition at line 19 of file sleigh\&.cc\&.
.SS "PcodeCacher::~PcodeCacher (void)"

.PP
Definition at line 29 of file sleigh\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void PcodeCacher::addLabel (uint4 id)"

.PP
Definition at line 87 of file sleigh\&.cc\&.
.SS "void PcodeCacher::addLabelRef (\fBVarnodeData\fP * ptr)"

.PP
Definition at line 78 of file sleigh\&.cc\&.
.SS "\fBPcodeData\fP* PcodeCacher::allocateInstruction (void)\fC [inline]\fP"

.PP
Definition at line 55 of file sleigh\&.hh\&.
.SS "\fBVarnodeData\fP* PcodeCacher::allocateVarnodes (uint4 size)\fC [inline]\fP"

.PP
Definition at line 46 of file sleigh\&.hh\&.
.SS "void PcodeCacher::clear (void)"

.PP
Definition at line 95 of file sleigh\&.cc\&.
.SS "void PcodeCacher::emit (const \fBAddress\fP & addr, \fBPcodeEmit\fP * emt) const"

.PP
Definition at line 122 of file sleigh\&.cc\&.
.SS "void PcodeCacher::resolveRelatives (void)"

.PP
Definition at line 104 of file sleigh\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
