.TH "PcodeOpEdge" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PcodeOpEdge \- Class representing a \fIterm\fP in an additive expression\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coreaction\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPcodeOpEdge\fP (\fBPcodeOp\fP *o, int4 s, \fBPcodeOp\fP *m)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "\fBPcodeOp\fP * \fBgetMultiplier\fP (void) const"
.br
.RI "Get the multiplier \fBPcodeOp\fP\&. "
.ti -1c
.RI "\fBPcodeOp\fP * \fBgetOp\fP (void) const"
.br
.RI "Get the component \fBPcodeOp\fP adding in the term\&. "
.ti -1c
.RI "int4 \fBgetSlot\fP (void) const"
.br
.RI "Get the slot reading the term\&. "
.ti -1c
.RI "\fBVarnode\fP * \fBgetVarnode\fP (void) const"
.br
.RI "Get the \fBVarnode\fP term\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class representing a \fIterm\fP in an additive expression\&. 
.PP
Definition at line 984 of file coreaction\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PcodeOpEdge::PcodeOpEdge (\fBPcodeOp\fP * o, int4 s, \fBPcodeOp\fP * m)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 990 of file coreaction\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPcodeOp\fP* PcodeOpEdge::getMultiplier (void) const\fC [inline]\fP"

.PP
Get the multiplier \fBPcodeOp\fP\&. 
.PP
Definition at line 991 of file coreaction\&.hh\&.
.SS "\fBPcodeOp\fP* PcodeOpEdge::getOp (void) const\fC [inline]\fP"

.PP
Get the component \fBPcodeOp\fP adding in the term\&. 
.PP
Definition at line 992 of file coreaction\&.hh\&.
.SS "int4 PcodeOpEdge::getSlot (void) const\fC [inline]\fP"

.PP
Get the slot reading the term\&. 
.PP
Definition at line 993 of file coreaction\&.hh\&.
.SS "\fBVarnode\fP* PcodeOpEdge::getVarnode (void) const\fC [inline]\fP"

.PP
Get the \fBVarnode\fP term\&. 
.PP
Definition at line 994 of file coreaction\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
