.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/pcoderaw.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/pcoderaw.hh \- Raw descriptions of varnodes and p-code ops\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'address\&.hh'\fP
.br
\fC#include 'opbehavior\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVarnodeData\fP"
.br
.RI "Data defining a specific memory location\&. "
.ti -1c
.RI "class \fBPcodeOpRaw\fP"
.br
.RI "A low-level representation of a single pcode operation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Raw descriptions of varnodes and p-code ops\&. 


.PP
Definition in file \fBpcoderaw\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
