.TH "PcodeInjectLibraryGhidra" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PcodeInjectLibraryGhidra \- A p-code injection library that uses a Ghidra client to generate/compile the injection p-code\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inject_ghidra\&.hh>\fP
.PP
Inherits \fBPcodeInjectLibrary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPcodeInjectLibraryGhidra\fP (\fBArchitectureGhidra\fP *ghi)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual int4 \fBmanualCallFixup\fP (const string &name, const string &snippet)"
.br
.RI "Manually add a call-fixup payload given a compilable snippet of p-code \fIsource\fP\&. "
.ti -1c
.RI "virtual int4 \fBmanualCallOtherFixup\fP (const string &name, const string &outname, const vector< string > &inname, const string &snippet)"
.br
.RI "Manually add a callother-fixup payload given a compilable snippet of p-code \fIsource\fP\&. "
.ti -1c
.RI "virtual \fBInjectContext\fP & \fBgetCachedContext\fP (void)"
.br
.RI "Retrieve a reusable context object for \fBthis\fP library\&. "
.ti -1c
.RI "virtual const vector< \fBOpBehavior\fP * > & \fBgetBehaviors\fP (void)"
.br
.RI "Get the array of op-code behaviors for initializing and emulator\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A p-code injection library that uses a Ghidra client to generate/compile the injection p-code\&. 

The \fBInjectPayload\fP objects produced by this library are just placeholders (see \fBInjectPayloadGhidra\fP)\&. At the time of injection, final p-code is generated by the Ghidra client\&. 
.PP
Definition at line 80 of file inject_ghidra\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PcodeInjectLibraryGhidra::PcodeInjectLibraryGhidra (\fBArchitectureGhidra\fP * ghi)"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 196 of file inject_ghidra\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "const vector< \fBOpBehavior\fP * > & PcodeInjectLibraryGhidra::getBehaviors (void)\fC [virtual]\fP"

.PP
Get the array of op-code behaviors for initializing and emulator\&. Behaviors are pulled from the underlying architecture in order to initialize the \fBEmulate\fP object which services the \fIp-code\fP \fIscript\fP payloads\&. 
.PP
\fBReturns:\fP
.RS 4
the array of \fBOpBehavior\fP objects indexed by op-code 
.RE
.PP

.PP
Implements \fBPcodeInjectLibrary\fP\&.
.PP
Definition at line 202 of file inject_ghidra\&.cc\&.
.SS "virtual \fBInjectContext\fP& PcodeInjectLibraryGhidra::getCachedContext (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Retrieve a reusable context object for \fBthis\fP library\&. The object returned by this method gets passed to the payload inject() method\&. The clear() method must be called between uses\&. 
.PP
\fBReturns:\fP
.RS 4
the cached context object 
.RE
.PP

.PP
Implements \fBPcodeInjectLibrary\fP\&.
.PP
Definition at line 90 of file inject_ghidra\&.hh\&.
.SS "int4 PcodeInjectLibraryGhidra::manualCallFixup (const string & name, const string & snippetstring)\fC [virtual]\fP"

.PP
Manually add a call-fixup payload given a compilable snippet of p-code \fIsource\fP\&. The snippet is compiled immediately to produce the payload\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP is the formal name of the new payload 
.br
\fIsnippetstring\fP is the compilable snippet of p-code \fIsource\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the id of the new payload 
.RE
.PP

.PP
Implements \fBPcodeInjectLibrary\fP\&.
.PP
Definition at line 210 of file inject_ghidra\&.cc\&.
.SS "int4 PcodeInjectLibraryGhidra::manualCallOtherFixup (const string & name, const string & outname, const vector< string > & inname, const string & snippet)\fC [virtual]\fP"

.PP
Manually add a callother-fixup payload given a compilable snippet of p-code \fIsource\fP\&. The snippet is compiled immediately to produce the payload\&. \fBSymbol\fP names for input and output parameters must be provided to the compiler\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP is the formal name of the new payload 
.br
\fIoutname\fP is the name of the output symbol 
.br
\fIinname\fP is the ordered list of input symbol names 
.br
\fIsnippet\fP is the compilable snippet of p-code \fIsource\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the id of the new payload 
.RE
.PP

.PP
Implements \fBPcodeInjectLibrary\fP\&.
.PP
Definition at line 216 of file inject_ghidra\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
