.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/pcodeinject.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/pcodeinject.hh \- Classes for managing \fBp-code\fP \fBinjection\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'emulateutil\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInjectParameter\fP"
.br
.RI "An input or output parameter to a p-code injection payload\&. "
.ti -1c
.RI "class \fBInjectContext\fP"
.br
.RI "Context needed to emit a p-code injection as a full set of p-code operations\&. "
.ti -1c
.RI "class \fBInjectPayload\fP"
.br
.RI "An active container for a set of p-code operations that can be injected into data-flow\&. "
.ti -1c
.RI "class \fBExecutablePcode\fP"
.br
.RI "A snippet of p-code that can be executed outside of normal analysis\&. "
.ti -1c
.RI "class \fBPcodeInjectLibrary\fP"
.br
.RI "A collection of p-code injection payloads\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classes for managing \fBp-code\fP \fBinjection\fP\&. 


.PP
Definition in file \fBpcodeinject\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
