.TH "PcodeSnippet" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PcodeSnippet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pcodeparse\&.hh>\fP
.PP
Inherits \fBPcodeCompile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPcodeSnippet\fP (const \fBSleighBase\fP *\fBslgh\fP)"
.br
.ti -1c
.RI "void \fBsetResult\fP (\fBConstructTpl\fP *res)"
.br
.ti -1c
.RI "\fBConstructTpl\fP * \fBreleaseResult\fP (void)"
.br
.ti -1c
.RI "virtual \fB~PcodeSnippet\fP (void)"
.br
.ti -1c
.RI "virtual void \fBreportError\fP (const string &msg)"
.br
.ti -1c
.RI "bool \fBhasErrors\fP (void) const"
.br
.ti -1c
.RI "const string \fBgetErrorMessage\fP (void) const"
.br
.ti -1c
.RI "void \fBsetUniqueBase\fP (\fBuintb\fP val)"
.br
.ti -1c
.RI "\fBuintb\fP \fBgetUniqueBase\fP (void) const"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "int \fBlex\fP (void)"
.br
.ti -1c
.RI "bool \fBparseStream\fP (istream &s)"
.br
.ti -1c
.RI "void \fBaddOperand\fP (const string &name, int4 index)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 70 of file pcodeparse\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PcodeSnippet::PcodeSnippet (const \fBSleighBase\fP * slgh)"

.SS "virtual PcodeSnippet::~PcodeSnippet (void)\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void PcodeSnippet::addOperand (const string & name, int4 index)"

.SS "void PcodeSnippet::clear (void)"

.SS "const string PcodeSnippet::getErrorMessage (void) const\fC [inline]\fP"

.PP
Definition at line 87 of file pcodeparse\&.hh\&.
.SS "\fBuintb\fP PcodeSnippet::getUniqueBase (void) const\fC [inline]\fP"

.PP
Definition at line 89 of file pcodeparse\&.hh\&.
.SS "bool PcodeSnippet::hasErrors (void) const\fC [inline]\fP"

.PP
Definition at line 86 of file pcodeparse\&.hh\&.
.SS "int PcodeSnippet::lex (void)"

.SS "bool PcodeSnippet::parseStream (istream & s)"

.SS "\fBConstructTpl\fP* PcodeSnippet::releaseResult (void)\fC [inline]\fP"

.PP
Definition at line 83 of file pcodeparse\&.hh\&.
.SS "virtual void PcodeSnippet::reportError (const string & msg)\fC [virtual]\fP"

.PP
Implements \fBPcodeCompile\fP\&.
.SS "void PcodeSnippet::setResult (\fBConstructTpl\fP * res)\fC [inline]\fP"

.PP
Definition at line 82 of file pcodeparse\&.hh\&.
.SS "void PcodeSnippet::setUniqueBase (\fBuintb\fP val)\fC [inline]\fP"

.PP
Definition at line 88 of file pcodeparse\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
