.TH "PointerModifier" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointerModifier
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grammar\&.hh>\fP
.PP
Inherits \fBTypeModifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPointerModifier\fP (uint4 fl)"
.br
.ti -1c
.RI "virtual uint4 \fBgetType\fP (void) const"
.br
.ti -1c
.RI "virtual bool \fBisValid\fP (void) const"
.br
.ti -1c
.RI "virtual \fBDatatype\fP * \fBmodType\fP (\fBDatatype\fP *base, const \fBTypeDeclarator\fP *decl, \fBArchitecture\fP *glb) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 131 of file grammar\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PointerModifier::PointerModifier (uint4 fl)\fC [inline]\fP"

.PP
Definition at line 134 of file grammar\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual uint4 PointerModifier::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBTypeModifier\fP\&.
.PP
Definition at line 135 of file grammar\&.hh\&.
.SS "virtual bool PointerModifier::isValid (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBTypeModifier\fP\&.
.PP
Definition at line 136 of file grammar\&.hh\&.
.SS "virtual \fBDatatype\fP* PointerModifier::modType (\fBDatatype\fP * base, const \fBTypeDeclarator\fP * decl, \fBArchitecture\fP * glb) const\fC [virtual]\fP"

.PP
Implements \fBTypeModifier\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
