.TH "PreferSplitManager" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreferSplitManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prefersplit\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBFuncdata\fP *fd, const vector< \fBPreferSplitRecord\fP > *rec)"
.br
.ti -1c
.RI "const \fBPreferSplitRecord\fP * \fBfindRecord\fP (\fBVarnode\fP *vn) const"
.br
.ti -1c
.RI "void \fBsplit\fP (void)"
.br
.ti -1c
.RI "void \fBsplitAdditional\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinitialize\fP (vector< \fBPreferSplitRecord\fP > &records)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file prefersplit\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBPreferSplitRecord\fP * PreferSplitManager::findRecord (\fBVarnode\fP * vn) const"

.PP
Definition at line 533 of file prefersplit\&.cc\&.
.SS "void PreferSplitManager::init (\fBFuncdata\fP * fd, const vector< \fBPreferSplitRecord\fP > * rec)"

.PP
Definition at line 526 of file prefersplit\&.cc\&.
.SS "void PreferSplitManager::initialize (vector< \fBPreferSplitRecord\fP > & records)\fC [static]\fP"

.PP
Definition at line 549 of file prefersplit\&.cc\&.
.SS "void PreferSplitManager::split (void)"

.PP
Definition at line 555 of file prefersplit\&.cc\&.
.SS "void PreferSplitManager::splitAdditional (void)"

.PP
Definition at line 562 of file prefersplit\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
