.TH "PreferSplitRecord" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreferSplitRecord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prefersplit\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPreferSplitRecord\fP &op2) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVarnodeData\fP \fBstorage\fP"
.br
.ti -1c
.RI "int4 \fBsplitoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file prefersplit\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PreferSplitRecord::operator< (const \fBPreferSplitRecord\fP & op2) const"

.PP
Definition at line 20 of file prefersplit\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int4 PreferSplitRecord::splitoffset"

.PP
Definition at line 25 of file prefersplit\&.hh\&.
.SS "\fBVarnodeData\fP PreferSplitRecord::storage"

.PP
Definition at line 24 of file prefersplit\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
