.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/prettyprint.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/prettyprint.hh \- Routines for emitting high-level (C) language syntax in a well formatted way\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'type\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmitXml\fP"
.br
.RI "Base class (and interface) for pretty printing and XML markup of tokens\&. "
.ti -1c
.RI "class \fBEmitNoXml\fP"
.br
.RI "A trivial emitter that outputs syntax straight to the stream\&. "
.ti -1c
.RI "class \fBTokenSplit\fP"
.br
.RI "A token/command object in the pretty printing stream\&. "
.ti -1c
.RI "class \fBcircularqueue< _type >\fP"
.br
.RI "A circular buffer template\&. "
.ti -1c
.RI "class \fBEmitPrettyPrint\fP"
.br
.RI "A generic source code pretty printer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Routines for emitting high-level (C) language syntax in a well formatted way\&. 


.PP
Definition in file \fBprettyprint\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
