.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/prettyprint.cc" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/prettyprint.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'prettyprint\&.hh'\fP
.br
\fC#include 'funcdata\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
