.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/printlanguage.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/printlanguage.hh \- Classes for printing tokens in a high-level language\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'capability\&.hh'\fP
.br
\fC#include 'cast\&.hh'\fP
.br
\fC#include 'prettyprint\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrintLanguageCapability\fP"
.br
.RI "Base class for high-level language capabilities\&. "
.ti -1c
.RI "class \fBOpToken\fP"
.br
.RI "A token representing an operator in the high-level language\&. "
.ti -1c
.RI "class \fBPrintLanguage\fP"
.br
.RI "The base class API for emitting a high-level language\&. "
.ti -1c
.RI "struct \fBPrintLanguage::ReversePolish\fP"
.br
.RI "An entry on the reverse polish notation (RPN) stack\&. "
.ti -1c
.RI "struct \fBPrintLanguage::NodePending\fP"
.br
.RI "A pending data-flow node; waiting to be placed on the reverse polish notation stack\&. "
.ti -1c
.RI "struct \fBPrintLanguage::Atom\fP"
.br
.RI "A single non-operator token emitted by the decompiler\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classes for printing tokens in a high-level language\&. 


.PP
Definition in file \fBprintlanguage\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
