.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/printc.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/printc.hh \- Classes to support the c-language back-end of the decompiler\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'printlanguage\&.hh'\fP
.br
\fC#include 'comment\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrintCCapability\fP"
.br
.RI "Factory and static initializer for the 'c-language' back-end to the decompiler\&. "
.ti -1c
.RI "struct \fBPartialSymbolEntry\fP"
.br
.RI "A structure for pushing nested fields to the RPN stack\&. "
.ti -1c
.RI "class \fBPrintC\fP"
.br
.RI "The c-language token emitter\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classes to support the c-language back-end of the decompiler\&. 


.PP
Definition in file \fBprintc\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
