.TH "PrintLanguage::ReversePolish" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrintLanguage::ReversePolish \- An entry on the reverse polish notation (RPN) stack\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <printlanguage\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBOpToken\fP * \fBtok\fP"
.br
.RI "The operator token\&. "
.ti -1c
.RI "int4 \fBvisited\fP"
.br
.RI "The current stage of printing for the operator\&. "
.ti -1c
.RI "bool \fBparen\fP"
.br
.RI "True if parentheses are required\&. "
.ti -1c
.RI "const \fBPcodeOp\fP * \fBop\fP"
.br
.RI "The \fBPcodeOp\fP associated with the operator token\&. "
.ti -1c
.RI "int4 \fBid\fP"
.br
.RI "The id of the token group which \fBthis\fP belongs to\&. "
.ti -1c
.RI "int4 \fBid2\fP"
.br
.RI "The id of the token group \fBthis\fP surrounds (for surround operator tokens) "
.in -1c
.SH "Detailed Description"
.PP 
An entry on the reverse polish notation (RPN) stack\&. 
.PP
Definition at line 166 of file printlanguage\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "int4 PrintLanguage::ReversePolish::id"

.PP
The id of the token group which \fBthis\fP belongs to\&. 
.PP
Definition at line 171 of file printlanguage\&.hh\&.
.SS "int4 PrintLanguage::ReversePolish::id2\fC [mutable]\fP"

.PP
The id of the token group \fBthis\fP surrounds (for surround operator tokens) 
.PP
Definition at line 172 of file printlanguage\&.hh\&.
.SS "const \fBPcodeOp\fP* PrintLanguage::ReversePolish::op"

.PP
The \fBPcodeOp\fP associated with the operator token\&. 
.PP
Definition at line 170 of file printlanguage\&.hh\&.
.SS "bool PrintLanguage::ReversePolish::paren"

.PP
True if parentheses are required\&. 
.PP
Definition at line 169 of file printlanguage\&.hh\&.
.SS "const \fBOpToken\fP* PrintLanguage::ReversePolish::tok"

.PP
The operator token\&. 
.PP
Definition at line 167 of file printlanguage\&.hh\&.
.SS "int4 PrintLanguage::ReversePolish::visited"

.PP
The current stage of printing for the operator\&. 
.PP
Definition at line 168 of file printlanguage\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
