.TH "PrototypePieces" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrototypePieces \- Raw components of a function prototype (obtained from parsing source code)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fspec\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProtoModel\fP * \fBmodel\fP"
.br
.RI "(Optional) model on which prototype is based "
.ti -1c
.RI "string \fBname\fP"
.br
.RI "Identifier (function name) associated with prototype\&. "
.ti -1c
.RI "\fBDatatype\fP * \fBouttype\fP"
.br
.RI "Return data-type\&. "
.ti -1c
.RI "vector< \fBDatatype\fP * > \fBintypes\fP"
.br
.RI "Input data-types\&. "
.ti -1c
.RI "vector< string > \fBinnames\fP"
.br
.RI "Identifiers for input types\&. "
.ti -1c
.RI "bool \fBdotdotdot\fP"
.br
.RI "True if prototype takes variable arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Raw components of a function prototype (obtained from parsing source code) 
.PP
Definition at line 1035 of file fspec\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "bool PrototypePieces::dotdotdot"

.PP
True if prototype takes variable arguments\&. 
.PP
Definition at line 1041 of file fspec\&.hh\&.
.SS "vector<string> PrototypePieces::innames"

.PP
Identifiers for input types\&. 
.PP
Definition at line 1040 of file fspec\&.hh\&.
.SS "vector<\fBDatatype\fP *> PrototypePieces::intypes"

.PP
Input data-types\&. 
.PP
Definition at line 1039 of file fspec\&.hh\&.
.SS "\fBProtoModel\fP* PrototypePieces::model"

.PP
(Optional) model on which prototype is based 
.PP
Definition at line 1036 of file fspec\&.hh\&.
.SS "string PrototypePieces::name"

.PP
Identifier (function name) associated with prototype\&. 
.PP
Definition at line 1037 of file fspec\&.hh\&.
.SS "\fBDatatype\fP* PrototypePieces::outtype"

.PP
Return data-type\&. 
.PP
Definition at line 1038 of file fspec\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
