.TH "ProtoStore" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProtoStore \- A collection parameter descriptions making up a function prototype\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fspec\&.hh>\fP
.PP
Inherited by \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ProtoStore\fP (void)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual \fBProtoParameter\fP * \fBsetInput\fP (int4 i, const string &nm, const \fBParameterPieces\fP &pieces)=0"
.br
.RI "Establish name, data-type, storage of a specific input parameter\&. "
.ti -1c
.RI "virtual void \fBclearInput\fP (int4 i)=0"
.br
.RI "Clear the input parameter at the specified slot\&. "
.ti -1c
.RI "virtual void \fBclearAllInputs\fP (void)=0"
.br
.RI "Clear all input parameters (and any backing symbols) "
.ti -1c
.RI "virtual int4 \fBgetNumInputs\fP (void) const =0"
.br
.RI "Get the number of input parameters for \fBthis\fP prototype\&. "
.ti -1c
.RI "virtual \fBProtoParameter\fP * \fBgetInput\fP (int4 i)=0"
.br
.RI "Get the i-th input parameter (or NULL if it doesn't exist) "
.ti -1c
.RI "virtual \fBProtoParameter\fP * \fBsetOutput\fP (const \fBParameterPieces\fP &piece)=0"
.br
.RI "Establish the data-type and storage of the return value\&. "
.ti -1c
.RI "virtual void \fBclearOutput\fP (void)=0"
.br
.RI "Clear the return value to TYPE_VOID\&. "
.ti -1c
.RI "virtual \fBProtoParameter\fP * \fBgetOutput\fP (void)=0"
.br
.RI "Get the return-value description\&. "
.ti -1c
.RI "virtual \fBProtoStore\fP * \fBclone\fP (void) const =0"
.br
.RI "Clone the entire collection of parameter descriptions\&. "
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const =0"
.br
.RI "Save any parameters that are not backed by symbols to an XML stream\&. "
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBProtoModel\fP *model)=0"
.br
.RI "Restore any internal parameter descriptions from an XML stream\&. "
.in -1c
.SH "Detailed Description"
.PP 
A collection parameter descriptions making up a function prototype\&. 

A unified interface for accessing descriptions of individual parameters in a function prototype\&. Both input parameters and return values are described\&. 
.PP
Definition at line 903 of file fspec\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ProtoStore::~ProtoStore (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 905 of file fspec\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ProtoStore::clearAllInputs (void)\fC [pure virtual]\fP"

.PP
Clear all input parameters (and any backing symbols) 
.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual void ProtoStore::clearInput (int4 i)\fC [pure virtual]\fP"

.PP
Clear the input parameter at the specified slot\&. The parameter is excised, any following parameters are shifted to fill its spot\&. If there is a backing \fBSymbol\fP, it is removed from the \fBSymbolTable\fP 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP is the specified parameter slot to remove 
.RE
.PP

.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual void ProtoStore::clearOutput (void)\fC [pure virtual]\fP"

.PP
Clear the return value to TYPE_VOID\&. 
.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual \fBProtoStore\fP* ProtoStore::clone (void) const\fC [pure virtual]\fP"

.PP
Clone the entire collection of parameter descriptions\&. 
.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual \fBProtoParameter\fP* ProtoStore::getInput (int4 i)\fC [pure virtual]\fP"

.PP
Get the i-th input parameter (or NULL if it doesn't exist) 
.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual int4 ProtoStore::getNumInputs (void) const\fC [pure virtual]\fP"

.PP
Get the number of input parameters for \fBthis\fP prototype\&. 
.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual \fBProtoParameter\fP* ProtoStore::getOutput (void)\fC [pure virtual]\fP"

.PP
Get the return-value description\&. 
.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual void ProtoStore::restoreXml (const \fBElement\fP * el, \fBProtoModel\fP * model)\fC [pure virtual]\fP"

.PP
Restore any internal parameter descriptions from an XML stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIel\fP is a root <internallist> element containing <param> and <retparam> sub-tags\&. 
.br
\fImodel\fP is prototype model for determining storage for unassigned parameters 
.RE
.PP

.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual void ProtoStore::saveXml (ostream & s) const\fC [pure virtual]\fP"

.PP
Save any parameters that are not backed by symbols to an XML stream\&. Symbols are stored elsewhere, so symbol backed parameters are not serialized\&. If there are any internal parameters an <internallist> tag is emitted\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the output stream 
.RE
.PP

.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual \fBProtoParameter\fP* ProtoStore::setInput (int4 i, const string & nm, const \fBParameterPieces\fP & pieces)\fC [pure virtual]\fP"

.PP
Establish name, data-type, storage of a specific input parameter\&. This either allocates a new parameter or replaces the existing one at the specified input slot\&. If there is a backing symbol table, a \fBSymbol\fP is created or modified\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP is the specified input slot 
.br
\fInm\fP is the (optional) name of the parameter 
.br
\fIpieces\fP holds the raw storage address and data-type to set 
.RE
.PP
\fBReturns:\fP
.RS 4
the new/modified \fBProtoParameter\fP 
.RE
.PP

.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.
.SS "virtual \fBProtoParameter\fP* ProtoStore::setOutput (const \fBParameterPieces\fP & piece)\fC [pure virtual]\fP"

.PP
Establish the data-type and storage of the return value\&. This either allocates a new parameter or replaces the existing one\&. A \fIvoid\fP return value can be specified with an \fIinvalid\fP address and TYPE_VOID data-type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpiece\fP holds the raw storage address and data-type to set 
.RE
.PP
\fBReturns:\fP
.RS 4
the new/modified \fBProtoParameter\fP 
.RE
.PP

.PP
Implemented in \fBProtoStoreInternal\fP, and \fBProtoStoreSymbol\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
