.TH "rangemap< _recordtype >" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rangemap< _recordtype >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rangemap\&.hh>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPartIterator\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _recordtype::linetype \fBlinetype\fP"
.br
.ti -1c
.RI "typedef _recordtype::subsorttype \fBsubsorttype\fP"
.br
.ti -1c
.RI "typedef _recordtype::inittype \fBinittype\fP"
.br
.ti -1c
.RI "typedef \fBPartIterator\fP \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP (void) const"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "std::list< _recordtype >::\fBconst_iterator\fP \fBbegin_list\fP (void) const"
.br
.ti -1c
.RI "std::list< _recordtype >::\fBconst_iterator\fP \fBend_list\fP (void) const"
.br
.ti -1c
.RI "std::list< _recordtype >::iterator \fBbegin_list\fP (void)"
.br
.ti -1c
.RI "std::list< _recordtype >::iterator \fBend_list\fP (void)"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP (void) const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP (void) const"
.br
.ti -1c
.RI "std::pair< \fBconst_iterator\fP, \fBconst_iterator\fP > \fBfind\fP (\fBlinetype\fP a) const"
.br
.ti -1c
.RI "std::pair< \fBconst_iterator\fP, \fBconst_iterator\fP > \fBfind\fP (\fBlinetype\fP a, const \fBsubsorttype\fP &subsort1, const \fBsubsorttype\fP &subsort2) const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBfind_firstafter\fP (\fBlinetype\fP point) const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBfind_lastbefore\fP (\fBlinetype\fP point) const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBfind_overlap\fP (\fBlinetype\fP point, \fBlinetype\fP \fBend\fP) const"
.br
.ti -1c
.RI "std::list< _recordtype >::iterator \fBinsert\fP (const \fBinittype\fP &data, \fBlinetype\fP a, \fBlinetype\fP b)"
.br
.ti -1c
.RI "void \fBerase\fP (typename std::list< _recordtype >::iterator v)"
.br
.ti -1c
.RI "void \fBerase\fP (\fBconst_iterator\fP iter)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _recordtype>
.br
class rangemap< _recordtype >"

.PP
Definition at line 47 of file rangemap\&.hh\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _recordtype> typedef \fBPartIterator\fP \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP"

.PP
Definition at line 96 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> typedef _recordtype::inittype \fBrangemap\fP< _recordtype >::\fBinittype\fP"

.PP
Definition at line 52 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> typedef _recordtype::linetype \fBrangemap\fP< _recordtype >::\fBlinetype\fP"

.PP
Definition at line 50 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> typedef _recordtype::subsorttype \fBrangemap\fP< _recordtype >::\fBsubsorttype\fP"

.PP
Definition at line 51 of file rangemap\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _recordtype> \fBconst_iterator\fP \fBrangemap\fP< _recordtype >::begin (void) const\fC [inline]\fP"

.PP
Definition at line 112 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> std::list<_recordtype>::\fBconst_iterator\fP \fBrangemap\fP< _recordtype >::begin_list (void) const\fC [inline]\fP"

.PP
Definition at line 107 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> std::list<_recordtype>::iterator \fBrangemap\fP< _recordtype >::begin_list (void)\fC [inline]\fP"

.PP
Definition at line 109 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> void \fBrangemap\fP< _recordtype >::clear (void)\fC [inline]\fP"

.PP
Definition at line 106 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> bool \fBrangemap\fP< _recordtype >::empty (void) const\fC [inline]\fP"

.PP
Definition at line 105 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBconst_iterator\fP \fBrangemap\fP< _recordtype >::end (void) const\fC [inline]\fP"

.PP
Definition at line 113 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> std::list<_recordtype>::\fBconst_iterator\fP \fBrangemap\fP< _recordtype >::end_list (void) const\fC [inline]\fP"

.PP
Definition at line 108 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> std::list<_recordtype>::iterator \fBrangemap\fP< _recordtype >::end_list (void)\fC [inline]\fP"

.PP
Definition at line 110 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> void \fBrangemap\fP< _recordtype >::erase (typename std::list< _recordtype >::iterator v)"

.PP
Definition at line 237 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> void \fBrangemap\fP< _recordtype >::erase (\fBconst_iterator\fP iter)\fC [inline]\fP"

.PP
Definition at line 134 of file rangemap\&.hh\&.
.SS "template<typename _recordtype > std::pair< typename \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP, typename \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP > \fBrangemap\fP< _recordtype >::find (\fBlinetype\fP a) const"

.PP
Definition at line 286 of file rangemap\&.hh\&.
.SS "template<typename _recordtype > std::pair< typename \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP, typename \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP > \fBrangemap\fP< _recordtype >::find (\fBlinetype\fP a, const \fBsubsorttype\fP & subsort1, const \fBsubsorttype\fP & subsort2) const"

.PP
Definition at line 305 of file rangemap\&.hh\&.
.SS "template<typename _recordtype > \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP \fBrangemap\fP< _recordtype >::find_firstafter (\fBlinetype\fP point) const"

.PP
Definition at line 339 of file rangemap\&.hh\&.
.SS "template<typename _recordtype > \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP \fBrangemap\fP< _recordtype >::find_lastbefore (\fBlinetype\fP point) const"

.PP
Definition at line 323 of file rangemap\&.hh\&.
.SS "template<typename _recordtype > \fBrangemap\fP< _recordtype >::\fBconst_iterator\fP \fBrangemap\fP< _recordtype >::find_overlap (\fBlinetype\fP point, \fBlinetype\fP end) const"

.PP
Definition at line 356 of file rangemap\&.hh\&.
.SS "template<typename _recordtype > std::list< _recordtype >::iterator \fBrangemap\fP< _recordtype >::insert (const \fBinittype\fP & data, \fBlinetype\fP a, \fBlinetype\fP b)"

.PP
Definition at line 179 of file rangemap\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
