.TH "rangemap< _recordtype >::PartIterator" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rangemap< _recordtype >::PartIterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rangemap\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartIterator\fP (void)"
.br
.ti -1c
.RI "\fBPartIterator\fP (typename std::multiset< AddrRange >::\fBconst_iterator\fP i)"
.br
.ti -1c
.RI "_recordtype & \fBoperator *\fP (void)"
.br
.ti -1c
.RI "\fBPartIterator\fP & \fBoperator++\fP (void)"
.br
.ti -1c
.RI "\fBPartIterator\fP \fBoperator++\fP (int i)"
.br
.ti -1c
.RI "\fBPartIterator\fP & \fBoperator\-\-\fP (void)"
.br
.ti -1c
.RI "\fBPartIterator\fP \fBoperator\-\-\fP (int i)"
.br
.ti -1c
.RI "\fBPartIterator\fP & \fBoperator=\fP (const \fBPartIterator\fP &op2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPartIterator\fP &op2) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPartIterator\fP &op2) const"
.br
.ti -1c
.RI "std::list< _recordtype >::iterator \fBgetValueIter\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _recordtype>
.br
class rangemap< _recordtype >::PartIterator"

.PP
Definition at line 72 of file rangemap\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _recordtype> \fBrangemap\fP< _recordtype >::PartIterator::PartIterator (void)\fC [inline]\fP"

.PP
Definition at line 75 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBrangemap\fP< _recordtype >::PartIterator::PartIterator (typename std::multiset< AddrRange >::\fBconst_iterator\fP i)\fC [inline]\fP"

.PP
Definition at line 76 of file rangemap\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _recordtype> std::list<_recordtype>::iterator \fBrangemap\fP< _recordtype >::PartIterator::getValueIter (void) const\fC [inline]\fP"

.PP
Definition at line 93 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> _recordtype& \fBrangemap\fP< _recordtype >::PartIterator::operator * (void)\fC [inline]\fP"

.PP
Definition at line 77 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> bool \fBrangemap\fP< _recordtype >::PartIterator::operator!= (const \fBPartIterator\fP & op2) const\fC [inline]\fP"

.PP
Definition at line 90 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBPartIterator\fP& \fBrangemap\fP< _recordtype >::PartIterator::operator++ (void)\fC [inline]\fP"

.PP
Definition at line 78 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBPartIterator\fP \fBrangemap\fP< _recordtype >::PartIterator::operator++ (int i)\fC [inline]\fP"

.PP
Definition at line 79 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBPartIterator\fP& \fBrangemap\fP< _recordtype >::PartIterator::operator\-\- (void)\fC [inline]\fP"

.PP
Definition at line 81 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBPartIterator\fP \fBrangemap\fP< _recordtype >::PartIterator::operator\-\- (int i)\fC [inline]\fP"

.PP
Definition at line 82 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> \fBPartIterator\fP& \fBrangemap\fP< _recordtype >::PartIterator::operator= (const \fBPartIterator\fP & op2)\fC [inline]\fP"

.PP
Definition at line 84 of file rangemap\&.hh\&.
.SS "template<typename _recordtype> bool \fBrangemap\fP< _recordtype >::PartIterator::operator== (const \fBPartIterator\fP & op2) const\fC [inline]\fP"

.PP
Definition at line 87 of file rangemap\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
