.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/raw_arch.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/raw_arch.hh \- Bare bones capability for treating a file as a raw executable image\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sleigh_arch\&.hh'\fP
.br
\fC#include 'loadimage\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRawBinaryArchitectureCapability\fP"
.br
.RI "Extension point for building an \fBArchitecture\fP that reads in raw images\&. "
.ti -1c
.RI "class \fBRawBinaryArchitecture\fP"
.br
.RI "\fBArchitecture\fP that reads its binary as a raw file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Bare bones capability for treating a file as a raw executable image\&. 


.PP
Definition in file \fBraw_arch\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
