.TH "RecovError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecovError \- A generic recoverable error\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <error\&.hh>\fP
.PP
Inherits \fBLowlevelError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecovError\fP (const string &s)"
.br
.RI "Initialize the error with an explanatory string\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A generic recoverable error\&. 

This error is the most basic form of recoverable error, meaning there is some problem that the user did not take into account\&. 
.PP
Definition at line 55 of file error\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RecovError::RecovError (const string & s)\fC [inline]\fP"

.PP
Initialize the error with an explanatory string\&. 
.PP
Definition at line 57 of file error\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
