.TH "RelativeRecord" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RelativeRecord
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sleigh\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVarnodeData\fP * \fBdataptr\fP"
.br
.ti -1c
.RI "\fBuintb\fP \fBcalling_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file sleigh\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuintb\fP RelativeRecord::calling_index"

.PP
Definition at line 25 of file sleigh\&.hh\&.
.SS "\fBVarnodeData\fP* RelativeRecord::dataptr"

.PP
Definition at line 24 of file sleigh\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
