.TH "RHSConstant" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RHSConstant
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherited by \fBConstantAbsolute\fP, \fBConstantConsumed\fP, \fBConstantExpression\fP, \fBConstantHeritageKnown\fP, \fBConstantIsConstant\fP, \fBConstantNamed\fP, \fBConstantNZMask\fP, \fBConstantOffset\fP, and \fBConstantVarnodeSize\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~RHSConstant\fP (void)"
.br
.ti -1c
.RI "virtual \fBRHSConstant\fP * \fBclone\fP (void)=0"
.br
.ti -1c
.RI "virtual \fBuintb\fP \fBgetConstant\fP (\fBUnifyState\fP &state) const =0"
.br
.ti -1c
.RI "virtual void \fBwriteExpression\fP (ostream &s, \fBUnifyCPrinter\fP &printstate) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual RHSConstant::~RHSConstant (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 60 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBRHSConstant\fP* RHSConstant::clone (void)\fC [pure virtual]\fP"

.PP
Implemented in \fBConstantExpression\fP, \fBConstantVarnodeSize\fP, \fBConstantHeritageKnown\fP, \fBConstantIsConstant\fP, \fBConstantOffset\fP, \fBConstantConsumed\fP, \fBConstantNZMask\fP, \fBConstantAbsolute\fP, and \fBConstantNamed\fP\&.
.SS "virtual \fBuintb\fP RHSConstant::getConstant (\fBUnifyState\fP & state) const\fC [pure virtual]\fP"

.PP
Implemented in \fBConstantExpression\fP, \fBConstantVarnodeSize\fP, \fBConstantHeritageKnown\fP, \fBConstantIsConstant\fP, \fBConstantOffset\fP, \fBConstantConsumed\fP, \fBConstantNZMask\fP, \fBConstantAbsolute\fP, and \fBConstantNamed\fP\&.
.SS "virtual void RHSConstant::writeExpression (ostream & s, \fBUnifyCPrinter\fP & printstate) const\fC [pure virtual]\fP"

.PP
Implemented in \fBConstantExpression\fP, \fBConstantVarnodeSize\fP, \fBConstantHeritageKnown\fP, \fBConstantIsConstant\fP, \fBConstantOffset\fP, \fBConstantConsumed\fP, \fBConstantNZMask\fP, \fBConstantAbsolute\fP, and \fBConstantNamed\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
