.TH "RtlPair" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtlPair
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slgh_compile\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRtlPair\fP (void)"
.br
.ti -1c
.RI "\fBRtlPair\fP (\fBConstructTpl\fP *sec, \fBSymbolScope\fP *sc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConstructTpl\fP * \fBsection\fP"
.br
.ti -1c
.RI "\fBSymbolScope\fP * \fBscope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file slgh_compile\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RtlPair::RtlPair (void)\fC [inline]\fP"

.PP
Definition at line 27 of file slgh_compile\&.hh\&.
.SS "RtlPair::RtlPair (\fBConstructTpl\fP * sec, \fBSymbolScope\fP * sc)\fC [inline]\fP"

.PP
Definition at line 28 of file slgh_compile\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSymbolScope\fP* RtlPair::scope"

.PP
Definition at line 26 of file slgh_compile\&.hh\&.
.SS "\fBConstructTpl\fP* RtlPair::section"

.PP
Definition at line 25 of file slgh_compile\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
