.TH "SectionSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SectionSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSleighSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSectionSymbol\fP (const string &nm, int4 id)"
.br
.ti -1c
.RI "int4 \fBgetTemplateId\fP (void) const"
.br
.ti -1c
.RI "void \fBincrementDefineCount\fP (void)"
.br
.ti -1c
.RI "void \fBincrementRefCount\fP (void)"
.br
.ti -1c
.RI "int4 \fBgetDefineCount\fP (void) const"
.br
.ti -1c
.RI "int4 \fBgetRefCount\fP (void) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 116 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SectionSymbol::SectionSymbol (const string & nm, int4 id)\fC [inline]\fP"

.PP
Definition at line 121 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "int4 SectionSymbol::getDefineCount (void) const\fC [inline]\fP"

.PP
Definition at line 125 of file slghsymbol\&.hh\&.
.SS "int4 SectionSymbol::getRefCount (void) const\fC [inline]\fP"

.PP
Definition at line 126 of file slghsymbol\&.hh\&.
.SS "int4 SectionSymbol::getTemplateId (void) const\fC [inline]\fP"

.PP
Definition at line 122 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP SectionSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 127 of file slghsymbol\&.hh\&.
.SS "void SectionSymbol::incrementDefineCount (void)\fC [inline]\fP"

.PP
Definition at line 123 of file slghsymbol\&.hh\&.
.SS "void SectionSymbol::incrementRefCount (void)\fC [inline]\fP"

.PP
Definition at line 124 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
