.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/semantics.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/semantics.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'context\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstTpl\fP"
.br
.ti -1c
.RI "class \fBVarnodeTpl\fP"
.br
.ti -1c
.RI "class \fBHandleTpl\fP"
.br
.ti -1c
.RI "class \fBOpTpl\fP"
.br
.ti -1c
.RI "class \fBConstructTpl\fP"
.br
.ti -1c
.RI "class \fBPcodeBuilder\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUILD\fP   \fBCPUI_MULTIEQUAL\fP"
.br
.ti -1c
.RI "#define \fBDELAY_SLOT\fP   \fBCPUI_INDIRECT\fP"
.br
.ti -1c
.RI "#define \fBCROSSBUILD\fP   \fBCPUI_PTRSUB\fP"
.br
.ti -1c
.RI "#define \fBMACROBUILD\fP   \fBCPUI_CAST\fP"
.br
.ti -1c
.RI "#define \fBLABELBUILD\fP   \fBCPUI_PTRADD\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUILD   \fBCPUI_MULTIEQUAL\fP"

.PP
Definition at line 23 of file semantics\&.hh\&.
.SS "#define CROSSBUILD   \fBCPUI_PTRSUB\fP"

.PP
Definition at line 25 of file semantics\&.hh\&.
.SS "#define DELAY_SLOT   \fBCPUI_INDIRECT\fP"

.PP
Definition at line 24 of file semantics\&.hh\&.
.SS "#define LABELBUILD   \fBCPUI_PTRADD\fP"

.PP
Definition at line 27 of file semantics\&.hh\&.
.SS "#define MACROBUILD   \fBCPUI_CAST\fP"

.PP
Definition at line 26 of file semantics\&.hh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
