.TH "ShiftForm" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShiftForm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <double\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBverifyLeft\fP (\fBVarnode\fP *h, \fBVarnode\fP *l, \fBPcodeOp\fP *loop)"
.br
.ti -1c
.RI "bool \fBverifyRight\fP (\fBVarnode\fP *h, \fBVarnode\fP *l, \fBPcodeOp\fP *hiop)"
.br
.ti -1c
.RI "bool \fBapplyRuleLeft\fP (\fBSplitVarnode\fP &i, \fBPcodeOp\fP *loop, bool workishi, \fBFuncdata\fP &data)"
.br
.ti -1c
.RI "bool \fBapplyRuleRight\fP (\fBSplitVarnode\fP &i, \fBPcodeOp\fP *hiop, bool workishi, \fBFuncdata\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 220 of file double\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ShiftForm::applyRuleLeft (\fBSplitVarnode\fP & i, \fBPcodeOp\fP * loop, bool workishi, \fBFuncdata\fP & data)"

.PP
Definition at line 2436 of file double\&.cc\&.
.SS "bool ShiftForm::applyRuleRight (\fBSplitVarnode\fP & i, \fBPcodeOp\fP * hiop, bool workishi, \fBFuncdata\fP & data)"

.PP
Definition at line 2454 of file double\&.cc\&.
.SS "bool ShiftForm::verifyLeft (\fBVarnode\fP * h, \fBVarnode\fP * l, \fBPcodeOp\fP * loop)"

.PP
Definition at line 2369 of file double\&.cc\&.
.SS "bool ShiftForm::verifyRight (\fBVarnode\fP * h, \fBVarnode\fP * l, \fBPcodeOp\fP * hiop)"

.PP
Definition at line 2403 of file double\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
