.TH "SleighPcode" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SleighPcode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slgh_compile\&.hh>\fP
.PP
Inherits \fBPcodeCompile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSleighPcode\fP (void)"
.br
.ti -1c
.RI "void \fBsetCompiler\fP (\fBSleighCompile\fP *comp)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 166 of file slgh_compile\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SleighPcode::SleighPcode (void)\fC [inline]\fP"

.PP
Definition at line 172 of file slgh_compile\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void SleighPcode::setCompiler (\fBSleighCompile\fP * comp)\fC [inline]\fP"

.PP
Definition at line 173 of file slgh_compile\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
