.TH "SleighError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SleighError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <context\&.hh>\fP
.PP
Inherits \fBLowlevelError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSleighError\fP (const string &s)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 176 of file context\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SleighError::SleighError (const string & s)\fC [inline]\fP"

.PP
Definition at line 177 of file context\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
