.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/sleigh_arch.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/sleigh_arch.hh \- \fBArchitecture\fP objects that use a \fBTranslate\fP object derived from \fBSleigh\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'filemanage\&.hh'\fP
.br
\fC#include 'architecture\&.hh'\fP
.br
\fC#include 'sleigh\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompilerTag\fP"
.br
.RI "Contents of a <compiler> tag in a \&.ldefs file\&. "
.ti -1c
.RI "class \fBLanguageDescription\fP"
.br
.RI "Contents of the <language> tag in a \&.ldefs file\&. "
.ti -1c
.RI "class \fBSleighArchitecture\fP"
.br
.RI "An \fBArchitecture\fP that uses the decompiler's native SLEIGH translation engine\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBArchitecture\fP objects that use a \fBTranslate\fP object derived from \fBSleigh\fP\&. 


.PP
Definition in file \fBsleigh_arch\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
