.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/sleighexample.cc" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/sleighexample.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'loadimage\&.hh'\fP
.br
\fC#include 'sleigh\&.hh'\fP
.br
\fC#include 'emulate\&.hh'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyLoadImage\fP"
.br
.ti -1c
.RI "class \fBAssemblyRaw\fP"
.br
.ti -1c
.RI "class \fBPcodeRawOut\fP"
.br
.ti -1c
.RI "class \fBPutsCallBack\fP"
.br
.ti -1c
.RI "class \fBPrintfCallBack\fP"
.br
.ti -1c
.RI "class \fBTerminateCallBack\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 286 of file sleighexample\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
