.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/sleighbase.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/sleighbase.hh \- Base class for applications that process SLEIGH format specifications\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'translate\&.hh'\fP
.br
\fC#include 'slghsymbol\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSleighBase\fP"
.br
.RI "Common core of classes that read or write SLEIGH specification files natively\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base class for applications that process SLEIGH format specifications\&. 


.PP
Definition in file \fBsleighbase\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
