.TH "SpaceSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpaceSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSleighSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpaceSymbol\fP (\fBAddrSpace\fP *spc)"
.br
.ti -1c
.RI "\fBAddrSpace\fP * \fBgetSpace\fP (void) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 99 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpaceSymbol::SpaceSymbol (\fBAddrSpace\fP * spc)\fC [inline]\fP"

.PP
Definition at line 102 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAddrSpace\fP* SpaceSymbol::getSpace (void) const\fC [inline]\fP"

.PP
Definition at line 103 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP SpaceSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 104 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
