.TH "SpecificSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecificSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBTripleSymbol\fP\&.
.PP
Inherited by \fBEndSymbol\fP, \fBFlowDestSymbol\fP, \fBFlowRefSymbol\fP, \fBOperandSymbol\fP, \fBPatternlessSymbol\fP, and \fBStartSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecificSymbol\fP (void)"
.br
.ti -1c
.RI "\fBSpecificSymbol\fP (const string &nm)"
.br
.ti -1c
.RI "virtual \fBVarnodeTpl\fP * \fBgetVarnode\fP (void) const =0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 164 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpecificSymbol::SpecificSymbol (void)\fC [inline]\fP"

.PP
Definition at line 166 of file slghsymbol\&.hh\&.
.SS "SpecificSymbol::SpecificSymbol (const string & nm)\fC [inline]\fP"

.PP
Definition at line 167 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBVarnodeTpl\fP* SpecificSymbol::getVarnode (void) const\fC [pure virtual]\fP"

.PP
Implemented in \fBFlowRefSymbol\fP, \fBFlowDestSymbol\fP, \fBEndSymbol\fP, \fBStartSymbol\fP, \fBOperandSymbol\fP, \fBVarnodeSymbol\fP, and \fBEpsilonSymbol\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
