.TH "SplitFlow" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplitFlow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <subflow\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplitFlow\fP (\fBFuncdata\fP *f, \fBVarnode\fP *root, int4 lowSize)"
.br
.ti -1c
.RI "void \fBdoReplacement\fP (void)"
.br
.ti -1c
.RI "bool \fBdoTrace\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file subflow\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SplitFlow::SplitFlow (\fBFuncdata\fP * f, \fBVarnode\fP * root, int4 lowSize)"

.PP
Definition at line 1532 of file subflow\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void SplitFlow::doReplacement (void)"

.PP
Definition at line 1547 of file subflow\&.cc\&.
.SS "bool SplitFlow::doTrace (void)"

.PP
Definition at line 1616 of file subflow\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
