.TH "StackEqn" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StackEqn \- A stack equation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBcompare\fP (const \fBStackEqn\fP &a, const \fBStackEqn\fP &b)"
.br
.RI "Order two equations\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int4 \fBvar1\fP"
.br
.RI "Variable with 1 coefficient\&. "
.ti -1c
.RI "int4 \fBvar2\fP"
.br
.RI "Variable with -1 coefficient\&. "
.ti -1c
.RI "int4 \fBrhs\fP"
.br
.RI "Right hand side of the equation\&. "
.in -1c
.SH "Detailed Description"
.PP 
A stack equation\&. 
.PP
Definition at line 21 of file coreaction\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool StackEqn::compare (const \fBStackEqn\fP & a, const \fBStackEqn\fP & b)\fC [static]\fP"

.PP
Order two equations\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP is the first equation to compare 
.br
\fIb\fP is the second 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the first equation comes before the second 
.RE
.PP

.PP
Definition at line 51 of file coreaction\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int4 StackEqn::rhs"

.PP
Right hand side of the equation\&. 
.PP
Definition at line 24 of file coreaction\&.cc\&.
.SS "int4 StackEqn::var1"

.PP
Variable with 1 coefficient\&. 
.PP
Definition at line 22 of file coreaction\&.cc\&.
.SS "int4 StackEqn::var2"

.PP
Variable with -1 coefficient\&. 
.PP
Definition at line 23 of file coreaction\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
