.TH "StarQuality" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarQuality
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pcodecompile\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConstTpl\fP \fBid\fP"
.br
.ti -1c
.RI "uint4 \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file pcodecompile\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConstTpl\fP StarQuality::id"

.PP
Definition at line 22 of file pcodecompile\&.hh\&.
.SS "uint4 StarQuality::size"

.PP
Definition at line 23 of file pcodecompile\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
