.TH "SubExpression" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubExpression
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBBinaryExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubExpression\fP (void)"
.br
.ti -1c
.RI "\fBSubExpression\fP (\fBPatternExpression\fP *l, \fBPatternExpression\fP *r)"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetValue\fP (\fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBintb\fP \fBgetSubValue\fP (const vector< \fBintb\fP > &replace, int4 &listpos) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 234 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubExpression::SubExpression (void)\fC [inline]\fP"

.PP
Definition at line 236 of file slghpatexpress\&.hh\&.
.SS "SubExpression::SubExpression (\fBPatternExpression\fP * l, \fBPatternExpression\fP * r)\fC [inline]\fP"

.PP
Definition at line 237 of file slghpatexpress\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBintb\fP SubExpression::getSubValue (const vector< \fBintb\fP > & replace, int4 & listpos) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 902 of file slghpatexpress\&.cc\&.
.SS "\fBintb\fP SubExpression::getValue (\fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBPatternExpression\fP\&.
.PP
Definition at line 894 of file slghpatexpress\&.cc\&.
.SS "void SubExpression::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBBinaryExpression\fP\&.
.PP
Definition at line 910 of file slghpatexpress\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
