.TH "SubfloatFlow" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubfloatFlow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <subflow\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubfloatFlow\fP (\fBFuncdata\fP *f, \fBVarnode\fP *root, int4 prec)"
.br
.ti -1c
.RI "bool \fBdoTrace\fP (void)"
.br
.ti -1c
.RI "void \fBdoReplacement\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 171 of file subflow\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubfloatFlow::SubfloatFlow (\fBFuncdata\fP * f, \fBVarnode\fP * root, int4 prec)"

.PP
Definition at line 2011 of file subflow\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void SubfloatFlow::doReplacement (void)"

.PP
Definition at line 2045 of file subflow\&.cc\&.
.SS "bool SubfloatFlow::doTrace (void)"

.PP
Definition at line 2020 of file subflow\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
