.TH "SubvariableFlow" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubvariableFlow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <subflow\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubvariableFlow\fP (\fBFuncdata\fP *f, \fBVarnode\fP *root, \fBuintb\fP mask, bool aggr, bool sext)"
.br
.ti -1c
.RI "bool \fBdoTrace\fP (void)"
.br
.ti -1c
.RI "void \fBdoReplacement\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file subflow\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubvariableFlow::SubvariableFlow (\fBFuncdata\fP * f, \fBVarnode\fP * root, \fBuintb\fP mask, bool aggr, bool sext)"

.PP
Definition at line 1039 of file subflow\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void SubvariableFlow::doReplacement (void)"

.PP
Definition at line 1091 of file subflow\&.cc\&.
.SS "bool SubvariableFlow::doTrace (void)"

.PP
Definition at line 1066 of file subflow\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
