.TH "SymbolEntry::EntryInitData" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SymbolEntry::EntryInitData \- Initialization data for a \fBSymbolEntry\fP to facilitate a rangemap\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <database\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntryInitData\fP (\fBSymbol\fP *sym, uint4 exfl, \fBAddrSpace\fP *spc, int4 off, const \fBRangeList\fP &ul)"
.br
.RI "\fBConstructor\fP\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSymbolEntry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initialization data for a \fBSymbolEntry\fP to facilitate a rangemap\&. 

This is all the raw pieces of a \fBSymbolEntry\fP for a (non-dynamic) \fBSymbol\fP except the offset of the main address and the size, which are provided by the (rangemap compatible) \fBSymbolEntry\fP constructor\&. 
.PP
Definition at line 67 of file database\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SymbolEntry::EntryInitData::EntryInitData (\fBSymbol\fP * sym, uint4 exfl, \fBAddrSpace\fP * spc, int4 off, const \fBRangeList\fP & ul)\fC [inline]\fP"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 75 of file database\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSymbolEntry\fP\fC [friend]\fP"

.PP
Definition at line 68 of file database\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
