.TH "SymbolScope" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SymbolScope
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSymbolScope\fP (\fBSymbolScope\fP *p, uintm i)"
.br
.ti -1c
.RI "\fBSymbolScope\fP * \fBgetParent\fP (void) const"
.br
.ti -1c
.RI "\fBSleighSymbol\fP * \fBaddSymbol\fP (\fBSleighSymbol\fP *a)"
.br
.ti -1c
.RI "\fBSleighSymbol\fP * \fBfindSymbol\fP (const string &nm) const"
.br
.ti -1c
.RI "SymbolTree::const_iterator \fBbegin\fP (void) const"
.br
.ti -1c
.RI "SymbolTree::const_iterator \fBend\fP (void) const"
.br
.ti -1c
.RI "uintm \fBgetId\fP (void) const"
.br
.ti -1c
.RI "void \fBremoveSymbol\fP (\fBSleighSymbol\fP *a)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSymbolTable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SymbolScope::SymbolScope (\fBSymbolScope\fP * p, uintm i)\fC [inline]\fP"

.PP
Definition at line 60 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSleighSymbol\fP * SymbolScope::addSymbol (\fBSleighSymbol\fP * a)"

.PP
Definition at line 20 of file slghsymbol\&.cc\&.
.SS "SymbolTree::const_iterator SymbolScope::begin (void) const\fC [inline]\fP"

.PP
Definition at line 64 of file slghsymbol\&.hh\&.
.SS "SymbolTree::const_iterator SymbolScope::end (void) const\fC [inline]\fP"

.PP
Definition at line 65 of file slghsymbol\&.hh\&.
.SS "\fBSleighSymbol\fP * SymbolScope::findSymbol (const string & nm) const"

.PP
Definition at line 31 of file slghsymbol\&.cc\&.
.SS "uintm SymbolScope::getId (void) const\fC [inline]\fP"

.PP
Definition at line 66 of file slghsymbol\&.hh\&.
.SS "\fBSymbolScope\fP* SymbolScope::getParent (void) const\fC [inline]\fP"

.PP
Definition at line 61 of file slghsymbol\&.hh\&.
.SS "void SymbolScope::removeSymbol (\fBSleighSymbol\fP * a)\fC [inline]\fP"

.PP
Definition at line 67 of file slghsymbol\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSymbolTable\fP\fC [friend]\fP"

.PP
Definition at line 55 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
