.TH "todo" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBAddrSpaceManager::insertSpace\fP (\fBAddrSpace\fP *spc)\fP" 1c
This really shouldn't be public\&. Need to move the allocation of \fBiop\fP, \fBfspec\fP, and \fBjoin\fP out of \fBArchitecture\fP  
.IP "\fBMember \fBAddrSpaceManager::setDefaultSpace\fP (int4 index)\fP" 1c
This really shouldn't be public 
.PP

