.TH "TokenSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBSleighSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTokenSymbol\fP (\fBToken\fP *t)"
.br
.ti -1c
.RI "\fB~TokenSymbol\fP (void)"
.br
.ti -1c
.RI "\fBToken\fP * \fBgetToken\fP (void) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 107 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TokenSymbol::TokenSymbol (\fBToken\fP * t)\fC [inline]\fP"

.PP
Definition at line 110 of file slghsymbol\&.hh\&.
.SS "TokenSymbol::~TokenSymbol (void)\fC [inline]\fP"

.PP
Definition at line 111 of file slghsymbol\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBToken\fP* TokenSymbol::getToken (void) const\fC [inline]\fP"

.PP
Definition at line 112 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP TokenSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 113 of file slghsymbol\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
