.TH "Token" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <context\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToken\fP (const string &nm, int4 sz, bool be, int4 ind)"
.br
.ti -1c
.RI "int4 \fBgetSize\fP (void) const"
.br
.ti -1c
.RI "bool \fBisBigEndian\fP (void) const"
.br
.ti -1c
.RI "int4 \fBgetIndex\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetName\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file context\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Token::Token (const string & nm, int4 sz, bool be, int4 ind)\fC [inline]\fP"

.PP
Definition at line 28 of file context\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "int4 Token::getIndex (void) const\fC [inline]\fP"

.PP
Definition at line 31 of file context\&.hh\&.
.SS "const string& Token::getName (void) const\fC [inline]\fP"

.PP
Definition at line 32 of file context\&.hh\&.
.SS "int4 Token::getSize (void) const\fC [inline]\fP"

.PP
Definition at line 29 of file context\&.hh\&.
.SS "bool Token::isBigEndian (void) const\fC [inline]\fP"

.PP
Definition at line 30 of file context\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
