.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/translate.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/translate.hh \- Classes for disassembly and pcode generation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pcoderaw\&.hh'\fP
.br
\fC#include 'float\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUnimplError\fP"
.br
.RI "Exception for encountering unimplemented pcode\&. "
.ti -1c
.RI "struct \fBBadDataError\fP"
.br
.RI "Exception for bad instruction data\&. "
.ti -1c
.RI "class \fBTruncationTag\fP"
.br
.RI "Object for describing how a space should be truncated\&. "
.ti -1c
.RI "class \fBPcodeEmit\fP"
.br
.RI "Abstract class for emitting pcode to an application\&. "
.ti -1c
.RI "class \fBAssemblyEmit\fP"
.br
.RI "Abstract class for emitting disassembly to an application\&. "
.ti -1c
.RI "class \fBAddressResolver\fP"
.br
.RI "Abstract class for converting native constants to addresses\&. "
.ti -1c
.RI "class \fBSpacebaseSpace\fP"
.br
.RI "A virtual space \fIstack\fP space\&. "
.ti -1c
.RI "class \fBJoinRecord\fP"
.br
.RI "A record describing how logical values are split\&. "
.ti -1c
.RI "struct \fBJoinRecordCompare\fP"
.br
.RI "Comparator for \fBJoinRecord\fP objects\&. "
.ti -1c
.RI "class \fBAddrSpaceManager\fP"
.br
.RI "A manager for different address spaces\&. "
.ti -1c
.RI "class \fBTranslate\fP"
.br
.RI "The interface to a translation engine for a processor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classes for disassembly and pcode generation\&. 

Classes for keeping track of spaces and registers (for a single architecture)\&. 
.PP
Definition in file \fBtranslate\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
