.TH "TraverseGroupState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraverseGroupState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBTraverseConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTraverseGroupState\fP (int4 i)"
.br
.ti -1c
.RI "void \fBaddTraverse\fP (\fBTraverseConstraint\fP *tc)"
.br
.ti -1c
.RI "\fBTraverseConstraint\fP * \fBgetSubTraverse\fP (int4 slot) const"
.br
.ti -1c
.RI "int4 \fBgetCurrentIndex\fP (void) const"
.br
.ti -1c
.RI "void \fBsetCurrentIndex\fP (int4 val)"
.br
.ti -1c
.RI "int4 \fBgetState\fP (void) const"
.br
.ti -1c
.RI "void \fBsetState\fP (int4 val)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 186 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TraverseGroupState::TraverseGroupState (int4 i)\fC [inline]\fP"

.PP
Definition at line 191 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void TraverseGroupState::addTraverse (\fBTraverseConstraint\fP * tc)\fC [inline]\fP"

.PP
Definition at line 192 of file unify\&.hh\&.
.SS "int4 TraverseGroupState::getCurrentIndex (void) const\fC [inline]\fP"

.PP
Definition at line 194 of file unify\&.hh\&.
.SS "int4 TraverseGroupState::getState (void) const\fC [inline]\fP"

.PP
Definition at line 196 of file unify\&.hh\&.
.SS "\fBTraverseConstraint\fP* TraverseGroupState::getSubTraverse (int4 slot) const\fC [inline]\fP"

.PP
Definition at line 193 of file unify\&.hh\&.
.SS "void TraverseGroupState::setCurrentIndex (int4 val)\fC [inline]\fP"

.PP
Definition at line 195 of file unify\&.hh\&.
.SS "void TraverseGroupState::setState (int4 val)\fC [inline]\fP"

.PP
Definition at line 197 of file unify\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
