.TH "TraverseDescendState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraverseDescendState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBTraverseConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTraverseDescendState\fP (int4 i)"
.br
.ti -1c
.RI "\fBPcodeOp\fP * \fBgetCurrentOp\fP (void) const"
.br
.ti -1c
.RI "void \fBinitialize\fP (\fBVarnode\fP *vn)"
.br
.ti -1c
.RI "bool \fBstep\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 160 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TraverseDescendState::TraverseDescendState (int4 i)\fC [inline]\fP"

.PP
Definition at line 165 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPcodeOp\fP* TraverseDescendState::getCurrentOp (void) const\fC [inline]\fP"

.PP
Definition at line 166 of file unify\&.hh\&.
.SS "void TraverseDescendState::initialize (\fBVarnode\fP * vn)\fC [inline]\fP"

.PP
Definition at line 167 of file unify\&.hh\&.
.SS "bool TraverseDescendState::step (void)\fC [inline]\fP"

.PP
Definition at line 168 of file unify\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
