.TH "TraverseCountState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraverseCountState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.PP
Inherits \fBTraverseConstraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTraverseCountState\fP (int4 i)"
.br
.ti -1c
.RI "int4 \fBgetState\fP (void) const"
.br
.ti -1c
.RI "void \fBinitialize\fP (int4 end)"
.br
.ti -1c
.RI "bool \fBstep\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 176 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TraverseCountState::TraverseCountState (int4 i)\fC [inline]\fP"

.PP
Definition at line 180 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "int4 TraverseCountState::getState (void) const\fC [inline]\fP"

.PP
Definition at line 181 of file unify\&.hh\&.
.SS "void TraverseCountState::initialize (int4 end)\fC [inline]\fP"

.PP
Definition at line 182 of file unify\&.hh\&.
.SS "bool TraverseCountState::step (void)\fC [inline]\fP"

.PP
Definition at line 183 of file unify\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
