.TH "TreeHandler" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xml\&.hh>\fP
.PP
Inherits \fBContentHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTreeHandler\fP (\fBElement\fP *rt)"
.br
.ti -1c
.RI "virtual \fB~TreeHandler\fP (void)"
.br
.ti -1c
.RI "virtual void \fBsetDocumentLocator\fP (\fBLocator\fP locator)"
.br
.ti -1c
.RI "virtual void \fBstartDocument\fP (void)"
.br
.ti -1c
.RI "virtual void \fBendDocument\fP (void)"
.br
.ti -1c
.RI "virtual void \fBstartPrefixMapping\fP (const string &prefix, const string &uri)"
.br
.ti -1c
.RI "virtual void \fBendPrefixMapping\fP (const string &prefix)"
.br
.ti -1c
.RI "virtual void \fBstartElement\fP (const string &namespaceURI, const string &localName, const string &qualifiedName, const \fBAttributes\fP &atts)"
.br
.ti -1c
.RI "virtual void \fBendElement\fP (const string &namespaceURI, const string &localName, const string &qualifiedName)"
.br
.ti -1c
.RI "virtual void \fBcharacters\fP (const char *text, int4 start, int4 length)"
.br
.ti -1c
.RI "virtual void \fBignorableWhitespace\fP (const char *text, int4 start, int4 length)"
.br
.ti -1c
.RI "virtual void \fBprocessingInstruction\fP (const string &target, const string &data)"
.br
.ti -1c
.RI "virtual void \fBsetVersion\fP (const string &val)"
.br
.ti -1c
.RI "virtual void \fBsetEncoding\fP (const string &val)"
.br
.ti -1c
.RI "virtual void \fBskippedEntity\fP (const string &name)"
.br
.ti -1c
.RI "virtual void \fBsetError\fP (const string &errmsg)"
.br
.ti -1c
.RI "const string & \fBgetError\fP (void) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 122 of file xml\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TreeHandler::TreeHandler (\fBElement\fP * rt)\fC [inline]\fP"

.PP
Definition at line 127 of file xml\&.hh\&.
.SS "virtual TreeHandler::~TreeHandler (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 128 of file xml\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void TreeHandler::characters (const char * text, int4 start, int4 length)\fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.SS "virtual void TreeHandler::endDocument (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 131 of file xml\&.hh\&.
.SS "virtual void TreeHandler::endElement (const string & namespaceURI, const string & localName, const string & qualifiedName)\fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.SS "virtual void TreeHandler::endPrefixMapping (const string & prefix)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 133 of file xml\&.hh\&.
.SS "const string& TreeHandler::getError (void) const\fC [inline]\fP"

.PP
Definition at line 145 of file xml\&.hh\&.
.SS "virtual void TreeHandler::ignorableWhitespace (const char * text, int4 start, int4 length)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 139 of file xml\&.hh\&.
.SS "virtual void TreeHandler::processingInstruction (const string & target, const string & data)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 140 of file xml\&.hh\&.
.SS "virtual void TreeHandler::setDocumentLocator (\fBLocator\fP locator)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 129 of file xml\&.hh\&.
.SS "virtual void TreeHandler::setEncoding (const string & val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 142 of file xml\&.hh\&.
.SS "virtual void TreeHandler::setError (const string & errmsg)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 144 of file xml\&.hh\&.
.SS "virtual void TreeHandler::setVersion (const string & val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 141 of file xml\&.hh\&.
.SS "virtual void TreeHandler::skippedEntity (const string & name)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 143 of file xml\&.hh\&.
.SS "virtual void TreeHandler::startDocument (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 130 of file xml\&.hh\&.
.SS "virtual void TreeHandler::startElement (const string & namespaceURI, const string & localName, const string & qualifiedName, const \fBAttributes\fP & atts)\fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.SS "virtual void TreeHandler::startPrefixMapping (const string & prefix, const string & uri)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBContentHandler\fP\&.
.PP
Definition at line 132 of file xml\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
