.TH "TypeOpSegment" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeOpSegment \- Information about the SEGMENTOP op-code\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typeop\&.hh>\fP
.PP
Inherits \fBTypeOp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeOpSegment\fP (\fBTypeFactory\fP *t)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual \fBDatatype\fP * \fBgetInputCast\fP (const \fBPcodeOp\fP *op, int4 slot, const \fBCastStrategy\fP *castStrategy) const"
.br
.RI "Find the data-type of the input to a specific \fBPcodeOp\fP\&. "
.ti -1c
.RI "virtual \fBDatatype\fP * \fBgetOutputToken\fP (const \fBPcodeOp\fP *op, \fBCastStrategy\fP *castStrategy) const"
.br
.RI "Find the data-type of the output that would be assigned by a compiler\&. "
.ti -1c
.RI "virtual void \fBpush\fP (\fBPrintLanguage\fP *lng, const \fBPcodeOp\fP *op) const"
.br
.RI "Push the specific \fBPcodeOp\fP to the emitter's RPN stack\&. "
.ti -1c
.RI "virtual void \fBprintRaw\fP (ostream &s, const \fBPcodeOp\fP *op)"
.br
.RI "Print (for debugging purposes) \fBthis\fP specific \fBPcodeOp\fP to the stream\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Information about the SEGMENTOP op-code\&. 

The segment operator is a placeholder for address mappings (i\&.e\&. from virtual to physical) that a compiler (or processor) may generate as part of its memory model\&. Typically this is of little concern to the high-level code, so this scheme allows the decompiler to track it but ignore it where appropriate, such as in type propagation and printing high-level expressions 
.PP
Definition at line 749 of file typeop\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TypeOpSegment::TypeOpSegment (\fBTypeFactory\fP * t)"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 1677 of file typeop\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDatatype\fP * TypeOpSegment::getInputCast (const \fBPcodeOp\fP * op, int4 slot, const \fBCastStrategy\fP * castStrategy) const\fC [virtual]\fP"

.PP
Find the data-type of the input to a specific \fBPcodeOp\fP\&. Calculate the actual data-type of the input to the specific \fBPcodeOp\fP\&. A \fBnull\fP result indicates the input data-type is the same as or otherwise doesn't need a cast from the data-type of the actual input \fBVarnode\fP 
.PP
\fBParameters:\fP
.RS 4
\fIop\fP is the specific \fBPcodeOp\fP 
.br
\fIslot\fP is the input to consider 
.br
\fIcastStrategy\fP is the current casting strategy 
.RE
.PP
\fBReturns:\fP
.RS 4
the data-type 
.RE
.PP

.PP
Reimplemented from \fBTypeOp\fP\&.
.PP
Definition at line 1707 of file typeop\&.cc\&.
.SS "\fBDatatype\fP * TypeOpSegment::getOutputToken (const \fBPcodeOp\fP * op, \fBCastStrategy\fP * castStrategy) const\fC [virtual]\fP"

.PP
Find the data-type of the output that would be assigned by a compiler\&. Calculate the actual data-type of the output for a specific \fBPcodeOp\fP as would be assigned by a C compiler parsing a grammar containing this op\&. 
.PP
\fBParameters:\fP
.RS 4
\fIop\fP is the specific \fBPcodeOp\fP 
.br
\fIcastStrategy\fP is the current casting strategy 
.RE
.PP
\fBReturns:\fP
.RS 4
the data-type 
.RE
.PP

.PP
Reimplemented from \fBTypeOp\fP\&.
.PP
Definition at line 1701 of file typeop\&.cc\&.
.SS "void TypeOpSegment::printRaw (ostream & s, const \fBPcodeOp\fP * op)\fC [virtual]\fP"

.PP
Print (for debugging purposes) \fBthis\fP specific \fBPcodeOp\fP to the stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the output stream 
.br
\fIop\fP is the specific \fBPcodeOp\fP to print 
.RE
.PP

.PP
Implements \fBTypeOp\fP\&.
.PP
Definition at line 1684 of file typeop\&.cc\&.
.SS "virtual void TypeOpSegment::push (\fBPrintLanguage\fP * lng, const \fBPcodeOp\fP * op) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Push the specific \fBPcodeOp\fP to the emitter's RPN stack\&. Given a specific language and \fBPcodeOp\fP, emit the expression rooted at the operation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlng\fP is the \fBPrintLanguage\fP to emit 
.br
\fIop\fP is the specific \fBPcodeOp\fP 
.RE
.PP

.PP
Implements \fBTypeOp\fP\&.
.PP
Definition at line 756 of file typeop\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
