.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/types.h" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/types.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUINTB8\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int8 \fBintb\fP"
.br
.ti -1c
.RI "typedef uint8 \fBuintb\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UINTB8"

.PP
Definition at line 221 of file types\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int8 \fBintb\fP"

.PP
Definition at line 223 of file types\&.h\&.
.SS "typedef uint8 \fBuintb\fP"

.PP
Definition at line 226 of file types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
