.TH "TypeDeclarator" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeDeclarator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grammar\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeDeclarator\fP (void)"
.br
.ti -1c
.RI "\fBTypeDeclarator\fP (const string &nm)"
.br
.ti -1c
.RI "\fB~TypeDeclarator\fP (void)"
.br
.ti -1c
.RI "\fBDatatype\fP * \fBgetBaseType\fP (void) const"
.br
.ti -1c
.RI "int4 \fBnumModifiers\fP (void) const"
.br
.ti -1c
.RI "const string & \fBgetIdentifier\fP (void) const"
.br
.ti -1c
.RI "\fBProtoModel\fP * \fBgetModel\fP (\fBArchitecture\fP *glb) const"
.br
.ti -1c
.RI "bool \fBgetPrototype\fP (\fBPrototypePieces\fP &pieces, \fBArchitecture\fP *glb) const"
.br
.ti -1c
.RI "bool \fBhasProperty\fP (uint4 mask)"
.br
.ti -1c
.RI "\fBDatatype\fP * \fBbuildType\fP (\fBArchitecture\fP *glb) const"
.br
.ti -1c
.RI "bool \fBisValid\fP (void) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCParse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 163 of file grammar\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TypeDeclarator::TypeDeclarator (void)\fC [inline]\fP"

.PP
Definition at line 171 of file grammar\&.hh\&.
.SS "TypeDeclarator::TypeDeclarator (const string & nm)\fC [inline]\fP"

.PP
Definition at line 172 of file grammar\&.hh\&.
.SS "TypeDeclarator::~TypeDeclarator (void)"

.SH "Member Function Documentation"
.PP 
.SS "\fBDatatype\fP* TypeDeclarator::buildType (\fBArchitecture\fP * glb) const"

.SS "\fBDatatype\fP* TypeDeclarator::getBaseType (void) const\fC [inline]\fP"

.PP
Definition at line 174 of file grammar\&.hh\&.
.SS "const string& TypeDeclarator::getIdentifier (void) const\fC [inline]\fP"

.PP
Definition at line 176 of file grammar\&.hh\&.
.SS "\fBProtoModel\fP* TypeDeclarator::getModel (\fBArchitecture\fP * glb) const"

.SS "bool TypeDeclarator::getPrototype (\fBPrototypePieces\fP & pieces, \fBArchitecture\fP * glb) const"

.SS "bool TypeDeclarator::hasProperty (uint4 mask)\fC [inline]\fP"

.PP
Definition at line 179 of file grammar\&.hh\&.
.SS "bool TypeDeclarator::isValid (void) const"

.SS "int4 TypeDeclarator::numModifiers (void) const\fC [inline]\fP"

.PP
Definition at line 175 of file grammar\&.hh\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBCParse\fP\fC [friend]\fP"

.PP
Definition at line 164 of file grammar\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
