.TH "TypeOpCallother" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeOpCallother \- Information about the CALLOTHER op-code (user defined p-code operations)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typeop\&.hh>\fP
.PP
Inherits \fBTypeOp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeOpCallother\fP (\fBTypeFactory\fP *t)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual void \fBpush\fP (\fBPrintLanguage\fP *lng, const \fBPcodeOp\fP *op) const"
.br
.RI "Push the specific \fBPcodeOp\fP to the emitter's RPN stack\&. "
.ti -1c
.RI "virtual void \fBprintRaw\fP (ostream &s, const \fBPcodeOp\fP *op)"
.br
.RI "Print (for debugging purposes) \fBthis\fP specific \fBPcodeOp\fP to the stream\&. "
.ti -1c
.RI "virtual string \fBgetOperatorName\fP (const \fBPcodeOp\fP *op) const"
.br
.RI "Get the name of the op-code as it should be displayed in context\&. "
.ti -1c
.RI "virtual \fBDatatype\fP * \fBgetInputLocal\fP (const \fBPcodeOp\fP *op, int4 slot) const"
.br
.RI "Find the minimal (or suggested) data-type of an input to \fBthis\fP op-code\&. "
.ti -1c
.RI "virtual \fBDatatype\fP * \fBgetOutputLocal\fP (const \fBPcodeOp\fP *op) const"
.br
.RI "Find the minimal (or suggested) data-type of an output to \fBthis\fP op-code\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Information about the CALLOTHER op-code (user defined p-code operations) 
.PP
Definition at line 281 of file typeop\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TypeOpCallother::TypeOpCallother (\fBTypeFactory\fP * t)"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 653 of file typeop\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDatatype\fP * TypeOpCallother::getInputLocal (const \fBPcodeOp\fP * op, int4 slot) const\fC [virtual]\fP"

.PP
Find the minimal (or suggested) data-type of an input to \fBthis\fP op-code\&. The result should depend only on the op-code itself (and the size of the input) 
.PP
\fBParameters:\fP
.RS 4
\fIop\fP is the \fBPcodeOp\fP being considered 
.br
\fIslot\fP is the input being considered 
.RE
.PP
\fBReturns:\fP
.RS 4
the data-type 
.RE
.PP

.PP
Reimplemented from \fBTypeOp\fP\&.
.PP
Definition at line 697 of file typeop\&.cc\&.
.SS "string TypeOpCallother::getOperatorName (const \fBPcodeOp\fP * op) const\fC [virtual]\fP"

.PP
Get the name of the op-code as it should be displayed in context\&. Depending on the context, the same op-code may get displayed in different ways\&. 
.PP
\fBParameters:\fP
.RS 4
\fIop\fP is the \fBPcodeOp\fP context 
.RE
.PP
\fBReturns:\fP
.RS 4
the display token 
.RE
.PP

.PP
Reimplemented from \fBTypeOp\fP\&.
.PP
Definition at line 679 of file typeop\&.cc\&.
.SS "\fBDatatype\fP * TypeOpCallother::getOutputLocal (const \fBPcodeOp\fP * op) const\fC [virtual]\fP"

.PP
Find the minimal (or suggested) data-type of an output to \fBthis\fP op-code\&. The result should depend only on the op-code itself (and the size of the output) 
.PP
\fBParameters:\fP
.RS 4
\fIop\fP is the \fBPcodeOp\fP being considered 
.RE
.PP
\fBReturns:\fP
.RS 4
the data-type 
.RE
.PP

.PP
Reimplemented from \fBTypeOp\fP\&.
.PP
Definition at line 718 of file typeop\&.cc\&.
.SS "void TypeOpCallother::printRaw (ostream & s, const \fBPcodeOp\fP * op)\fC [virtual]\fP"

.PP
Print (for debugging purposes) \fBthis\fP specific \fBPcodeOp\fP to the stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the output stream 
.br
\fIop\fP is the specific \fBPcodeOp\fP to print 
.RE
.PP

.PP
Implements \fBTypeOp\fP\&.
.PP
Definition at line 660 of file typeop\&.cc\&.
.SS "virtual void TypeOpCallother::push (\fBPrintLanguage\fP * lng, const \fBPcodeOp\fP * op) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Push the specific \fBPcodeOp\fP to the emitter's RPN stack\&. Given a specific language and \fBPcodeOp\fP, emit the expression rooted at the operation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlng\fP is the \fBPrintLanguage\fP to emit 
.br
\fIop\fP is the specific \fBPcodeOp\fP 
.RE
.PP

.PP
Implements \fBTypeOp\fP\&.
.PP
Definition at line 284 of file typeop\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
