.TH "TypeSpecifiers" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeSpecifiers
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grammar\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeSpecifiers\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDatatype\fP * \fBtype_specifier\fP"
.br
.ti -1c
.RI "string \fBfunction_specifier\fP"
.br
.ti -1c
.RI "uint4 \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file grammar\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TypeSpecifiers::TypeSpecifiers (void)\fC [inline]\fP"

.PP
Definition at line 188 of file grammar\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "uint4 TypeSpecifiers::flags"

.PP
Definition at line 187 of file grammar\&.hh\&.
.SS "string TypeSpecifiers::function_specifier"

.PP
Definition at line 186 of file grammar\&.hh\&.
.SS "\fBDatatype\fP* TypeSpecifiers::type_specifier"

.PP
Definition at line 185 of file grammar\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
