.TH "TypeOpFloatInt2Float" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeOpFloatInt2Float \- Information about the FLOAT_INT2FLOAT op-code\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <typeop\&.hh>\fP
.PP
Inherits \fBTypeOpFunc\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeOpFloatInt2Float\fP (\fBTypeFactory\fP *t, const \fBTranslate\fP *trans)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual void \fBpush\fP (\fBPrintLanguage\fP *lng, const \fBPcodeOp\fP *op) const"
.br
.RI "Push the specific \fBPcodeOp\fP to the emitter's RPN stack\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Information about the FLOAT_INT2FLOAT op-code\&. 
.PP
Definition at line 629 of file typeop\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TypeOpFloatInt2Float::TypeOpFloatInt2Float (\fBTypeFactory\fP * t, const \fBTranslate\fP * trans)"

.PP
\fBConstructor\fP\&. 
.PP
Definition at line 1399 of file typeop\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void TypeOpFloatInt2Float::push (\fBPrintLanguage\fP * lng, const \fBPcodeOp\fP * op) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Push the specific \fBPcodeOp\fP to the emitter's RPN stack\&. Given a specific language and \fBPcodeOp\fP, emit the expression rooted at the operation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlng\fP is the \fBPrintLanguage\fP to emit 
.br
\fIop\fP is the specific \fBPcodeOp\fP 
.RE
.PP

.PP
Implements \fBTypeOp\fP\&.
.PP
Definition at line 632 of file typeop\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
