.TH "UnifyState" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnifyState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnifyState\fP (\fBConstraintGroup\fP *uni)"
.br
.ti -1c
.RI "\fB~UnifyState\fP (void)"
.br
.ti -1c
.RI "int4 \fBnumTraverse\fP (void) const"
.br
.ti -1c
.RI "void \fBregisterTraverseConstraint\fP (\fBTraverseConstraint\fP *t)"
.br
.ti -1c
.RI "\fBUnifyDatatype\fP & \fBdata\fP (int4 slot)"
.br
.ti -1c
.RI "\fBTraverseConstraint\fP * \fBgetTraverse\fP (int4 slot) const"
.br
.ti -1c
.RI "\fBFuncdata\fP * \fBgetFunction\fP (void) const"
.br
.ti -1c
.RI "\fBOpBehavior\fP * \fBgetBehavior\fP (\fBOpCode\fP opc)"
.br
.ti -1c
.RI "void \fBsetFunction\fP (\fBFuncdata\fP *f)"
.br
.ti -1c
.RI "void \fBinitialize\fP (int4 id, \fBVarnode\fP *vn)"
.br
.ti -1c
.RI "void \fBinitialize\fP (int4 id, \fBPcodeOp\fP *op)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 607 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnifyState::UnifyState (\fBConstraintGroup\fP * uni)"

.SS "UnifyState::~UnifyState (void)"

.SH "Member Function Documentation"
.PP 
.SS "\fBUnifyDatatype\fP& UnifyState::data (int4 slot)\fC [inline]\fP"

.PP
Definition at line 617 of file unify\&.hh\&.
.SS "\fBOpBehavior\fP* UnifyState::getBehavior (\fBOpCode\fP opc)"

.SS "\fBFuncdata\fP* UnifyState::getFunction (void) const\fC [inline]\fP"

.PP
Definition at line 619 of file unify\&.hh\&.
.SS "\fBTraverseConstraint\fP* UnifyState::getTraverse (int4 slot) const\fC [inline]\fP"

.PP
Definition at line 618 of file unify\&.hh\&.
.SS "void UnifyState::initialize (int4 id, \fBVarnode\fP * vn)"

.SS "void UnifyState::initialize (int4 id, \fBPcodeOp\fP * op)"

.SS "int4 UnifyState::numTraverse (void) const\fC [inline]\fP"

.PP
Definition at line 615 of file unify\&.hh\&.
.SS "void UnifyState::registerTraverseConstraint (\fBTraverseConstraint\fP * t)\fC [inline]\fP"

.PP
Definition at line 616 of file unify\&.hh\&.
.SS "void UnifyState::setFunction (\fBFuncdata\fP * f)\fC [inline]\fP"

.PP
Definition at line 621 of file unify\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
