.TH "UnifyCPrinter" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnifyCPrinter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unify\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnifyCPrinter\fP (void)"
.br
.ti -1c
.RI "int4 \fBgetDepth\fP (void) const"
.br
.ti -1c
.RI "void \fBincDepth\fP (void)"
.br
.ti -1c
.RI "void \fBdecDepth\fP (void)"
.br
.ti -1c
.RI "void \fBprintIndent\fP (ostream &s) const"
.br
.ti -1c
.RI "void \fBprintAbort\fP (ostream &s)"
.br
.ti -1c
.RI "void \fBpopDepth\fP (ostream &s, int4 newdepth)"
.br
.ti -1c
.RI "const string & \fBgetName\fP (int4 id) const"
.br
.ti -1c
.RI "void \fBinitializeRuleAction\fP (\fBConstraintGroup\fP *g, int4 opparam, const vector< \fBOpCode\fP > &olist)"
.br
.ti -1c
.RI "void \fBinitializeBasic\fP (\fBConstraintGroup\fP *g)"
.br
.ti -1c
.RI "void \fBsetClassName\fP (const string &nm)"
.br
.ti -1c
.RI "void \fBaddNames\fP (const map< string, int4 > &nmmap)"
.br
.ti -1c
.RI "void \fBprintVarDecls\fP (ostream &s) const"
.br
.ti -1c
.RI "void \fBprint\fP (ostream &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 626 of file unify\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnifyCPrinter::UnifyCPrinter (void)\fC [inline]\fP"

.PP
Definition at line 639 of file unify\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void UnifyCPrinter::addNames (const map< string, int4 > & nmmap)"

.SS "void UnifyCPrinter::decDepth (void)\fC [inline]\fP"

.PP
Definition at line 642 of file unify\&.hh\&.
.SS "int4 UnifyCPrinter::getDepth (void) const\fC [inline]\fP"

.PP
Definition at line 640 of file unify\&.hh\&.
.SS "const string& UnifyCPrinter::getName (int4 id) const\fC [inline]\fP"

.PP
Definition at line 646 of file unify\&.hh\&.
.SS "void UnifyCPrinter::incDepth (void)\fC [inline]\fP"

.PP
Definition at line 641 of file unify\&.hh\&.
.SS "void UnifyCPrinter::initializeBasic (\fBConstraintGroup\fP * g)"

.SS "void UnifyCPrinter::initializeRuleAction (\fBConstraintGroup\fP * g, int4 opparam, const vector< \fBOpCode\fP > & olist)"

.SS "void UnifyCPrinter::popDepth (ostream & s, int4 newdepth)"

.SS "void UnifyCPrinter::print (ostream & s)"

.SS "void UnifyCPrinter::printAbort (ostream & s)"

.SS "void UnifyCPrinter::printIndent (ostream & s) const\fC [inline]\fP"

.PP
Definition at line 643 of file unify\&.hh\&.
.SS "void UnifyCPrinter::printVarDecls (ostream & s) const"

.SS "void UnifyCPrinter::setClassName (const string & nm)\fC [inline]\fP"

.PP
Definition at line 649 of file unify\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
