.TH "ValExpressEquation" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValExpressEquation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghpatexpress\&.hh>\fP
.PP
Inherits \fBPatternEquation\fP\&.
.PP
Inherited by \fBEqualEquation\fP, \fBGreaterEqualEquation\fP, \fBGreaterEquation\fP, \fBLessEqualEquation\fP, \fBLessEquation\fP, and \fBNotEqualEquation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValExpressEquation\fP (\fBPatternValue\fP *l, \fBPatternExpression\fP *r)"
.br
.ti -1c
.RI "virtual bool \fBresolveOperandLeft\fP (\fBOperandResolve\fP &state) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ValExpressEquation\fP (void)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPatternValue\fP * \fBlhs\fP"
.br
.ti -1c
.RI "\fBPatternExpression\fP * \fBrhs\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 370 of file slghpatexpress\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ValExpressEquation::~ValExpressEquation (void)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1235 of file slghpatexpress\&.cc\&.
.SS "ValExpressEquation::ValExpressEquation (\fBPatternValue\fP * l, \fBPatternExpression\fP * r)"

.PP
Definition at line 1228 of file slghpatexpress\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ValExpressEquation::resolveOperandLeft (\fBOperandResolve\fP & state) const\fC [virtual]\fP"

.PP
Implements \fBPatternEquation\fP\&.
.PP
Definition at line 1242 of file slghpatexpress\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPatternValue\fP* ValExpressEquation::lhs\fC [protected]\fP"

.PP
Definition at line 372 of file slghpatexpress\&.hh\&.
.SS "\fBPatternExpression\fP* ValExpressEquation::rhs\fC [protected]\fP"

.PP
Definition at line 373 of file slghpatexpress\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
