.TH "VarnodeSymbol" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VarnodeSymbol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slghsymbol\&.hh>\fP
.PP
Inherits \fBPatternlessSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVarnodeSymbol\fP (void)"
.br
.ti -1c
.RI "\fBVarnodeSymbol\fP (const string &nm, \fBAddrSpace\fP *base, \fBuintb\fP offset, int4 size)"
.br
.ti -1c
.RI "void \fBmarkAsContext\fP (void)"
.br
.ti -1c
.RI "const \fBVarnodeData\fP & \fBgetFixedVarnode\fP (void) const"
.br
.ti -1c
.RI "virtual \fBVarnodeTpl\fP * \fBgetVarnode\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBgetFixedHandle\fP (\fBFixedHandle\fP &hand, \fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual int4 \fBgetSize\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (ostream &s, \fBParserWalker\fP &walker) const"
.br
.ti -1c
.RI "virtual \fBsymbol_type\fP \fBgetType\fP (void) const"
.br
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBsaveXmlHeader\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (const \fBElement\fP *el, \fBSleighBase\fP *trans)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 244 of file slghsymbol\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VarnodeSymbol::VarnodeSymbol (void)\fC [inline]\fP"

.PP
Definition at line 248 of file slghsymbol\&.hh\&.
.SS "VarnodeSymbol::VarnodeSymbol (const string & nm, \fBAddrSpace\fP * base, \fBuintb\fP offset, int4 size)"

.PP
Definition at line 707 of file slghsymbol\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void VarnodeSymbol::getFixedHandle (\fBFixedHandle\fP & hand, \fBParserWalker\fP & walker) const\fC [virtual]\fP"

.PP
Implements \fBTripleSymbol\fP\&.
.PP
Definition at line 722 of file slghsymbol\&.cc\&.
.SS "const \fBVarnodeData\fP& VarnodeSymbol::getFixedVarnode (void) const\fC [inline]\fP"

.PP
Definition at line 251 of file slghsymbol\&.hh\&.
.SS "virtual int4 VarnodeSymbol::getSize (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBTripleSymbol\fP\&.
.PP
Definition at line 254 of file slghsymbol\&.hh\&.
.SS "virtual \fBsymbol_type\fP VarnodeSymbol::getType (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 257 of file slghsymbol\&.hh\&.
.SS "\fBVarnodeTpl\fP * VarnodeSymbol::getVarnode (void) const\fC [virtual]\fP"

.PP
Implements \fBSpecificSymbol\fP\&.
.PP
Definition at line 716 of file slghsymbol\&.cc\&.
.SS "void VarnodeSymbol::markAsContext (void)\fC [inline]\fP"

.PP
Definition at line 250 of file slghsymbol\&.hh\&.
.SS "virtual void VarnodeSymbol::print (ostream & s, \fBParserWalker\fP & walker) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBTripleSymbol\fP\&.
.PP
Definition at line 255 of file slghsymbol\&.hh\&.
.SS "void VarnodeSymbol::restoreXml (const \fBElement\fP * el, \fBSleighBase\fP * trans)\fC [virtual]\fP"

.PP
Reimplemented from \fBPatternlessSymbol\fP\&.
.PP
Definition at line 752 of file slghsymbol\&.cc\&.
.SS "void VarnodeSymbol::saveXml (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPatternlessSymbol\fP\&.
.PP
Definition at line 731 of file slghsymbol\&.cc\&.
.SS "void VarnodeSymbol::saveXmlHeader (ostream & s) const\fC [virtual]\fP"

.PP
Reimplemented from \fBSleighSymbol\fP\&.
.PP
Definition at line 744 of file slghsymbol\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
