.TH "WithBlock" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithBlock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slgh_compile\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWithBlock\fP (void)"
.br
.ti -1c
.RI "void \fBset\fP (\fBSubtableSymbol\fP *s, \fBPatternEquation\fP *pq, vector< \fBContextChange\fP * > *cvec)"
.br
.ti -1c
.RI "\fB~WithBlock\fP (void)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPatternEquation\fP * \fBcollectAndPrependPattern\fP (const list< \fBWithBlock\fP > &stack, \fBPatternEquation\fP *pateq)"
.br
.ti -1c
.RI "static vector< \fBContextChange\fP * > * \fBcollectAndPrependContext\fP (const list< \fBWithBlock\fP > &stack, vector< \fBContextChange\fP * > *contvec)"
.br
.ti -1c
.RI "static \fBSubtableSymbol\fP * \fBgetCurrentSubtable\fP (const list< \fBWithBlock\fP > &stack)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file slgh_compile\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WithBlock::WithBlock (void)\fC [inline]\fP"

.PP
Definition at line 73 of file slgh_compile\&.hh\&.
.SS "WithBlock::~WithBlock (void)"

.PP
Definition at line 127 of file slgh_compile\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< \fBContextChange\fP * > * WithBlock::collectAndPrependContext (const list< \fBWithBlock\fP > & stack, vector< \fBContextChange\fP * > * contvec)\fC [static]\fP"

.PP
Definition at line 149 of file slgh_compile\&.cc\&.
.SS "\fBPatternEquation\fP * WithBlock::collectAndPrependPattern (const list< \fBWithBlock\fP > & stack, \fBPatternEquation\fP * pateq)\fC [static]\fP"

.PP
Definition at line 137 of file slgh_compile\&.cc\&.
.SS "\fBSubtableSymbol\fP * WithBlock::getCurrentSubtable (const list< \fBWithBlock\fP > & stack)\fC [static]\fP"

.PP
Definition at line 175 of file slgh_compile\&.cc\&.
.SS "void WithBlock::set (\fBSubtableSymbol\fP * s, \fBPatternEquation\fP * pq, vector< \fBContextChange\fP * > * cvec)"

.PP
Definition at line 113 of file slgh_compile\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
