.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/xml.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/xml.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAttributes\fP"
.br
.ti -1c
.RI "class \fBContentHandler\fP"
.br
.ti -1c
.RI "class \fBElement\fP"
.br
.ti -1c
.RI "class \fBDocument\fP"
.br
.ti -1c
.RI "class \fBTreeHandler\fP"
.br
.ti -1c
.RI "class \fBDocumentStorage\fP"
.br
.ti -1c
.RI "struct \fBXmlError\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBLocator\fP"
.br
.ti -1c
.RI "typedef vector< \fBElement\fP * > \fBList\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int4 \fBxml_parse\fP (istream &i, \fBContentHandler\fP *hand, int4 dbg=0)"
.br
.ti -1c
.RI "\fBDocument\fP * \fBxml_tree\fP (istream &i)"
.br
.ti -1c
.RI "void \fBxml_escape\fP (ostream &s, const char *str)"
.br
.ti -1c
.RI "void \fBa_v\fP (ostream &s, const string &attr, const string &val)"
.br
.ti -1c
.RI "void \fBa_v_i\fP (ostream &s, const string &attr, \fBintb\fP val)"
.br
.ti -1c
.RI "void \fBa_v_u\fP (ostream &s, const string &attr, \fBuintb\fP val)"
.br
.ti -1c
.RI "void \fBa_v_b\fP (ostream &s, const string &attr, bool val)"
.br
.ti -1c
.RI "bool \fBxml_readbool\fP (const string &attr)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef vector<\fBElement\fP *> \fBList\fP"

.PP
Definition at line 85 of file xml\&.hh\&.
.SS "typedef void* \fBLocator\fP"

.PP
Definition at line 62 of file xml\&.hh\&.
.SH "Function Documentation"
.PP 
.SS "void a_v (ostream & s, const string & attr, const string & val)\fC [inline]\fP"

.PP
Definition at line 170 of file xml\&.hh\&.
.SS "void a_v_b (ostream & s, const string & attr, bool val)\fC [inline]\fP"

.PP
Definition at line 190 of file xml\&.hh\&.
.SS "void a_v_i (ostream & s, const string & attr, \fBintb\fP val)\fC [inline]\fP"

.PP
Definition at line 178 of file xml\&.hh\&.
.SS "void a_v_u (ostream & s, const string & attr, \fBuintb\fP val)\fC [inline]\fP"

.PP
Definition at line 184 of file xml\&.hh\&.
.SS "void xml_escape (ostream & s, const char * str)"

.SS "int4 xml_parse (istream & i, \fBContentHandler\fP * hand, int4 dbg = \fC0\fP)"

.SS "bool xml_readbool (const string & attr)\fC [inline]\fP"

.PP
Definition at line 201 of file xml\&.hh\&.
.SS "\fBDocument\fP* xml_tree (istream & i)"

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
