.TH "F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/xml_arch.hh" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/re/ghidra_sourcecode/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/xml_arch.hh \- Extension to read executables based on an XML format\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sleigh_arch\&.hh'\fP
.br
\fC#include 'loadimage_xml\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlArchitectureCapability\fP"
.br
.RI "Extension for building an XML format capable \fBArchitecture\fP\&. "
.ti -1c
.RI "class \fBXmlArchitecture\fP"
.br
.RI "An \fBArchitecture\fP that loads executables using an XML format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Extension to read executables based on an XML format\&. 


.PP
Definition in file \fBxml_arch\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
