.TH "XmlArchitecture" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlArchitecture \- An \fBArchitecture\fP that loads executables using an XML format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xml_arch\&.hh>\fP
.PP
Inherits \fBSleighArchitecture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsaveXml\fP (ostream &s) const"
.br
.ti -1c
.RI "virtual void \fBrestoreXml\fP (\fBDocumentStorage\fP &store)"
.br
.RI "Restore the \fBArchitecture\fP state from an XML stream\&. "
.ti -1c
.RI "\fBXmlArchitecture\fP (const string &fname, const string &targ, ostream *estream)"
.br
.RI "\fBConstructor\fP\&. "
.ti -1c
.RI "virtual \fB~XmlArchitecture\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBArchitecture\fP that loads executables using an XML format\&. 
.PP
Definition at line 34 of file xml_arch\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XmlArchitecture::XmlArchitecture (const string & fname, const string & targ, ostream * estream)"

.PP
\fBConstructor\fP\&. This just wraps the base constructor 
.PP
\fBParameters:\fP
.RS 4
\fIfname\fP is the path to the executable file (containing XML) 
.br
\fItarg\fP is the (optional) language id 
.br
\fIestream\fP is the stream to use for the error console 
.RE
.PP

.PP
Definition at line 84 of file xml_arch\&.cc\&.
.SS "virtual XmlArchitecture::~XmlArchitecture (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 43 of file xml_arch\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "void XmlArchitecture::restoreXml (\fBDocumentStorage\fP & store)\fC [virtual]\fP"

.PP
Restore the \fBArchitecture\fP state from an XML stream\&. Read in all the sub-component state from a <save_state> XML tag When adding stuff to this BEWARE: The spec file has already initialized stuff 
.PP
\fBParameters:\fP
.RS 4
\fIstore\fP is document store containing the parsed root tag 
.RE
.PP

.PP
Reimplemented from \fBArchitecture\fP\&.
.PP
Definition at line 106 of file xml_arch\&.cc\&.
.SS "void XmlArchitecture::saveXml (ostream & s) const\fC [virtual]\fP"
Prepend extra stuff to specify binary file and spec 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP is the stream to write to 
.RE
.PP

.PP
Reimplemented from \fBArchitecture\fP\&.
.PP
Definition at line 93 of file xml_arch\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
