.TH "XmlError" 3 "Sun Apr 14 2019" "decompile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xml\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlError\fP (const string &s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBexplain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file xml\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XmlError::XmlError (const string & s)\fC [inline]\fP"

.PP
Definition at line 162 of file xml\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "string XmlError::explain"

.PP
Definition at line 161 of file xml\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for decompile from the source code\&.
